# workflow for calculate snow correction for solar energy
id: 2d4e1c6a-eb70-11f0-9b6c-7c70db10a7e3
name: CalculateCloudCorrectionFactor
entryGraphId: a2df1dee-eba2-11f0-b126-7c70db10a7e3
with:
  csvFile: null
graphs:
  - id: a2df1dee-eba2-11f0-b126-7c70db10a7e3
    name: CloudFactorWorkflow
    nodes:
      - id: c4ea198e-eba2-11f0-b93c-7c70db10a7e3
        name: CsvReader
        type: action
        action: CsvReader
        with:
          format: csv
          inline: |
            env.get("csvFile")

      - id: 9444dbf6-eba3-11f0-bdcb-7c70db10a7e3
        name: PrepareAttribute
        type: action
        action: AttributeManager
        with:
          operations:
          - attribute: year
            method: create
            value:
              env.get("__value")["年"];
          - attribute: 年
            method: remove

          - attribute: month
            method: create
            value:
              env.get("__value")["月"];
          - attribute: 月
            method: remove

          - attribute: daylight_hours
            method: create
            value:
              env.get("__value")["日照時間(時間)"];
          - attribute: 日照時間(時間)
            method: remove

          - attribute: daylight_hours_num
            method: create
            value:
              env.get("__value")["日照時間(時間)00"];
          - attribute: 日照時間(時間)00
            method: remove

          - attribute: days_less_then_1h_daylight
            method: create
            value:
              env.get("__value")["日照時間0.1時間未満日数(日)"];
          - attribute: 日照時間0.1時間未満日数(日)
            method: remove

          - attribute: days_less_then_1h_daylight_num
            method: create
            value:
              env.get("__value")["日照時間0.1時間未満日数(日)00"];
          - attribute: 日照時間0.1時間未満日数(日)00
            method: remove

          - attribute: days_over_40%_daylight_late
            method: create
            value:
              env.get("__value")["日照率40%以上日数(日)"];
          - attribute: 日照率40%以上日数(日)
            method: remove

          - attribute: days_over_40%_daylight_late_num
            method: create
            value:
              env.get("__value")["日照率40%以上日数(日)00"];
          - attribute: 日照率40%以上日数(日)00
            method: remove

          - attribute: max_daylight_hours
            method: create
            value: |
              310

          - attribute: transmissivity
            method: create
            value: |
              0.75

      # Calculate averages grouped by month and add year attribute
      - id: b26d26ee-ec37-11f0-8e87-7c70db10a7e3
        name: AggregateByMonth
        type: action
        action: AttributeAggregator
        with:
          # Define the grouping attributes (what to group by)
          aggregateAttributes:
            - newAttribute: month
              attribute: month

          # Define multiple calculations to perform on the same grouping
          calculations:
            # Calculate averages directly instead of sums then division
            - calculation: |
                let v = env.get("__value")["daylight_hours"];
                parse_float(v)
              calculationAttribute: daylight_hours
              method: avg

            - calculation: |
                let v = env.get("__value")["daylight_hours_num"];
                parse_float(v)
              calculationAttribute: daylight_hours_num
              method: avg

            - calculation: |
                env.get("__value")["transmissivity"]
              calculationAttribute: transmissivity
              method: avg

            # Add the year attribute with value 9999
            - calculation: |
                9999
              calculationAttribute: year
              method: max  # Any method works for a constant value

      - id: 4624d686-ec5e-11f0-a279-7c70db10a7e3
        name: TestFilter_2
        type: action
        action: FeatureFilter
        with:
          conditions:
            - expr: |
                env.get("__value")["period"] == "period_year"
              outputPort: yearPort
            - expr: |
                env.get("__value")["period"] == "period_month"
              outputPort: monthPort
            - expr: |
                env.get("__value")["period"] == "period_day"
              outputPort: datePort
            - expr: |
                env.get("__value")["year"] == 9999
              outputPort: year9999Port

      # Aggregator for year, month, date features (using new AttributeAggregator to calculate averages)
      - id: 4624d686-ec5e-11f0-a279-7c70db10a7e4
        name: Aggregator_2
        type: action
        action: AttributeAggregator
        with:
          # Define the grouping attributes (what to group by)
          aggregateAttributes:
            - newAttribute: year
              attribute: year

          # Define multiple calculations to perform on the same grouping
          calculations:
            # Calculate averages directly
            - calculation: |
                let v = env.get("__value")["daylight_hours"];
                parse_float(v)
              calculationAttribute: daylight_hours
              method: avg

            - calculation: |
                let v = env.get("__value")["daylight_hours_num"];
                parse_float(v)
              calculationAttribute: daylight_hours_num
              method: avg

            - calculation: |
                let v = env.get("__value")["transmissivity"];
                parse_float(v)
              calculationAttribute: transmissivity
              method: avg

      # Aggregator for 9999-year features (using new AttributeAggregator to calculate averages)
      - id: 4624d686-ec5e-11f0-a279-7c70db10a7e5
        name: Aggregator_4
        type: action
        action: AttributeAggregator
        with:
          # Define the grouping attributes (what to group by)
          aggregateAttributes:
            - newAttribute: year
              attribute: year

          # Define multiple calculations to perform on the same grouping
          calculations:
            # Calculate averages directly
            - calculation: |
                env.get("__value")["daylight_hours"]
              calculationAttribute: daylight_hours
              method: avg

            - calculation: |
                env.get("__value")["daylight_hours_num"]
              calculationAttribute: daylight_hours_num
              method: avg

            - calculation: |
                env.get("__value")["transmissivity"]
              calculationAttribute: transmissivity
              method: avg

      # ExpressionEvaluator_6 equivalent - calculates sunshine rate
      - id: 4624d686-ec5e-11f0-a279-7c70db10a7e8
        name: ExpressionEvaluator_6
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: sunshine_rate
              method: create
              value: |
                let daylight_hours_value = env.get("__value")["daylight_hours"];
                let max_daylight_hours_value = env.get("__value")["max_daylight_hours"] ?? 0.0;
                if max_daylight_hours_value != 0.0 {
                  daylight_hours_value / max_daylight_hours_value
                } else {
                  0.0
                }

      # ExpressionEvaluator_8 equivalent - calculates cloud rate
      - id: 4624d686-ec5e-11f0-a279-7c70db10a7e9
        name: ExpressionEvaluator_8
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: cloud_rate
              method: create
              value: |
                1.0 - env.get("__value")["sunshine_rate"]

      # ExpressionEvaluator_7 equivalent - creates is_not_9999 flag
      - id: 00557d1e-ec71-11f0-8212-7c70db10a7e3
        name: ExpressionEvaluator_7
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: is_not_9999
              method: create
              value: |
                let year_value = env.get("__value")["year"];
                if year_value != 9999 {
                  1
                } else {
                  0
                }

      # StatisticsCalculator_5 equivalent - performs statistics calculations
      - id: 35a4b566-ec71-11f0-bc8b-7c70db10a7e3
        name: StatisticsCalculator_5
        type: action
        action: StatisticsCalculator
        with:
          groupBy:
            - year
          calculations:
            - newAttribute: sum_is_not_9999
              expr: |
                env.get("__value")["is_not_9999"] ?? 0.0
            - newAttribute: sum_sunshine_rate
              expr: |
                env.get("__value")["sunshine_rate"] ?? 0.0
            - newAttribute: sum_cloud_rate
              expr: |
                env.get("__value")["cloud_rate"] ?? 0.0

      # AttributeCreator_6 equivalent - creates join key
      - id: 78dd336c-ec71-11f0-a5ee-7c70db10a7e3
        name: AttributeCreator_6
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: join_key
              method: create
              value: |
                "key"

      - id: cf028708-eba2-11f0-baa6-7c70db10a7e3
        name: DummyOutput
        type: action
        action: NoopSink

    edges:
      - id: bcdf7d4c-eba2-11f0-995a-7c70db10a7e3
        from: c4ea198e-eba2-11f0-b93c-7c70db10a7e3
        to: 9444dbf6-eba3-11f0-bdcb-7c70db10a7e3
        fromPort: default
        toPort: default

      - id: f113d102-eba3-11f0-ae93-7c70db10a7e3
        from: 9444dbf6-eba3-11f0-bdcb-7c70db10a7e3
        to: b26d26ee-ec37-11f0-8e87-7c70db10a7e3
        fromPort: default
        toPort: default

      # Connect the new AttributeAggregator directly to TestFilter_2
      - id: 4353493c-ec5a-11f0-8f0d-7c70db10a7e3
        from: b26d26ee-ec37-11f0-8e87-7c70db10a7e3
        to: 4624d686-ec5e-11f0-a279-7c70db10a7e3
        fromPort: default
        toPort: default

      # edge connect PrepareAttribute to TestFilter_2 (backup connection)
      - id: 26b3234c-ec5f-11f0-9544-7c70db10a7e3
        from: 9444dbf6-eba3-11f0-bdcb-7c70db10a7e3
        to: 4624d686-ec5e-11f0-a279-7c70db10a7e3
        fromPort: default
        toPort: default

      # Connect TestFilter_2 outputs to different aggregators
      - id: 3794a212-ec5a-11f0-9030-7c70db10a7e4
        from: 4624d686-ec5e-11f0-a279-7c70db10a7e3
        to: 4624d686-ec5e-11f0-a279-7c70db10a7e4
        fromPort: yearPort
        toPort: default

      - id: 3794a212-ec5a-11f0-9030-7c70db10a7e5
        from: 4624d686-ec5e-11f0-a279-7c70db10a7e3
        to: 4624d686-ec5e-11f0-a279-7c70db10a7e5
        fromPort: year9999Port
        toPort: default

      # Connect Aggregator_2 directly to ExpressionEvaluator_6 (since it now calculates averages directly)
      - id: 3794a212-ec5a-11f0-9030-7c70db10a7e6
        from: 4624d686-ec5e-11f0-a279-7c70db10a7e4
        to: 4624d686-ec5e-11f0-a279-7c70db10a7e8
        fromPort: default
        toPort: default

      # Connect Aggregator_4 directly to ExpressionEvaluator_6 (since it now calculates averages directly)
      - id: 3794a212-ec5a-11f0-9030-7c70db10a7e7
        from: 4624d686-ec5e-11f0-a279-7c70db10a7e5
        to: 4624d686-ec5e-11f0-a279-7c70db10a7e8
        fromPort: default
        toPort: default

      # Connect ExpressionEvaluator_6 to ExpressionEvaluator_8
      - id: e76300b0-ec70-11f0-8c1a-7c70db10a7e3
        from: 4624d686-ec5e-11f0-a279-7c70db10a7e8
        to: 4624d686-ec5e-11f0-a279-7c70db10a7e9
        fromPort: default
        toPort: default

      # Connect ExpressionEvaluator_8 to ExpressionEvaluator_7
      - id: f05a8bfc-ec70-11f0-870f-7c70db10a7e3
        from: 4624d686-ec5e-11f0-a279-7c70db10a7e9
        to: 00557d1e-ec71-11f0-8212-7c70db10a7e3
        fromPort: default
        toPort: default

      # Connect ExpressionEvaluator_7 to StatisticsCalculator_5
      - id: 2b2b8e02-ec71-11f0-8282-7c70db10a7e3
        from: 00557d1e-ec71-11f0-8212-7c70db10a7e3
        to: 35a4b566-ec71-11f0-bc8b-7c70db10a7e3
        fromPort: default
        toPort: default

      # Connect StatisticsCalculator_5 to AttributeCreator_6
      - id: 4c8c746c-ec71-11f0-9a9a-7c70db10a7e3
        from: 35a4b566-ec71-11f0-bc8b-7c70db10a7e3
        to: 78dd336c-ec71-11f0-a5ee-7c70db10a7e3
        fromPort: default
        toPort: default

      # Connect AttributeCreator_6 to final output
      - id: 3794a212-ec5a-11f0-9030-7c70db10a7e9
        from: 78dd336c-ec71-11f0-a5ee-7c70db10a7e3
        to: cf028708-eba2-11f0-baa6-7c70db10a7e3
        fromPort: default
        toPort: default

