# workflow for calculate snow correction for solar energy

id: 2d4e1c6a-eb70-11f0-9b6c-7c70db10a7e3
name: CalculateCloudCorrectionFactor
entryGraphId: a2df1dee-eba2-11f0-b126-7c70db10a7e3
with:
  csvFile: !include ./input.csv
graphs:
  - id: a2df1dee-eba2-11f0-b126-7c70db10a7e3
    name: CloudFactorWorkflow
    nodes:
      - id: c4ea198e-eba2-11f0-b93c-7c70db10a7e3
        name: CsvReader
        type: action
        action: CsvReader
        with:
          format: csv
          inline: |
            env.get("csvFile")
    
      - id: cf028708-eba2-11f0-baa6-7c70db10a7e3
        name: DummyOutput
        type: action
        action: NoopSink

    edges:
      - id: bcdf7d4c-eba2-11f0-995a-7c70db10a7e3
        from: c4ea198e-eba2-11f0-b93c-7c70db10a7e3
        to: cf028708-eba2-11f0-baa6-7c70db10a7e3
        fromPort: default
        toPort: default

