# workflow for calculate snow correction for solar energy
id: 2d4e1c6a-eb70-11f0-9b6c-7c70db10a7e3
name: CalculateCloudCorrectionFactor
entryGraphId: a2df1dee-eba2-11f0-b126-7c70db10a7e3
with:
  csvFile: !include ./input.csv
graphs:
  - id: a2df1dee-eba2-11f0-b126-7c70db10a7e3
    name: CloudFactorWorkflow
    nodes:
      - id: c4ea198e-eba2-11f0-b93c-7c70db10a7e3
        name: CsvReader
        type: action
        action: CsvReader
        with:
          format: csv
          inline: |
            env.get("csvFile")

      - id: 9444dbf6-eba3-11f0-bdcb-7c70db10a7e3
        name: PrepareAttribute
        type: action
        action: AttributeManager
        with:
          operations:
          - attribute: year
            method: create
            value:
              env.get("__value")["年"];
          - attribute: 年
            method: remove

          - attribute: month
            method: create
            value:
              env.get("__value")["月"];
          - attribute: 月
            method: remove

          - attribute: daylight_hours
            method: create
            value:
              env.get("__value")["日照時間(時間)"];
          - attribute: 日照時間(時間)
            method: remove

          - attribute: daylight_hours_num
            method: create
            value:
              env.get("__value")["日照時間(時間)00"];
          - attribute: 日照時間(時間)00
            method: remove

          - attribute: days_less_then_1h_daylight
            method: create
            value:
              env.get("__value")["日照時間0.1時間未満日数(日)"];
          - attribute: 日照時間0.1時間未満日数(日)
            method: remove

          - attribute: days_less_then_1h_daylight_num
            method: create
            value:
              env.get("__value")["日照時間0.1時間未満日数(日)00"];
          - attribute: 日照時間0.1時間未満日数(日)00
            method: remove

          - attribute: days_over_40%_daylight_late
            method: create
            value:
              env.get("__value")["日照率40%以上日数(日)"];
          - attribute: 日照率40%以上日数(日)
            method: remove

          - attribute: days_over_40%_daylight_late_num
            method: create
            value:
              env.get("__value")["日照率40%以上日数(日)00"];
          - attribute: 日照率40%以上日数(日)00
            method: remove

          - attribute: max_daylight_hours
            method: create
            value: |
              310

          - attribute: transmissivity
            method: create
            value: |
              0.75

      # 1) Group features by the month attribute
      # 2) Calculate sums for all the required attributes: daylight_hours, daylight_hours_num, days_less_then_1h_daylight, etc.
      # 3) Also calculates a count by using an expression that always evaluates to 1
      - id: b26d26ee-ec37-11f0-8e87-7c70db10a7e3
        name: AggregateByMonth
        type: action
        action: StatisticsCalculator
        with:
          groupBy:
            - month
          calculations:

            - newAttribute: sum_daylight_hours
              expr: |
                let v = env.get("__value")["daylight_hours"];
                parse_float(v)
            - newAttribute: sum_daylight_hours_num
              expr: |
                let v = env.get("__value")["daylight_hours_num"];
                parse_float(v)
            - newAttribute: count
              expr: |
                1
            - newAttribute: sum_transmissivity
              expr: |
                env.get("__value")["transmissivity"]

      # 1) Divide each sum by the count to get the average value for each attribute
      # 2) Create new attributes with the averaged values (prefixed with avg_)
      # 3) Remove the temporary sum and count attributes to clean up
      - id: 4c0b32ba-ec5a-11f0-9a05-7c70db10a7e3
        name: CalculateAverages
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: avg_daylight_hours
              method: create
              value: |
                env.get("__value")["sum_daylight_hours"] / env.get("__value")["count"]
            - attribute: avg_daylight_hours_num
              method: create
              value: |
                env.get("__value")["sum_daylight_hours_num"] / env.get("__value")["count"]
            - attribute: avg_transmissivity
              method: create
              value: |
                env.get("__value")["sum_transmissivity"] / env.get("__value")["count"]
            - attribute: sum_daylight_hours
              method: remove
            - attribute: sum_daylight_hours_num
              method: remove
            - attribute: sum_transmissivity
              method: remove
            - attribute: count
              method: remove
            - attribute: year
              method: create
              value: |
                9999

      - id: 4624d686-ec5e-11f0-a279-7c70db10a7e3
        name: TestFilter_2
        type: action
        action: FeatureFilter
        with:
          conditions:
            - expr: |
                env.get("__value")["period"] == "period_year"
              outputPort: yearPort
            - expr: |
                env.get("__value")["period"] == "period_month"
              outputPort: monthPort
            - expr: |
                env.get("__value")["period"] == "period_day"
              outputPort: datePort
            - expr: |
                env.get("__value")["year"] == 9999
              outputPort: year9999Port

      # Aggregator for year, month, date features (corresponds to Aggregator_2 in FME)
      - id: 4624d686-ec5e-11f0-a279-7c70db10a7e4
        name: Aggregator_2
        type: action
        action: StatisticsCalculator
        with:
          groupBy:
            - year
          calculations:
            - newAttribute: sum_daylight_hours
              expr: |
                let v = env.get("__value")["avg_daylight_hours"];
                parse_float(v)
            - newAttribute: sum_daylight_hours_num
              expr: |
                let v = env.get("__value")["avg_daylight_hours_num"];
                parse_float(v)
            # - newAttribute: sum_days_less_then_1h_daylight
            #   expr: |
            #     let v = env.get("__value")["avg_days_less_then_1h_daylight"];
            #     parse_float(v)
            # - newAttribute: sum_days_less_then_1h_daylight_num
            #   expr: |
            #     let v = env.get("__value")["avg_days_less_then_1h_daylight_num"];
            #     parse_float(v)
            # - newAttribute: sum_days_over_40%_daylight_late
            #   expr: |
            #     let v = env.get("__value")["avg_days_over_40%_daylight_late"];
            #     parse_float(v)
            # - newAttribute: sum_days_over_40%_daylight_late_num
            #   expr: |
            #     let v = env.get("__value")["avg_days_over_40%_daylight_late_num"];
            #     parse_float(v)
            # - newAttribute: sum_max_daylight_hours
            #   expr: |
            #     let v = env.get("__value")["avg_max_daylight_hours"];
            #     parse_float(v)
            - newAttribute: sum_transmissivity
              expr: |
                let v = env.get("__value")["avg_transmissivity"];
                parse_float(v)
            - newAttribute: count
              expr: |
                1

      # Calculate averages for Aggregator_2 results
      - id: 4624d686-ec5e-11f0-a279-7c70db10a7e6
        name: CalculateAverages_Aggregator_2
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: avg_daylight_hours
              method: create
              value: |
                env.get("__value")["sum_daylight_hours"] / env.get("__value")["count"]
            - attribute: avg_daylight_hours_num
              method: create
              value: |
                env.get("__value")["sum_daylight_hours_num"] / env.get("__value")["count"]
            # - attribute: avg_days_less_then_1h_daylight
            #   method: create
            #   value: |
            #     env.get("__value")["sum_days_less_then_1h_daylight"] / env.get("__value")["count"]
            # - attribute: avg_days_less_then_1h_daylight_num
            #   method: create
            #   value: |
            #     env.get("__value")["sum_days_less_then_1h_daylight_num"] / env.get("__value")["count"]
            # - attribute: avg_days_over_40%_daylight_late
            #   method: create
            #   value: |
            #     env.get("__value")["sum_days_over_40%_daylight_late"] / env.get("__value")["count"]
            # - attribute: avg_days_over_40%_daylight_late_num
            #   method: create
            #   value: |
            #     env.get("__value")["sum_days_over_40%_daylight_late_num"] / env.get("__value")["count"]
            # - attribute: avg_max_daylight_hours
            #   method: create
            #   value: |
            #     env.get("__value")["sum_max_daylight_hours"] / env.get("__value")["count"]
            - attribute: avg_transmissivity
              method: create
              value: |
                env.get("__value")["sum_transmissivity"] / env.get("__value")["count"]
            - attribute: sum_daylight_hours
              method: remove
            - attribute: sum_daylight_hours_num
              method: remove
            # - attribute: sum_days_less_then_1h_daylight
            #   method: remove
            # - attribute: sum_days_less_then_1h_daylight_num
            #   method: remove
            # - attribute: sum_days_over_40%_daylight_late
            #   method: remove
            # - attribute: sum_days_over_40%_daylight_late_num
            #   method: remove
            # - attribute: sum_max_daylight_hours
            #   method: remove
            - attribute: sum_transmissivity
              method: remove
            - attribute: count
              method: remove

      # Aggregator for 9999-year features (corresponds to Aggregator_4 in FME)
      - id: 4624d686-ec5e-11f0-a279-7c70db10a7e5
        name: Aggregator_4
        type: action
        action: StatisticsCalculator
        with:
          groupBy:
            - year
          calculations:
            - newAttribute: sum_daylight_hours
              expr: |
                env.get("__value")["avg_daylight_hours"]
            - newAttribute: sum_daylight_hours_num
              expr: |
                env.get("__value")["avg_daylight_hours_num"]
            # - newAttribute: sum_days_less_then_1h_daylight
            #   expr: |
            #     let v = env.get("__value")["avg_days_less_then_1h_daylight"];
            #     parse_float(v)
            # - newAttribute: sum_days_less_then_1h_daylight_num
            #   expr: |
            #     let v = env.get("__value")["avg_days_less_then_1h_daylight_num"];
            #     parse_float(v)
            # - newAttribute: sum_days_over_40%_daylight_late
            #   expr: |
            #     let v = env.get("__value")["avg_days_over_40%_daylight_late"];
            #     parse_float(v)
            # - newAttribute: sum_days_over_40%_daylight_late_num
            #   expr: |
            #     let v = env.get("__value")["avg_days_over_40%_daylight_late_num"];
            #     parse_float(v)
            # - newAttribute: sum_max_daylight_hours
            #   expr: |
            #     let v = env.get("__value")["avg_max_daylight_hours"];
            #     parse_float(v)
            - newAttribute: sum_transmissivity
              expr: |
                env.get("__value")["avg_transmissivity"]
            - newAttribute: count
              expr: |
                1

      # Calculate averages for Aggregator_4 results
      - id: 4624d686-ec5e-11f0-a279-7c70db10a7e7
        name: CalculateAverages_Aggregator_4
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: avg_daylight_hours
              method: create
              value: |
                env.get("__value")["sum_daylight_hours"] / env.get("__value")["count"]
            - attribute: avg_daylight_hours_num
              method: create
              value: |
                env.get("__value")["sum_daylight_hours_num"] / env.get("__value")["count"]
            # - attribute: avg_days_less_then_1h_daylight
            #   method: create
            #   value: |
            #     env.get("__value")["sum_days_less_then_1h_daylight"] / env.get("__value")["count"]
            # - attribute: avg_days_less_then_1h_daylight_num
            #   method: create
            #   value: |
            #     env.get("__value")["sum_days_less_then_1h_daylight_num"] / env.get("__value")["count"]
            # - attribute: avg_days_over_40%_daylight_late
            #   method: create
            #   value: |
            #     env.get("__value")["sum_days_over_40%_daylight_late"] / env.get("__value")["count"]
            # - attribute: avg_days_over_40%_daylight_late_num
            #   method: create
            #   value: |
            #     env.get("__value")["sum_days_over_40%_daylight_late_num"] / env.get("__value")["count"]
            # - attribute: avg_max_daylight_hours
            #   method: create
            #   value: |
            #     env.get("__value")["sum_max_daylight_hours"] / env.get("__value")["count"]
            - attribute: avg_transmissivity
              method: create
              value: |
                env.get("__value")["sum_transmissivity"] / env.get("__value")["count"]
            - attribute: sum_daylight_hours
              method: remove
            - attribute: sum_daylight_hours_num
              method: remove
            # - attribute: sum_days_less_then_1h_daylight
            #   method: remove
            # - attribute: sum_days_less_then_1h_daylight_num
            #   method: remove
            # - attribute: sum_days_over_40%_daylight_late
            #   method: remove
            # - attribute: sum_days_over_40%_daylight_late_num
            #   method: remove
            # - attribute: sum_max_daylight_hours
            #   method: remove
            - attribute: sum_transmissivity
              method: remove
            - attribute: count
              method: remove

      # ExpressionEvaluator_6 equivalent - combines results
      - id: 4624d686-ec5e-11f0-a279-7c70db10a7e8
        name: ExpressionEvaluator_6
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: combined_result
              method: create
              value: |
                env.get("__value")["avg_daylight_hours"]

      - id: cf028708-eba2-11f0-baa6-7c70db10a7e3
        name: DummyOutput
        type: action
        action: NoopSink

    edges:
      - id: bcdf7d4c-eba2-11f0-995a-7c70db10a7e3
        from: c4ea198e-eba2-11f0-b93c-7c70db10a7e3
        to: 9444dbf6-eba3-11f0-bdcb-7c70db10a7e3
        fromPort: default
        toPort: default

      - id: f113d102-eba3-11f0-ae93-7c70db10a7e3
        from: 9444dbf6-eba3-11f0-bdcb-7c70db10a7e3
        to: b26d26ee-ec37-11f0-8e87-7c70db10a7e3
        fromPort: default
        toPort: default

      - id: 4353493c-ec5a-11f0-8f0d-7c70db10a7e3
        from: b26d26ee-ec37-11f0-8e87-7c70db10a7e3
        to: 4c0b32ba-ec5a-11f0-9a05-7c70db10a7e3
        fromPort: default
        toPort: default

      # edge connect CalculateAverages to TestFilter_2
      - id: 3794a212-ec5a-11f0-9030-7c70db10a7e3
        from: 4c0b32ba-ec5a-11f0-9a05-7c70db10a7e3
        to: 4624d686-ec5e-11f0-a279-7c70db10a7e3
        fromPort: default
        toPort: default

      # edge connect PrepareAttribute to TestFilter_2
      - id: 26b3234c-ec5f-11f0-9544-7c70db10a7e3
        from: 9444dbf6-eba3-11f0-bdcb-7c70db10a7e3
        to: 4624d686-ec5e-11f0-a279-7c70db10a7e3
        fromPort: default
        toPort: default

      # Connect TestFilter_2 outputs to different aggregators
      - id: 3794a212-ec5a-11f0-9030-7c70db10a7e4
        from: 4624d686-ec5e-11f0-a279-7c70db10a7e3
        to: 4624d686-ec5e-11f0-a279-7c70db10a7e4
        fromPort: yearPort
        toPort: default

      - id: 3794a212-ec5a-11f0-9030-7c70db10a7e5
        from: 4624d686-ec5e-11f0-a279-7c70db10a7e3
        to: 4624d686-ec5e-11f0-a279-7c70db10a7e5
        fromPort: year9999Port
        toPort: default

      # Connect Aggregator_2 to its average calculator
      - id: 3794a212-ec5a-11f0-9030-7c70db10a7e6
        from: 4624d686-ec5e-11f0-a279-7c70db10a7e4
        to: 4624d686-ec5e-11f0-a279-7c70db10a7e6
        fromPort: default
        toPort: default

      # Connect Aggregator_4 to its average calculator
      - id: 3794a212-ec5a-11f0-9030-7c70db10a7e7
        from: 4624d686-ec5e-11f0-a279-7c70db10a7e5
        to: 4624d686-ec5e-11f0-a279-7c70db10a7e7
        fromPort: default
        toPort: default

      # Connect average calculators to ExpressionEvaluator_6
      - id: 3794a212-ec5a-11f0-9030-7c70db10a7e8
        from: 4624d686-ec5e-11f0-a279-7c70db10a7e6
        to: 4624d686-ec5e-11f0-a279-7c70db10a7e8
        fromPort: default
        toPort: default

      # Connect to final output
      - id: 3794a212-ec5a-11f0-9030-7c70db10a7e9
        from: 4624d686-ec5e-11f0-a279-7c70db10a7e8
        to: cf028708-eba2-11f0-baa6-7c70db10a7e3
        fromPort: default
        toPort: default

