# workflow for calculate snow correction for solar energy

id: 2d4e1c6a-eb70-11f0-9b6c-7c70db10a7e3
name: CalculateCloudCorrectionFactor
entryGraphId: a2df1dee-eba2-11f0-b126-7c70db10a7e3
with:
  csvFile: !include ./input.csv
graphs:
  - id: a2df1dee-eba2-11f0-b126-7c70db10a7e3
    name: CloudFactorWorkflow
    nodes:
      - id: c4ea198e-eba2-11f0-b93c-7c70db10a7e3
        name: CsvReader
        type: action
        action: CsvReader
        with:
          format: csv
          inline: |
            env.get("csvFile")
      
      - id: 9444dbf6-eba3-11f0-bdcb-7c70db10a7e3
        name: PrepareAttribute
        type: action 
        action: AttributeManager 
        with:
          operations:
          - attribute: year 
            method: create 
            value: 
              env.get("__value")["年"];          
          - attribute: 年
            method: remove
          
          - attribute: month 
            method: create 
            value: 
              env.get("__value")["月"];
          - attribute: 月
            method: remove 

          - attribute: daylight_hours 
            method: create 
            value: 
              env.get("__value")["日照時間(時間)"];
          - attribute: 日照時間(時間)
            method: remove      

          - attribute: daylight_hours_num 
            method: create 
            value: 
              env.get("__value")["日照時間(時間)00"];
          - attribute: 日照時間(時間)00
            method: remove         

          - attribute: days_less_then_1h_daylight 
            method: create 
            value: 
              env.get("__value")["日照時間0.1時間未満日数(日)"];
          - attribute: 日照時間0.1時間未満日数(日)
            method: remove      

          - attribute: days_less_then_1h_daylight_num 
            method: create 
            value: 
              env.get("__value")["日照時間0.1時間未満日数(日)00"];
          - attribute: 日照時間0.1時間未満日数(日)00
            method: remove   

          - attribute: days_over_40%_daylight_late 
            method: create 
            value: 
              env.get("__value")["日照率40%以上日数(日)"];
          - attribute: 日照率40%以上日数(日)
            method: remove      

          - attribute: days_over_40%_daylight_late_num 
            method: create 
            value: 
              env.get("__value")["日照率40%以上日数(日)00"];
          - attribute: 日照率40%以上日数(日)00
            method: remove   

          - attribute: max_daylight_hours
            method: create 
            value: | 
              310 

          - attribute: transmissivity
            method: create 
            value: |
              0.75        

      - id: b26d26ee-ec37-11f0-8e87-7c70db10a7e3
        name: AverageOnMonth
        # daylight_hours daylight_hours_num days_less_then_1h_daylight days_less_then_1h_daylight_num days_over_40%_daylight_late days_over_40%_daylight_late_num max_daylight_hours transmissivity
        type: action 
        action: AttributeAggregator
        with: 
          aggregateAttributes:
          - newAttribute: daylight_hours
            attribute: daylight_hours
          - newAttribute: daylight_hours_num
            attribute: daylight_hours_num
          - newAttribute: days_less_then_1h_daylight
            attribute: days_less_then_1h_daylight
          - newAttribute: days_less_then_1h_daylight_num
            attribute: days_less_then_1h_daylight_num
          - newAttribute: days_over_40%_daylight_late
            attribute: days_over_40%_daylight_late
          - newAttribute: days_over_40%_daylight_late_num
            attribute: days_over_40%_daylight_late_num
          - newAttribute: max_daylight_hours
            attribute: max_daylight_hours
          - newAttribute: transmissivity
            attribute: transmissivity 
          calculationAttribute: month 
          method: average                            
 
      - id: cf028708-eba2-11f0-baa6-7c70db10a7e3
        name: DummyOutput
        type: action
        action: NoopSink

    edges:
      - id: bcdf7d4c-eba2-11f0-995a-7c70db10a7e3
        from: c4ea198e-eba2-11f0-b93c-7c70db10a7e3
        to: 9444dbf6-eba3-11f0-bdcb-7c70db10a7e3
        fromPort: default
        toPort: default

      - id: f113d102-eba3-11f0-ae93-7c70db10a7e3
        from: 9444dbf6-eba3-11f0-bdcb-7c70db10a7e3
        to: b26d26ee-ec37-11f0-8e87-7c70db10a7e3
        fromPort: default 
        toPort: default

      - id: f113d102-eba3-11f0-ae93-7c70db10a7e3
        from: b26d26ee-ec37-11f0-8e87-7c70db10a7e3
        to: cf028708-eba2-11f0-baa6-7c70db10a7e3
        fromPort: default 
        toPort: default

