services:
  reearth-flow-api:
    image: reearth/reearth-flow:latest
    build:
      context: ../../
      dockerfile: server/api/Dockerfile
    environment:
      REEARTH_FLOW_DB: mongodb://reearth-flow-mongo
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - reearth-flow-mongo
    volumes:
      - ./data:/app/data

  reearth-flow-mongo:
    image: mongo:7-jammy
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db

  reearth-flow-postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: reearth
      POSTGRES_PASSWORD: reearth
      POSTGRES_DB: reearth-flow
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
