// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/cms/proto/schema.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Visibility int32

const (
	Visibility_PUBLIC  Visibility = 0
	Visibility_PRIVATE Visibility = 1
)

// Enum value maps for Visibility.
var (
	Visibility_name = map[int32]string{
		0: "PUBLIC",
		1: "PRIVATE",
	}
	Visibility_value = map[string]int32{
		"PUBLIC":  0,
		"PRIVATE": 1,
	}
)

func (x Visibility) Enum() *Visibility {
	p := new(Visibility)
	*p = x
	return p
}

func (x Visibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Visibility) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_cms_proto_schema_proto_enumTypes[0].Descriptor()
}

func (Visibility) Type() protoreflect.EnumType {
	return &file_pkg_cms_proto_schema_proto_enumTypes[0]
}

func (x Visibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Visibility.Descriptor instead.
func (Visibility) EnumDescriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{0}
}

type SchemaFieldType int32

const (
	SchemaFieldType_Text           SchemaFieldType = 0
	SchemaFieldType_TextArea       SchemaFieldType = 1
	SchemaFieldType_RichText       SchemaFieldType = 2
	SchemaFieldType_MarkdownText   SchemaFieldType = 3
	SchemaFieldType_Asset          SchemaFieldType = 4
	SchemaFieldType_Date           SchemaFieldType = 5
	SchemaFieldType_Bool           SchemaFieldType = 6
	SchemaFieldType_Select         SchemaFieldType = 7
	SchemaFieldType_Tag            SchemaFieldType = 8
	SchemaFieldType_Integer        SchemaFieldType = 9
	SchemaFieldType_Number         SchemaFieldType = 10
	SchemaFieldType_Reference      SchemaFieldType = 11
	SchemaFieldType_Checkbox       SchemaFieldType = 12
	SchemaFieldType_URL            SchemaFieldType = 13
	SchemaFieldType_Group          SchemaFieldType = 14
	SchemaFieldType_GeometryObject SchemaFieldType = 15
	SchemaFieldType_GeometryEditor SchemaFieldType = 16
)

// Enum value maps for SchemaFieldType.
var (
	SchemaFieldType_name = map[int32]string{
		0:  "Text",
		1:  "TextArea",
		2:  "RichText",
		3:  "MarkdownText",
		4:  "Asset",
		5:  "Date",
		6:  "Bool",
		7:  "Select",
		8:  "Tag",
		9:  "Integer",
		10: "Number",
		11: "Reference",
		12: "Checkbox",
		13: "URL",
		14: "Group",
		15: "GeometryObject",
		16: "GeometryEditor",
	}
	SchemaFieldType_value = map[string]int32{
		"Text":           0,
		"TextArea":       1,
		"RichText":       2,
		"MarkdownText":   3,
		"Asset":          4,
		"Date":           5,
		"Bool":           6,
		"Select":         7,
		"Tag":            8,
		"Integer":        9,
		"Number":         10,
		"Reference":      11,
		"Checkbox":       12,
		"URL":            13,
		"Group":          14,
		"GeometryObject": 15,
		"GeometryEditor": 16,
	}
)

func (x SchemaFieldType) Enum() *SchemaFieldType {
	p := new(SchemaFieldType)
	*p = x
	return p
}

func (x SchemaFieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchemaFieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_cms_proto_schema_proto_enumTypes[1].Descriptor()
}

func (SchemaFieldType) Type() protoreflect.EnumType {
	return &file_pkg_cms_proto_schema_proto_enumTypes[1]
}

func (x SchemaFieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchemaFieldType.Descriptor instead.
func (SchemaFieldType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{1}
}

// Core messages
type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	License       *string                `protobuf:"bytes,5,opt,name=license,proto3,oneof" json:"license,omitempty"`
	Readme        *string                `protobuf:"bytes,6,opt,name=readme,proto3,oneof" json:"readme,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,7,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Visibility    Visibility             `protobuf:"varint,8,opt,name=visibility,proto3,enum=reearth.cms.v1.Visibility" json:"visibility,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Project) GetLicense() string {
	if x != nil && x.License != nil {
		return *x.License
	}
	return ""
}

func (x *Project) GetReadme() string {
	if x != nil && x.Readme != nil {
		return *x.Readme
	}
	return ""
}

func (x *Project) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Project) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_PUBLIC
}

func (x *Project) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Project) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Key           string                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Schema        *Schema                `protobuf:"bytes,6,opt,name=schema,proto3" json:"schema,omitempty"`
	PublicApiEp   string                 `protobuf:"bytes,7,opt,name=public_api_ep,json=publicApiEp,proto3" json:"public_api_ep,omitempty"`
	EditorUrl     string                 `protobuf:"bytes,8,opt,name=editor_url,json=editorUrl,proto3" json:"editor_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{1}
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Model) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Model) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Model) GetPublicApiEp() string {
	if x != nil {
		return x.PublicApiEp
	}
	return ""
}

func (x *Model) GetEditorUrl() string {
	if x != nil {
		return x.EditorUrl
	}
	return ""
}

func (x *Model) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Model) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields        map[string]*anypb.Any  `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetFields() map[string]*anypb.Any {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Item) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Item) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Schema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaId      string                 `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	Fields        []*SchemaField         `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{3}
}

func (x *Schema) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *Schema) GetFields() []*SchemaField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type SchemaField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldId       string                 `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          SchemaFieldType        `protobuf:"varint,3,opt,name=type,proto3,enum=reearth.cms.v1.SchemaFieldType" json:"type,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaField) Reset() {
	*x = SchemaField{}
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaField) ProtoMessage() {}

func (x *SchemaField) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaField.ProtoReflect.Descriptor instead.
func (*SchemaField) Descriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{4}
}

func (x *SchemaField) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *SchemaField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemaField) GetType() SchemaFieldType {
	if x != nil {
		return x.Type
	}
	return SchemaFieldType_Text
}

func (x *SchemaField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SchemaField) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// Request messages
type ProjectRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProjectIdOrAlias string                 `protobuf:"bytes,1,opt,name=project_id_or_alias,json=projectIdOrAlias,proto3" json:"project_id_or_alias,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProjectRequest) Reset() {
	*x = ProjectRequest{}
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRequest) ProtoMessage() {}

func (x *ProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRequest.ProtoReflect.Descriptor instead.
func (*ProjectRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{5}
}

func (x *ProjectRequest) GetProjectIdOrAlias() string {
	if x != nil {
		return x.ProjectIdOrAlias
	}
	return ""
}

type AliasAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliasAvailabilityRequest) Reset() {
	*x = AliasAvailabilityRequest{}
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliasAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliasAvailabilityRequest) ProtoMessage() {}

func (x *AliasAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliasAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*AliasAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{6}
}

func (x *AliasAvailabilityRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	License       *string                `protobuf:"bytes,4,opt,name=license,proto3,oneof" json:"license,omitempty"`
	Readme        *string                `protobuf:"bytes,5,opt,name=readme,proto3,oneof" json:"readme,omitempty"`
	Alias         string                 `protobuf:"bytes,6,opt,name=alias,proto3" json:"alias,omitempty"`
	Visibility    Visibility             `protobuf:"varint,7,opt,name=visibility,proto3,enum=reearth.cms.v1.Visibility" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{7}
}

func (x *CreateProjectRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateProjectRequest) GetLicense() string {
	if x != nil && x.License != nil {
		return *x.License
	}
	return ""
}

func (x *CreateProjectRequest) GetReadme() string {
	if x != nil && x.Readme != nil {
		return *x.Readme
	}
	return ""
}

func (x *CreateProjectRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *CreateProjectRequest) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_PUBLIC
}

type UpdateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	License       *string                `protobuf:"bytes,4,opt,name=license,proto3,oneof" json:"license,omitempty"`
	Readme        *string                `protobuf:"bytes,5,opt,name=readme,proto3,oneof" json:"readme,omitempty"`
	Alias         *string                `protobuf:"bytes,6,opt,name=alias,proto3,oneof" json:"alias,omitempty"`
	Visibility    *Visibility            `protobuf:"varint,7,opt,name=visibility,proto3,enum=reearth.cms.v1.Visibility,oneof" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateProjectRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateProjectRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateProjectRequest) GetLicense() string {
	if x != nil && x.License != nil {
		return *x.License
	}
	return ""
}

func (x *UpdateProjectRequest) GetReadme() string {
	if x != nil && x.Readme != nil {
		return *x.Readme
	}
	return ""
}

func (x *UpdateProjectRequest) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

func (x *UpdateProjectRequest) GetVisibility() Visibility {
	if x != nil && x.Visibility != nil {
		return *x.Visibility
	}
	return Visibility_PUBLIC
}

type DeleteProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	PublicOnly    bool                   `protobuf:"varint,2,opt,name=public_only,json=publicOnly,proto3" json:"public_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{10}
}

func (x *ListProjectsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListProjectsRequest) GetPublicOnly() bool {
	if x != nil {
		return x.PublicOnly
	}
	return false
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{11}
}

func (x *ListModelsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Page          *int32                 `protobuf:"varint,3,opt,name=page,proto3,oneof" json:"page,omitempty"`
	PageSize      *int32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{12}
}

func (x *ListItemsRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ListItemsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListItemsRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListItemsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

type ExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{13}
}

func (x *ExportRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ExportRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

// Response messages
type ProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectResponse) Reset() {
	*x = ProjectResponse{}
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectResponse) ProtoMessage() {}

func (x *ProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectResponse.ProtoReflect.Descriptor instead.
func (*ProjectResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{14}
}

func (x *ProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type AliasAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliasAvailabilityResponse) Reset() {
	*x = AliasAvailabilityResponse{}
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliasAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliasAvailabilityResponse) ProtoMessage() {}

func (x *AliasAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliasAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*AliasAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{15}
}

func (x *AliasAvailabilityResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type DeleteProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectResponse) Reset() {
	*x = DeleteProjectResponse{}
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectResponse) ProtoMessage() {}

func (x *DeleteProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteProjectResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteProjectResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{17}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ListProjectsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{18}
}

func (x *ListModelsResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ListModelsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{19}
}

func (x *ListItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListItemsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ExportURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportURLResponse) Reset() {
	*x = ExportURLResponse{}
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportURLResponse) ProtoMessage() {}

func (x *ExportURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cms_proto_schema_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportURLResponse.ProtoReflect.Descriptor instead.
func (*ExportURLResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cms_proto_schema_proto_rawDescGZIP(), []int{20}
}

func (x *ExportURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_pkg_cms_proto_schema_proto protoreflect.FileDescriptor

const file_pkg_cms_proto_schema_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/cms/proto/schema.proto\x12\x0ereearth.cms.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\xa2\x03\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\alicense\x18\x05 \x01(\tH\x01R\alicense\x88\x01\x01\x12\x1b\n" +
	"\x06readme\x18\x06 \x01(\tH\x02R\x06readme\x88\x01\x01\x12!\n" +
	"\fworkspace_id\x18\a \x01(\tR\vworkspaceId\x12:\n" +
	"\n" +
	"visibility\x18\b \x01(\x0e2\x1a.reearth.cms.v1.VisibilityR\n" +
	"visibility\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_licenseB\t\n" +
	"\a_readme\"\xe7\x02\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x10\n" +
	"\x03key\x18\x05 \x01(\tR\x03key\x12.\n" +
	"\x06schema\x18\x06 \x01(\v2\x16.reearth.cms.v1.SchemaR\x06schema\x12\"\n" +
	"\rpublic_api_ep\x18\a \x01(\tR\vpublicApiEp\x12\x1d\n" +
	"\n" +
	"editor_url\x18\b \x01(\tR\teditorUrl\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x97\x02\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\x06fields\x18\x02 \x03(\v2 .reearth.cms.v1.Item.FieldsEntryR\x06fields\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1aO\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"Z\n" +
	"\x06Schema\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\tR\bschemaId\x123\n" +
	"\x06fields\x18\x02 \x03(\v2\x1b.reearth.cms.v1.SchemaFieldR\x06fields\"\xba\x01\n" +
	"\vSchemaField\x12\x19\n" +
	"\bfield_id\x18\x01 \x01(\tR\afieldId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x123\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1f.reearth.cms.v1.SchemaFieldTypeR\x04type\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"?\n" +
	"\x0eProjectRequest\x12-\n" +
	"\x13project_id_or_alias\x18\x01 \x01(\tR\x10projectIdOrAlias\"0\n" +
	"\x18AliasAvailabilityRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"\xa9\x02\n" +
	"\x14CreateProjectRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\alicense\x18\x04 \x01(\tH\x01R\alicense\x88\x01\x01\x12\x1b\n" +
	"\x06readme\x18\x05 \x01(\tH\x02R\x06readme\x88\x01\x01\x12\x14\n" +
	"\x05alias\x18\x06 \x01(\tR\x05alias\x12:\n" +
	"\n" +
	"visibility\x18\a \x01(\x0e2\x1a.reearth.cms.v1.VisibilityR\n" +
	"visibilityB\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_licenseB\t\n" +
	"\a_readme\"\xd6\x02\n" +
	"\x14UpdateProjectRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\alicense\x18\x04 \x01(\tH\x02R\alicense\x88\x01\x01\x12\x1b\n" +
	"\x06readme\x18\x05 \x01(\tH\x03R\x06readme\x88\x01\x01\x12\x19\n" +
	"\x05alias\x18\x06 \x01(\tH\x04R\x05alias\x88\x01\x01\x12?\n" +
	"\n" +
	"visibility\x18\a \x01(\x0e2\x1a.reearth.cms.v1.VisibilityH\x05R\n" +
	"visibility\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_licenseB\t\n" +
	"\a_readmeB\b\n" +
	"\x06_aliasB\r\n" +
	"\v_visibility\"5\n" +
	"\x14DeleteProjectRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"Y\n" +
	"\x13ListProjectsRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1f\n" +
	"\vpublic_only\x18\x02 \x01(\bR\n" +
	"publicOnly\"2\n" +
	"\x11ListModelsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"\x9e\x01\n" +
	"\x10ListItemsRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x17\n" +
	"\x04page\x18\x03 \x01(\x05H\x00R\x04page\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x04 \x01(\x05H\x01R\bpageSize\x88\x01\x01B\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_size\"I\n" +
	"\rExportRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\"D\n" +
	"\x0fProjectResponse\x121\n" +
	"\aproject\x18\x01 \x01(\v2\x17.reearth.cms.v1.ProjectR\aproject\"9\n" +
	"\x19AliasAvailabilityResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\"6\n" +
	"\x15DeleteProjectResponse\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"l\n" +
	"\x14ListProjectsResponse\x123\n" +
	"\bprojects\x18\x01 \x03(\v2\x17.reearth.cms.v1.ProjectR\bprojects\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"d\n" +
	"\x12ListModelsResponse\x12-\n" +
	"\x06models\x18\x01 \x03(\v2\x15.reearth.cms.v1.ModelR\x06models\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"`\n" +
	"\x11ListItemsResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.reearth.cms.v1.ItemR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"%\n" +
	"\x11ExportURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url*%\n" +
	"\n" +
	"Visibility\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x00\x12\v\n" +
	"\aPRIVATE\x10\x01*\xef\x01\n" +
	"\x0fSchemaFieldType\x12\b\n" +
	"\x04Text\x10\x00\x12\f\n" +
	"\bTextArea\x10\x01\x12\f\n" +
	"\bRichText\x10\x02\x12\x10\n" +
	"\fMarkdownText\x10\x03\x12\t\n" +
	"\x05Asset\x10\x04\x12\b\n" +
	"\x04Date\x10\x05\x12\b\n" +
	"\x04Bool\x10\x06\x12\n" +
	"\n" +
	"\x06Select\x10\a\x12\a\n" +
	"\x03Tag\x10\b\x12\v\n" +
	"\aInteger\x10\t\x12\n" +
	"\n" +
	"\x06Number\x10\n" +
	"\x12\r\n" +
	"\tReference\x10\v\x12\f\n" +
	"\bCheckbox\x10\f\x12\a\n" +
	"\x03URL\x10\r\x12\t\n" +
	"\x05Group\x10\x0e\x12\x12\n" +
	"\x0eGeometryObject\x10\x0f\x12\x12\n" +
	"\x0eGeometryEditor\x10\x102\xca\x06\n" +
	"\n" +
	"ReEarthCMS\x12X\n" +
	"\rCreateProject\x12$.reearth.cms.v1.CreateProjectRequest\x1a\x1f.reearth.cms.v1.ProjectResponse\"\x00\x12X\n" +
	"\rUpdateProject\x12$.reearth.cms.v1.UpdateProjectRequest\x1a\x1f.reearth.cms.v1.ProjectResponse\"\x00\x12^\n" +
	"\rDeleteProject\x12$.reearth.cms.v1.DeleteProjectRequest\x1a%.reearth.cms.v1.DeleteProjectResponse\"\x00\x12o\n" +
	"\x16CheckAliasAvailability\x12(.reearth.cms.v1.AliasAvailabilityRequest\x1a).reearth.cms.v1.AliasAvailabilityResponse\"\x00\x12O\n" +
	"\n" +
	"GetProject\x12\x1e.reearth.cms.v1.ProjectRequest\x1a\x1f.reearth.cms.v1.ProjectResponse\"\x00\x12[\n" +
	"\fListProjects\x12#.reearth.cms.v1.ListProjectsRequest\x1a$.reearth.cms.v1.ListProjectsResponse\"\x00\x12U\n" +
	"\n" +
	"ListModels\x12!.reearth.cms.v1.ListModelsRequest\x1a\".reearth.cms.v1.ListModelsResponse\"\x00\x12R\n" +
	"\tListItems\x12 .reearth.cms.v1.ListItemsRequest\x1a!.reearth.cms.v1.ListItemsResponse\"\x00\x12^\n" +
	"\x18GetModelGeoJSONExportURL\x12\x1d.reearth.cms.v1.ExportRequest\x1a!.reearth.cms.v1.ExportURLResponse\"\x00B3Z1github.com/reearth/reearth-flow/api/pkg/cms/protob\x06proto3"

var (
	file_pkg_cms_proto_schema_proto_rawDescOnce sync.Once
	file_pkg_cms_proto_schema_proto_rawDescData []byte
)

func file_pkg_cms_proto_schema_proto_rawDescGZIP() []byte {
	file_pkg_cms_proto_schema_proto_rawDescOnce.Do(func() {
		file_pkg_cms_proto_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_cms_proto_schema_proto_rawDesc), len(file_pkg_cms_proto_schema_proto_rawDesc)))
	})
	return file_pkg_cms_proto_schema_proto_rawDescData
}

var file_pkg_cms_proto_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_cms_proto_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_pkg_cms_proto_schema_proto_goTypes = []any{
	(Visibility)(0),                   // 0: reearth.cms.v1.Visibility
	(SchemaFieldType)(0),              // 1: reearth.cms.v1.SchemaFieldType
	(*Project)(nil),                   // 2: reearth.cms.v1.Project
	(*Model)(nil),                     // 3: reearth.cms.v1.Model
	(*Item)(nil),                      // 4: reearth.cms.v1.Item
	(*Schema)(nil),                    // 5: reearth.cms.v1.Schema
	(*SchemaField)(nil),               // 6: reearth.cms.v1.SchemaField
	(*ProjectRequest)(nil),            // 7: reearth.cms.v1.ProjectRequest
	(*AliasAvailabilityRequest)(nil),  // 8: reearth.cms.v1.AliasAvailabilityRequest
	(*CreateProjectRequest)(nil),      // 9: reearth.cms.v1.CreateProjectRequest
	(*UpdateProjectRequest)(nil),      // 10: reearth.cms.v1.UpdateProjectRequest
	(*DeleteProjectRequest)(nil),      // 11: reearth.cms.v1.DeleteProjectRequest
	(*ListProjectsRequest)(nil),       // 12: reearth.cms.v1.ListProjectsRequest
	(*ListModelsRequest)(nil),         // 13: reearth.cms.v1.ListModelsRequest
	(*ListItemsRequest)(nil),          // 14: reearth.cms.v1.ListItemsRequest
	(*ExportRequest)(nil),             // 15: reearth.cms.v1.ExportRequest
	(*ProjectResponse)(nil),           // 16: reearth.cms.v1.ProjectResponse
	(*AliasAvailabilityResponse)(nil), // 17: reearth.cms.v1.AliasAvailabilityResponse
	(*DeleteProjectResponse)(nil),     // 18: reearth.cms.v1.DeleteProjectResponse
	(*ListProjectsResponse)(nil),      // 19: reearth.cms.v1.ListProjectsResponse
	(*ListModelsResponse)(nil),        // 20: reearth.cms.v1.ListModelsResponse
	(*ListItemsResponse)(nil),         // 21: reearth.cms.v1.ListItemsResponse
	(*ExportURLResponse)(nil),         // 22: reearth.cms.v1.ExportURLResponse
	nil,                               // 23: reearth.cms.v1.Item.FieldsEntry
	(*timestamppb.Timestamp)(nil),     // 24: google.protobuf.Timestamp
	(*anypb.Any)(nil),                 // 25: google.protobuf.Any
}
var file_pkg_cms_proto_schema_proto_depIdxs = []int32{
	0,  // 0: reearth.cms.v1.Project.visibility:type_name -> reearth.cms.v1.Visibility
	24, // 1: reearth.cms.v1.Project.created_at:type_name -> google.protobuf.Timestamp
	24, // 2: reearth.cms.v1.Project.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 3: reearth.cms.v1.Model.schema:type_name -> reearth.cms.v1.Schema
	24, // 4: reearth.cms.v1.Model.created_at:type_name -> google.protobuf.Timestamp
	24, // 5: reearth.cms.v1.Model.updated_at:type_name -> google.protobuf.Timestamp
	23, // 6: reearth.cms.v1.Item.fields:type_name -> reearth.cms.v1.Item.FieldsEntry
	24, // 7: reearth.cms.v1.Item.created_at:type_name -> google.protobuf.Timestamp
	24, // 8: reearth.cms.v1.Item.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 9: reearth.cms.v1.Schema.fields:type_name -> reearth.cms.v1.SchemaField
	1,  // 10: reearth.cms.v1.SchemaField.type:type_name -> reearth.cms.v1.SchemaFieldType
	0,  // 11: reearth.cms.v1.CreateProjectRequest.visibility:type_name -> reearth.cms.v1.Visibility
	0,  // 12: reearth.cms.v1.UpdateProjectRequest.visibility:type_name -> reearth.cms.v1.Visibility
	2,  // 13: reearth.cms.v1.ProjectResponse.project:type_name -> reearth.cms.v1.Project
	2,  // 14: reearth.cms.v1.ListProjectsResponse.projects:type_name -> reearth.cms.v1.Project
	3,  // 15: reearth.cms.v1.ListModelsResponse.models:type_name -> reearth.cms.v1.Model
	4,  // 16: reearth.cms.v1.ListItemsResponse.items:type_name -> reearth.cms.v1.Item
	25, // 17: reearth.cms.v1.Item.FieldsEntry.value:type_name -> google.protobuf.Any
	9,  // 18: reearth.cms.v1.ReEarthCMS.CreateProject:input_type -> reearth.cms.v1.CreateProjectRequest
	10, // 19: reearth.cms.v1.ReEarthCMS.UpdateProject:input_type -> reearth.cms.v1.UpdateProjectRequest
	11, // 20: reearth.cms.v1.ReEarthCMS.DeleteProject:input_type -> reearth.cms.v1.DeleteProjectRequest
	8,  // 21: reearth.cms.v1.ReEarthCMS.CheckAliasAvailability:input_type -> reearth.cms.v1.AliasAvailabilityRequest
	7,  // 22: reearth.cms.v1.ReEarthCMS.GetProject:input_type -> reearth.cms.v1.ProjectRequest
	12, // 23: reearth.cms.v1.ReEarthCMS.ListProjects:input_type -> reearth.cms.v1.ListProjectsRequest
	13, // 24: reearth.cms.v1.ReEarthCMS.ListModels:input_type -> reearth.cms.v1.ListModelsRequest
	14, // 25: reearth.cms.v1.ReEarthCMS.ListItems:input_type -> reearth.cms.v1.ListItemsRequest
	15, // 26: reearth.cms.v1.ReEarthCMS.GetModelGeoJSONExportURL:input_type -> reearth.cms.v1.ExportRequest
	16, // 27: reearth.cms.v1.ReEarthCMS.CreateProject:output_type -> reearth.cms.v1.ProjectResponse
	16, // 28: reearth.cms.v1.ReEarthCMS.UpdateProject:output_type -> reearth.cms.v1.ProjectResponse
	18, // 29: reearth.cms.v1.ReEarthCMS.DeleteProject:output_type -> reearth.cms.v1.DeleteProjectResponse
	17, // 30: reearth.cms.v1.ReEarthCMS.CheckAliasAvailability:output_type -> reearth.cms.v1.AliasAvailabilityResponse
	16, // 31: reearth.cms.v1.ReEarthCMS.GetProject:output_type -> reearth.cms.v1.ProjectResponse
	19, // 32: reearth.cms.v1.ReEarthCMS.ListProjects:output_type -> reearth.cms.v1.ListProjectsResponse
	20, // 33: reearth.cms.v1.ReEarthCMS.ListModels:output_type -> reearth.cms.v1.ListModelsResponse
	21, // 34: reearth.cms.v1.ReEarthCMS.ListItems:output_type -> reearth.cms.v1.ListItemsResponse
	22, // 35: reearth.cms.v1.ReEarthCMS.GetModelGeoJSONExportURL:output_type -> reearth.cms.v1.ExportURLResponse
	27, // [27:36] is the sub-list for method output_type
	18, // [18:27] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_pkg_cms_proto_schema_proto_init() }
func file_pkg_cms_proto_schema_proto_init() {
	if File_pkg_cms_proto_schema_proto != nil {
		return
	}
	file_pkg_cms_proto_schema_proto_msgTypes[0].OneofWrappers = []any{}
	file_pkg_cms_proto_schema_proto_msgTypes[4].OneofWrappers = []any{}
	file_pkg_cms_proto_schema_proto_msgTypes[7].OneofWrappers = []any{}
	file_pkg_cms_proto_schema_proto_msgTypes[8].OneofWrappers = []any{}
	file_pkg_cms_proto_schema_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_cms_proto_schema_proto_rawDesc), len(file_pkg_cms_proto_schema_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_cms_proto_schema_proto_goTypes,
		DependencyIndexes: file_pkg_cms_proto_schema_proto_depIdxs,
		EnumInfos:         file_pkg_cms_proto_schema_proto_enumTypes,
		MessageInfos:      file_pkg_cms_proto_schema_proto_msgTypes,
	}.Build()
	File_pkg_cms_proto_schema_proto = out.File
	file_pkg_cms_proto_schema_proto_goTypes = nil
	file_pkg_cms_proto_schema_proto_depIdxs = nil
}
