version: 2
updates:
  - package-ecosystem: cargo
    directory: /worker
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Tokyo"
    target-branch: "main"
    labels: []
