# yaml-language-server: $schema=https://raw.githubusercontent.com/reearth/reearth-flow/main/engine/schema/workflow.json
id: 83307700-04b9-490c-b6a1-11b93e7f7a8a
name: "PLATEAU4-DataConvert-01-bldg-workflow"
entryGraphId: 34bf873b-3364-46b0-8153-efeb9568bb3c
with:
  cityGmlPath:
  codelists:
  schemas:
  targetPackages:
    - bldg
  outputPath:
graphs:
  - !include ../../../../graphs/plateau4/folder_and_file_path_reader.yml
  - id: 34bf873b-3364-46b0-8153-efeb9568bb3c
    name: entry_point
    nodes:
      - id: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        name: FeatureCreator
        type: action
        action: FeatureCreator
        with:
          creator: |
            [
              #{
                cityGmlPath: env.get("cityGmlPath"),
                cityCode: env.get("cityCode") ?? file::extract_filename(env.get("cityGmlPath"))[0..5],
                codelists: env.get("codelists"),
                schemas: env.get("schemas"),
              },
            ]

      - id: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        name: FolderAndFilePathReader
        type: subGraph
        subGraphId: c6863b71-953b-4d15-af56-396fc93fc617

      - id: ded2e272-e05c-4918-86b3-aa9f763da6e6
        name: FeatureReaderByCityGml
        type: action
        action: FeatureCityGmlReader
        with:
          format: citygml
          dataset: |
            env.get("__value")["path"]

      - id: 33e32a91-5ade-4265-8665-b061f552839c
        name: AttributeManagerForCityCodeAndCityName
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: cityCode
              method: convert
              value: |
                let attributes = env.get("__value").cityGmlAttributes;
                let buildingIdAttributes = attributes["uro:BuildingIDAttribute"] ?? {};
                buildingIdAttributes["uro:city_code"] ?? env.get("__value").cityCode

            - attribute: cityName
              method: convert
              value: |
                let attributes = env.get("__value").cityGmlAttributes;
                let buildingIdAttributes = attributes["uro:BuildingIDAttribute"] ?? {};
                buildingIdAttributes["uro:city"] ?? env.get("__value").cityName

      - id: 4ffbb8a3-371e-4938-aa73-c142f11bb04b
        name: FeatureSorter
        type: action
        action: FeatureSorter
        with:
          attributes:
            - path
          order: ascending

      - id: dc498449-5478-4bff-abaa-59f2d160925f
        name: PLATEAU4.MaxLodExtractor
        type: action
        action: PLATEAU4.MaxLodExtractor
        with:
          cityGmlPathAttribute: path
          maxLodAttribute: maxLod

      - id: 1fb4ce1c-538a-436d-8dfa-79185e032de3
        name: AttributeAggregatorByMaxLod
        type: action
        action: AttributeAggregator
        with:
          aggregateAttributes:
          - newAttribute: file
            attributeValue: |
              file::extract_filename(env.get("__value")["path"])
          - newAttribute: type
            attributeValue: |
              env.get("__feature_type")
          - newAttribute: maxLod
            attributeValue: |
              env.get("__value").maxLod
          calculation: |
            1
          calculationAttribute: count
          method: count

      - id: 52ff7b3c-5fbb-4ad2-86d9-5df50429e3b4
        name: AttributeMapperByMaxLod
        type: action
        action: AttributeMapper
        with:
          mappers:
          - attribute: code
            expr: |
              env.get("__value").file.split("_")[0]
          - attribute: type
            expr: |
              env.get("__value")["type"].split(":")[0]
          - attribute: maxLod
            expr: |
              env.get("__value").maxLod
          - attribute: file
            expr: |
              env.get("__value").file

      - id: 65074ffc-9113-4fbf-8957-9ba1de4c56ab
        name: FileWriterTsvFilePath
        type: action
        action: FileWriter
        with:
          format: csv
          output: |
            file::join_path(env.get("outputPath"), "maxLod.csv")

      - id: 5daabfc0-2bda-4f8d-b206-d7a388469f7a
        name: AttributeFlattener
        type: action
        action: PLATEAU4.AttributeFlattener

      - id: 8b05f9d4-1cb2-4071-a1da-c968431bc0ec
        name: VerticalReprojector
        type: action
        action: VerticalReprojector
        with:
          reprojectorType: jgd2011ToWgs84

      - id: 3e637368-48dc-48c2-aade-253d5b0cfeeb
        name: AttributeManagerRemoveUnnecessaryAttributes
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: meshcode
              method: create
              value: |
                file::extract_filename_without_ext(env.get("__value")["path"]).split("_")[0]
            - attribute: type
              method: rename
              value: "feature_type"
            - attribute: path
              method: rename
              value: "_path"
            - attribute: cityCode
              method: rename
              value: "city_code"
            - attribute: cityName
              method: rename
              value: "city_name"
            - attribute: gmlId
              method: rename
              value: "gml_id"
            - attribute: package
              method: remove
            - attribute: fileIndex
              method: remove
            - attribute: extension
              method: remove
            - attribute: root
              method: remove
            - attribute: gmlRootId
              method: remove
            - attribute: udxDirs
              method: remove
            - attribute: cityGmlPath
              method: remove
            - attribute: schemas
              method: remove
            - attribute: dirCodelists
              method: remove
            - attribute: dirSchemas
              method: remove
            - attribute: gmlName
              method: remove
            - attribute: codelists
              method: remove
            - attribute: maxLod
              method: remove
            - attribute: dirRoot
              method: remove

      - id: c32a279d-97be-4584-b282-4d65627b1132
        name: FeatureLodFilter
        type: action
        action: FeatureLodFilter
        with:
          filterKey: _path

      - id: 41d69f1f-2a4d-4bc1-a5d0-175698273571
        name: cesium3DTilesWriterByLod1
        type: action
        action: Cesium3DTilesWriter
        with:
          minZoom: 15
          maxZoom: 18
          attachTexture: false
          output: |
            file::join_path(env.get("outputPath"), "bldg_lod1")
          compressOutput: |
            file::join_path(env.get("outputPath"), "" + file::extract_filename_without_ext(env.get("cityGmlPath")) + "_3dtiles_lod1.zip")

      - id: a61799d5-176e-4fb9-aa64-5d350adf0bb8
        name: cesium3DTilesWriterByLod2
        type: action
        action: Cesium3DTilesWriter
        with:
          minZoom: 15
          maxZoom: 18
          attachTexture: true
          output: |
            file::join_path(env.get("outputPath"), "bldg_lod2")
          compressOutput: |
            file::join_path(env.get("outputPath"), "" + file::extract_filename_without_ext(env.get("cityGmlPath")) + "_3dtiles_lod2.zip")

      - id: fc4c3817-6efe-4d6e-8e82-ebd84d5e6e19
        name: cesium3DTilesWriterByLod2NoTexture
        type: action
        action: Cesium3DTilesWriter
        with:
          minZoom: 15
          maxZoom: 18
          attachTexture: false
          output: |
            file::join_path(env.get("outputPath"), "bldg_lod2_no_texture")
          compressOutput: |
            file::join_path(env.get("outputPath"), "" + file::extract_filename_without_ext(env.get("cityGmlPath")) + "_3dtiles_lod2_no_texture.zip")

      - id: 953f5c48-9875-4c78-a1d6-4619f8fdedd2
        name: cesium3DTilesWriterByLod3
        type: action
        action: Cesium3DTilesWriter
        with:
          minZoom: 15
          maxZoom: 18
          attachTexture: true
          output: |
            file::join_path(env.get("outputPath"), "bldg_lod3")
          compressOutput: |
            file::join_path(env.get("outputPath"), file::extract_filename_without_ext(env.get("cityGmlPath")) + "_3dtiles_lod3.zip")

      - id: 990ff798-168a-496e-a20a-b428de6a9ec0
        name: cesium3DTilesWriterByLod3NoTexture
        type: action
        action: Cesium3DTilesWriter
        with:
          minZoom: 15
          maxZoom: 18
          attachTexture: false
          output: |
            file::join_path(env.get("outputPath"), "bldg_lod3_no_texture")
          compressOutput: |
            file::join_path(env.get("outputPath"), file::extract_filename_without_ext(env.get("cityGmlPath")) + "_3dtiles_lod3_no_texture.zip")

      - id: b0f8f2c5-bb9b-4f4f-8c27-254367031ded
        name: cesium3DTilesWriterByLod4
        type: action
        action: Cesium3DTilesWriter
        with:
          minZoom: 15
          maxZoom: 18
          attachTexture: true
          output: |
             file::join_path(env.get("outputPath"), "bldg_lod4")
          compressOutput: |
            file::join_path(env.get("outputPath"), file::extract_filename_without_ext(env.get("cityGmlPath")) + "_3dtiles_lod4.zip")

      - id: 3dfe09e6-0de5-4ba6-ac84-8dd4d2e94638
        name: cesium3DTilesWriterByLod4NoTexture
        type: action
        action: Cesium3DTilesWriter
        with:
          minZoom: 15
          maxZoom: 18
          attachTexture: false
          output: |
            file::join_path(env.get("outputPath"), "bldg_lod4_no_texture")
          compressOutput: |
            file::join_path(env.get("outputPath"), file::extract_filename_without_ext(env.get("cityGmlPath")) + "_3dtiles_lod4_no_texture.zip")

    edges:
      - id: 5ebf24ab-1d98-49d5-8f58-eb7c18d27244
        from: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        to: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        fromPort: default
        toPort: default
      - id: 7b81f501-3f07-4cec-bf9b-9cefcebdf47d
        from: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        to: ded2e272-e05c-4918-86b3-aa9f763da6e6
        fromPort: default
        toPort: default
      - id: cf845867-6ffc-4b83-9fd5-e376a22470e2
        from: ded2e272-e05c-4918-86b3-aa9f763da6e6
        to: 33e32a91-5ade-4265-8665-b061f552839c
        fromPort: default
        toPort: default
      - id: f79ef31d-45f5-4aa5-ade2-620ab74bb35a
        from: 33e32a91-5ade-4265-8665-b061f552839c
        to: 4ffbb8a3-371e-4938-aa73-c142f11bb04b
        fromPort: default
        toPort: default
      - id: f7c94aaf-e43c-4779-893c-e5b23c0cf643
        from: 4ffbb8a3-371e-4938-aa73-c142f11bb04b
        to: dc498449-5478-4bff-abaa-59f2d160925f
        fromPort: default
        toPort: default
      - id: 046c94ea-9937-4439-b5f8-c8a616f6599d
        from: dc498449-5478-4bff-abaa-59f2d160925f
        to: 1fb4ce1c-538a-436d-8dfa-79185e032de3
        fromPort: default
        toPort: default
      - id: 59c14dab-0e56-4f90-85e6-0c8cfa6d1d14
        from: 1fb4ce1c-538a-436d-8dfa-79185e032de3
        to: 52ff7b3c-5fbb-4ad2-86d9-5df50429e3b4
        fromPort: default
        toPort: default
      - id: 993360df-5cfd-4525-9626-bfe13fa62117
        from: 52ff7b3c-5fbb-4ad2-86d9-5df50429e3b4
        to: 65074ffc-9113-4fbf-8957-9ba1de4c56ab
        fromPort: default
        toPort: default
      - id: 60ee038e-db4c-4c70-8c0a-a9cbfba726d0
        from: 4ffbb8a3-371e-4938-aa73-c142f11bb04b
        to: 5daabfc0-2bda-4f8d-b206-d7a388469f7a
        fromPort: default
        toPort: default
      - id: bfeb12b1-c8d5-4d13-928d-bf2b01672af9
        from: 5daabfc0-2bda-4f8d-b206-d7a388469f7a
        to: 8b05f9d4-1cb2-4071-a1da-c968431bc0ec
        fromPort: default
        toPort: default
      - id: fddd597c-3e9c-400c-abd9-02b6c2214459
        from: 8b05f9d4-1cb2-4071-a1da-c968431bc0ec
        to: 3e637368-48dc-48c2-aade-253d5b0cfeeb
        fromPort: default
        toPort: default
      - id: 64540b5c-066e-449f-ace1-4af29c0e3b3c
        from: 3e637368-48dc-48c2-aade-253d5b0cfeeb
        to: c32a279d-97be-4584-b282-4d65627b1132
        fromPort: default
        toPort: default
      - id: dde1d751-fe3e-4283-8742-ec4a61a41574
        from: c32a279d-97be-4584-b282-4d65627b1132
        to: 41d69f1f-2a4d-4bc1-a5d0-175698273571
        fromPort: up_to_lod1
        toPort: default
      - id: 2e6bfbbd-f48f-4cb8-97ac-46fe4ecc30bb
        from: c32a279d-97be-4584-b282-4d65627b1132
        to: a61799d5-176e-4fb9-aa64-5d350adf0bb8
        fromPort: up_to_lod2
        toPort: default
      - id: 2e6bfbbd-f48f-4cb8-97ac-46fe4ecc30bc
        from: c32a279d-97be-4584-b282-4d65627b1132
        to: fc4c3817-6efe-4d6e-8e82-ebd84d5e6e19
        fromPort: up_to_lod2
        toPort: default
      - id: ce3f3571-053c-4487-8e85-b95fb71a49c7
        from: c32a279d-97be-4584-b282-4d65627b1132
        to: 953f5c48-9875-4c78-a1d6-4619f8fdedd2
        fromPort: up_to_lod3
        toPort: default
      - id: ce3f3571-053c-4487-8e85-b95fb71a49c8
        from: c32a279d-97be-4584-b282-4d65627b1132
        to: 990ff798-168a-496e-a20a-b428de6a9ec0
        fromPort: up_to_lod3
        toPort: default
      - id: 841f1bed-a4d3-4425-a754-4f0dd7461eac
        from: c32a279d-97be-4584-b282-4d65627b1132
        to: b0f8f2c5-bb9b-4f4f-8c27-254367031ded
        fromPort: up_to_lod4
        toPort: default
      - id: 841f1bed-a4d3-4425-a754-4f0dd7461ead
        from: c32a279d-97be-4584-b282-4d65627b1132
        to: 3dfe09e6-0de5-4ba6-ac84-8dd4d2e94638
        fromPort: up_to_lod4
        toPort: default
