package app

// baseActions is the curated set of actions exposed in the Re:Earth Flow SaaS UI palette.
// All other actions in the schema are available for workflow execution but hidden from the UI.
var baseActions = map[string]bool{
	// Input
	"CityGML Reader":     true,
	"CSV Reader":         true,
	"Feature Creator":    true,
	"File Path Extractor": true,
	"GeoJSON Reader":     true,
	"GeoPackage Reader":  true,
	"JSON Reader":        true,
	"Shapefile Reader":   true,
	"SQL Reader":         true,
	// Output
	"Cesium 3D Tiles Writer": true,
	"CityGML Writer":       true,
	"CSV Writer":           true,
	"Echo Sink":            true,
	"GeoJSON Writer":       true,
	"GeoPackage Writer":    true,
	"JSON Writer":          true,
	"MVT Writer":           true,
	"Noop Sink":            true,
	"Shapefile Writer":     true,
	"XML Writer":           true,
	"Zip File Writer":       true,
	// Geometry
	"Appearance Remover":      true,
	"Area Calculator":         true,
	"Bounds Extractor":        true,
	"Bufferer":               true,
	"Clipper":                true,
	"Dimension Filter":        true,
	"Elevation Extractor":     true,
	"Extruder":               true,
	"Footprint Replacer":      true,
	"Geometry Extractor":      true,
	"Geometry Part Extractor":  true,
	"Geometry Remover":        true,
	"Geometry Replacer":       true,
	"Geometry Validator":      true,
	"Geometry Splitter":       true,
	"Grid Divider":            true,
	"Horizontal Reprojector":  true,
	"Image Rasterizer":        true,
	"Polygon Normal Extractor": true,
	"Ray Intersector":         true,
	"Refiner":                true,
	"Spatial Filter":          true,
	"Three Dimension Forcer":   true,
	"Two Dimension Forcer":     true,
	"Vertical Reprojector":    true,
	// Attribute
	"Attribute Aggregator":      true,
	"Attribute Conversion Table": true,
	"Attribute Flattener":       true,
	"Attribute Manager":         true,
	"Attribute Mapper":          true,
	"Bulk Attribute Renamer":     true,
	"Null Attribute Mapper":      true,
	"Statistics Calculator":     true,
	// Feature / Flow
	"Feature CityGML Reader":     true,
	"Feature Counter":           true,
	"Feature File Path Extractor": true,
	"Feature Filter":            true,
	"Feature Joiner":            true,
	"Feature LOD Filter":         true,
	"Feature Merger":            true,
	"Feature Sorter":            true,
	"Feature Transformer":       true,
	"Feature Type Filter":        true,
	"Input Router":              true,
	"Output Router":             true,
	"Rhai Caller":               true,
	// Utility
	"Directory Decompressor": true,
	"Echo Processor":         true,
	"File Property Extractor": true,
	"List Exploder":          true,
	"Noop Processor":         true,
	"XML Fragmenter":         true,
	"XML Validator":          true,
}
