package app

// baseActions is the curated set of actions exposed in the Re:Earth Flow SaaS UI palette.
// All other actions in the schema are available for workflow execution but hidden from the UI.
var baseActions = map[string]bool{
	// Input
	"CityGML Reader":      true,
	"CSV Reader":          true,
	"Feature Creator":     true,
	"File Path Extractor": true,
	"GeoJSON Reader":      true,
	"GeoPackage Reader":   true,
	"glTF Reader":         true,
	"JSON Reader":         true,
	"OBJ Reader":          true,
	"Shapefile Reader":    true,
	"SQL Reader":          true,
	// Output
	"Cesium 3D Tiles Writer": true,
	"CityGML Writer":         true,
	"CSV Writer":             true,
	"Echo Sink":              true,
	"Excel Writer":           true,
	"GeoJSON Writer":         true,
	"GeoPackage Writer":      true,
	"JSON Writer":            true,
	"MVT Writer":             true,
	"Noop Sink":              true,
	"Shapefile Writer":       true,
	"XML Writer":             true,
	"Zip File Writer":        true,
	// Geometry
	"Appearance Remover":           true,
	"Area Calculator":              true,
	"Area On Area Overlayer":       true,
	"Bounds Extractor":             true,
	"Bufferer":                     true,
	"Center Point Replacer":        true,
	"Clipper":                      true,
	"Coordinate Frame Reprojector": true,
	"CSG Builder":                  true,
	"CSG Evaluator":                true,
	"Dimension Filter":             true,
	"Dissolver":                    true,
	"Elevation Extractor":          true,
	"Extruder":                     true,
	"Footprint Replacer":           true,
	"Geometry Coercer":             true,
	"Geometry Extractor":           true,
	"Geometry Filter":              true,
	"Geometry Part Extractor":      true,
	"Geometry Remover":             true,
	"Geometry Replacer":            true,
	"Geometry Splitter":            true,
	"Geometry Validator":           true,
	"Grid Divider":                 true,
	"Hole Counter":                 true,
	"Hole Extractor":               true,
	"Horizontal Reprojector":       true,
	"Image Rasterizer":             true,
	"Line On Line Overlayer":       true,
	"Neighbor Finder":              true,
	"Offsetter":                    true,
	"Polygon Normal Extractor":     true,
	"Ray Intersector":              true,
	"Refiner":                      true,
	"Spatial Filter":               true,
	"Three Dimension Forcer":       true,
	"Two Dimension Forcer":         true,
	"Vertical Reprojector":         true,
	// Attribute
	"Attribute Aggregator":               true,
	"Attribute Bulk Array Joiner":        true,
	"Attribute Conversion Table":         true,
	"Attribute Duplicate Filter":         true,
	"Attribute File Path Info Extractor": true,
	"Attribute Flattener":                true,
	"Attribute Manager":                  true,
	"Attribute Mapper":                   true,
	"Attribute Range Mapper":             true,
	"Attribute Table Extractor":          true,
	"Bulk Attribute Renamer":             true,
	"Date Time Converter":                true,
	"Null Attribute Mapper":              true,
	"Statistics Calculator":              true,
	// Feature / Flow
	"Feature CityGML 2 Reader":    true,
	"Feature CityGML 3 Reader":    true,
	"Feature CityGML Reader":      true,
	"Feature Counter":             true,
	"Feature Duplicate Filter":    true,
	"Feature File Path Extractor": true,
	"Feature Filter":              true,
	"Feature GeoJSON Writer":      true,
	"Feature Joiner":              true,
	"Feature LOD Filter":          true,
	"Feature Merger":              true,
	"Feature Reader":              true,
	"Feature Sorter":              true,
	"Feature Transformer":         true,
	"Feature Type Filter":         true,
	"Feature Writer":              true,
	"Input Router":                true,
	"JSON Fragmenter":             true,
	"List Concatenator":           true,
	"List Indexer":                true,
	"Output Router":               true,
	// Utility
	"Directory Decompressor":  true,
	"Echo Processor":          true,
	"File Property Extractor": true,
	"HTTP Caller":             true,
	"List Exploder":           true,
	"Noop Processor":          true,
	"XML Fragmenter":          true,
	"XML Validator":           true,
}
