# workflow for calculate snow correction for solar energy

id: 2d4e1c6a-eb70-11f0-9b6c-7c70db10a7e3
name: CalculateSnowCorrectionFactor
entryGraphId: 2c8e0b08-eb72-11f0-b371-7c70db10a7e3
with:
  csvFile: !include ./input.csv
graphs:
  - id: 2c8e0b08-eb72-11f0-b371-7c70db10a7e3
    name: SnowFactorWorkflow
    nodes:
      - id: 454dfd76-eb70-11f0-8280-7c70db10a7e3
        name: CsvReader
        type: action
        action: CsvReader
        with:
          format: csv
          inline: |
            env.get("csvFile")

      - id: 630f7e44-eb74-11f0-81ac-7c70db10a7e3
        name: Tester_3
        type: action
        action: AttributeManager
        with:
          operations:
          - attribute: col0
            method: convert
            value: |
              9

      - id: 78b75e32-eb70-11f0-a1de-7c70db10a7e3
        name: RenameAttributeAndConvertTheirValue
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: observatory
              method: create
              value: |
                env.get("__value")["col0"]

            - attribute: month
              method: create
              value: |
                let v = env.get("__value")["col1"];
                parse_int(v)

            - attribute: day
              method: create
              value: |
                let v = env.get("__value")["col2"];
                parse_int(v)

            - attribute: year
              method: create
              value: |
                let v = env.get("__value")["col3"];
                parse_int(v)

            - attribute: snow_depth{0}
              method: create
              value: |
                let v = env.get("__value")["col4"];
                parse_int(v)

            - attribute: snow_depth{1}
              method: create
              value: |
                let v = env.get("__value")["col5"];
                parse_int(v)

            - attribute: snow_depth{2}
              method: create
              value: |
                let v = env.get("__value")["col6"];
                parse_int(v)

            - attribute: snow_depth{3}
              method: create
              value: |
                let v = env.get("__value")["col7"];
                parse_int(v)

            - attribute: snow_depth{4}
              method: create
              value: |
                let v = env.get("__value")["col8"];
                parse_int(v)

            - attribute: snow_depth{5}
              method: create
              value: |
                let v = env.get("__value")["col9"];
                parse_int(v)

            - attribute: snow_depth{6}
              method: create
              value: |
                let v = env.get("__value")["col10"];
                parse_int(v)

            - attribute: snow_depth{7}
              method: create
              value: |
                let v = env.get("__value")["col11"];
                parse_int(v)

            - attribute: snow_depth{8}
              method: create
              value: |
                let v = env.get("__value")["col12"];
                parse_int(v)

            - attribute: snow_depth{9}
              method: create
              value: |
                let v = env.get("__value")["col13"];
                parse_int(v)

            - attribute: snow_depth{10}
              method: create
              value: |
                let v = env.get("__value")["col14"];
                parse_int(v)

            - attribute: snow_depth{11}
              method: create
              value: |
                let v = env.get("__value")["col15"];
                parse_int(v)

            - attribute: snow_depth{12}
              method: create
              value: |
                let v = env.get("__value")["col16"];
                parse_int(v)

            - attribute: snow_depth{13}
              method: create
              value: |
                let v = env.get("__value")["col17"];
                parse_int(v)

            - attribute: snow_depth{14}
              method: create
              value: |
                let v = env.get("__value")["col18"];
                parse_int(v)

            - attribute: snow_depth{15}
              method: create
              value: |
                let v = env.get("__value")["col19"];
                parse_int(v)

            - attribute: snow_depth{16}
              method: create
              value: |
                let v = env.get("__value")["col20"];
                parse_int(v)

            - attribute: snow_depth{17}
              method: create
              value: |
                let v = env.get("__value")["col21"];
                parse_int(v)

            - attribute: snow_depth{18}
              method: create
              value: |
                let v = env.get("__value")["col22"];
                parse_int(v)

            - attribute: snow_depth{19}
              method: create
              value: |
                let v = env.get("__value")["col23"];
                parse_int(v)

            - attribute: snow_depth{20}
              method: create
              value: |
                let v = env.get("__value")["col24"];
                parse_int(v)

            - attribute: snow_depth{21}
              method: create
              value: |
                let v = env.get("__value")["col25"];
                parse_int(v)

            - attribute: snow_depth{22}
              method: create
              value: |
                let v = env.get("__value")["col26"];
                parse_int(v)

            - attribute: snow_depth{23}
              method: create
              value: |
                let v = env.get("__value")["col27"];
                parse_int(v)

            - attribute: aggregate1
              method: create
              value: |
                let v = env.get("__value")["col28"];
                parse_int(v)

            - attribute: aggregate2
              method: create
              value: |
                let v = env.get("__value")["col29"];
                parse_int(v)

            - attribute: aggregate3
              method: create
              value: |
                let v = env.get("__value")["col30"];
                parse_int(v)

            - attribute: aggregate4
              method: create
              value: |
                let v = env.get("__value")["col31"];
                parse_int(v)

            - attribute: day2
              method: create
              value: |
                let v = env.get("__value")["col32"];
                parse_int(v)

            - attribute: col0
              method: remove
            - attribute: col1
              method: remove
            - attribute: col2
              method: remove
            - attribute: col3
              method: remove
            - attribute: col4
              method: remove
            - attribute: col5
              method: remove
            - attribute: col6
              method: remove
            - attribute: col7
              method: remove
            - attribute: col8
              method: remove
            - attribute: col9
              method: remove
            - attribute: col10
              method: remove
            - attribute: col11
              method: remove
            - attribute: col12
              method: remove
            - attribute: col13
              method: remove
            - attribute: col14
              method: remove
            - attribute: col15
              method: remove
            - attribute: col16
              method: remove
            - attribute: col17
              method: remove
            - attribute: col18
              method: remove
            - attribute: col19
              method: remove
            - attribute: col20
              method: remove
            - attribute: col21
              method: remove
            - attribute: col22
              method: remove
            - attribute: col23
              method: remove
            - attribute: col24
              method: remove
            - attribute: col25
              method: remove
            - attribute: col26
              method: remove
            - attribute: col27
              method: remove
            - attribute: col28
              method: remove
            - attribute: col29
              method: remove
            - attribute: col30
              method: remove
            - attribute: col31
              method: remove
            - attribute: col32
              method: remove

      - id: 38658a84-eb75-11f0-b42e-7c70db10a7e3
        name: DummyOutput
        type: action
        action: NoopSink

    edges:
      - id: beec4146-eb71-11f0-a144-7c70db10a7e3
        from: 454dfd76-eb70-11f0-8280-7c70db10a7e3
        to: 630f7e44-eb74-11f0-81ac-7c70db10a7e3
        fromPort: default
        toPort: default

      - id: cb592162-eb74-11f0-8d92-7c70db10a7e3
        from: 630f7e44-eb74-11f0-81ac-7c70db10a7e3
        to: 78b75e32-eb70-11f0-a1de-7c70db10a7e3
        fromPort: default
        toPort: default

      - id: 61342df8-eb75-11f0-880e-7c70db10a7e3
        from: 78b75e32-eb70-11f0-a1de-7c70db10a7e3
        to: 38658a84-eb75-11f0-b42e-7c70db10a7e3
        fromPort: default
        toPort: default
