# workflow for calculate snow correction for solar energy

id: 2d4e1c6a-eb70-11f0-9b6c-7c70db10a7e3
name: CalculateSnowCorrectionFactor
entryGraphId: 2c8e0b08-eb72-11f0-b371-7c70db10a7e3
with:
  csvFile: !include ./input.csv
graphs:
  - id: 2c8e0b08-eb72-11f0-b371-7c70db10a7e3
    name: SnowFactorWorkflow
    nodes:
      - id: 454dfd76-eb70-11f0-8280-7c70db10a7e3
        name: CsvReader
        type: action
        action: CsvReader
        with:
          format: csv
          inline: |
            env.get("csvFile")

      - id: 630f7e44-eb74-11f0-81ac-7c70db10a7e3
        name: Tester_3
        type: action
        action: FeatureFilter
        with:
          conditions:
          - expr: |
              env.get("__value").col0 == "9"
            outputPort: default

      - id: 78b75e32-eb70-11f0-a1de-7c70db10a7e3
        name: AttributeManager_5
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: observatory
              method: create
              value: |
                env.get("__value")["col0"]

            - attribute: month
              method: create
              value: |
                let v = env.get("__value")["col1"];
                parse_int(v)

            - attribute: day
              method: create
              value: |
                let v = env.get("__value")["col2"];
                parse_int(v)

            - attribute: year
              method: create
              value: |
                let v = env.get("__value")["col3"];
                parse_int(v)

            - attribute: snow_depth{0}
              method: create
              value: |
                let v = env.get("__value")["col4"];
                parse_int(v)

            - attribute: snow_depth{1}
              method: create
              value: |
                let v = env.get("__value")["col5"];
                parse_int(v)

            - attribute: snow_depth{2}
              method: create
              value: |
                let v = env.get("__value")["col6"];
                parse_int(v)

            - attribute: snow_depth{3}
              method: create
              value: |
                let v = env.get("__value")["col7"];
                parse_int(v)

            - attribute: snow_depth{4}
              method: create
              value: |
                let v = env.get("__value")["col8"];
                parse_int(v)

            - attribute: snow_depth{5}
              method: create
              value: |
                let v = env.get("__value")["col9"];
                parse_int(v)

            - attribute: snow_depth{6}
              method: create
              value: |
                let v = env.get("__value")["col10"];
                parse_int(v)

            - attribute: snow_depth{7}
              method: create
              value: |
                let v = env.get("__value")["col11"];
                parse_int(v)

            - attribute: snow_depth{8}
              method: create
              value: |
                let v = env.get("__value")["col12"];
                parse_int(v)

            - attribute: snow_depth{9}
              method: create
              value: |
                let v = env.get("__value")["col13"];
                parse_int(v)

            - attribute: snow_depth{10}
              method: create
              value: |
                let v = env.get("__value")["col14"];
                parse_int(v)

            - attribute: snow_depth{11}
              method: create
              value: |
                let v = env.get("__value")["col15"];
                parse_int(v)

            - attribute: snow_depth{12}
              method: create
              value: |
                let v = env.get("__value")["col16"];
                parse_int(v)

            - attribute: snow_depth{13}
              method: create
              value: |
                let v = env.get("__value")["col17"];
                parse_int(v)

            - attribute: snow_depth{14}
              method: create
              value: |
                let v = env.get("__value")["col18"];
                parse_int(v)

            - attribute: snow_depth{15}
              method: create
              value: |
                let v = env.get("__value")["col19"];
                parse_int(v)

            - attribute: snow_depth{16}
              method: create
              value: |
                let v = env.get("__value")["col20"];
                parse_int(v)

            - attribute: snow_depth{17}
              method: create
              value: |
                let v = env.get("__value")["col21"];
                parse_int(v)

            - attribute: snow_depth{18}
              method: create
              value: |
                let v = env.get("__value")["col22"];
                parse_int(v)

            - attribute: snow_depth{19}
              method: create
              value: |
                let v = env.get("__value")["col23"];
                parse_int(v)

            - attribute: snow_depth{20}
              method: create
              value: |
                let v = env.get("__value")["col24"];
                parse_int(v)

            - attribute: snow_depth{21}
              method: create
              value: |
                let v = env.get("__value")["col25"];
                parse_int(v)

            - attribute: snow_depth{22}
              method: create
              value: |
                let v = env.get("__value")["col26"];
                parse_int(v)

            - attribute: snow_depth{23}
              method: create
              value: |
                let v = env.get("__value")["col27"];
                parse_int(v)

            - attribute: aggregate1
              method: create
              value: |
                let v = env.get("__value")["col28"];
                parse_int(v)

            - attribute: aggregate2
              method: create
              value: |
                let v = env.get("__value")["col29"];
                parse_int(v)

            - attribute: aggregate3
              method: create
              value: |
                let v = env.get("__value")["col30"];
                parse_int(v)

            - attribute: aggregate4
              method: create
              value: |
                let v = env.get("__value")["col31"];
                parse_int(v)

            - attribute: day2
              method: create
              value: |
                let v = env.get("__value")["col32"];
                parse_int(v)

            - attribute: col0
              method: remove
            - attribute: col1
              method: remove
            - attribute: col2
              method: remove
            - attribute: col3
              method: remove
            - attribute: col4
              method: remove
            - attribute: col5
              method: remove
            - attribute: col6
              method: remove
            - attribute: col7
              method: remove
            - attribute: col8
              method: remove
            - attribute: col9
              method: remove
            - attribute: col10
              method: remove
            - attribute: col11
              method: remove
            - attribute: col12
              method: remove
            - attribute: col13
              method: remove
            - attribute: col14
              method: remove
            - attribute: col15
              method: remove
            - attribute: col16
              method: remove
            - attribute: col17
              method: remove
            - attribute: col18
              method: remove
            - attribute: col19
              method: remove
            - attribute: col20
              method: remove
            - attribute: col21
              method: remove
            - attribute: col22
              method: remove
            - attribute: col23
              method: remove
            - attribute: col24
              method: remove
            - attribute: col25
              method: remove
            - attribute: col26
              method: remove
            - attribute: col27
              method: remove
            - attribute: col28
              method: remove
            - attribute: col29
              method: remove
            - attribute: col30
              method: remove
            - attribute: col31
              method: remove
            - attribute: col32
              method: remove

      - id: 2b4b16a6-f116-11f0-809d-7c70db10a7e3
        name: ListExploder
        type: action 
        action: ListExploder
        with:
          sourceAttribute: snow_depth
          matchAll: true 
          showAttributeIndex: true

      - id: b86b4170-f1b4-11f0-bf60-6c02e0440ed6
        name: AttributeCreator_7
        type: action 
        action: AttributeManager
        with:
          operations:
            - attribute: date_key
              method: create
              value: |
                let year = env.get("__value")["year"];
                let month = env.get("__value")["month"];
                let day = env.get("__value")["day"];

                let month_str = if month < 10 { "0" + month } else { month.to_string() };
                let day_str = if day < 10 { "0" + day } else { day.to_string() };
                year.to_string() + "/" + month_str + "/" + day_str

            - attribute: date_key(MMDD)
              method: create
              value: |                
                let month = env.get("__value")["month"];
                let day = env.get("__value")["day"];

                let month_str = if month < 10 { "0" + month } else { month.to_string() };
                let day_str = if day < 10 { "0" + day } else { day.to_string() };
                month_str + "/" + day_str      

            - attribute: date_key(YYYYMM)
              method: create
              value: |                
                let year = env.get("__value")["year"];
                let month = env.get("__value")["month"];

                let month_str = if month < 10 { "0" + month } else { month.to_string() };
                year.to_string() + "/" + month_str                    

      - id: 77b33a0c-f1be-11f0-866f-6c02e0440ed6
        name: AttributeManager_3
        type: action 
        action: AttributeManager
        with:
          operations:
            - attribute: time
              method: create
              value: |
                let v = env.get("__value")["_element_index"];
                parse_int(v)
            - attribute: _element_index
              method: remove       

      # @Value(snow_depth) >= 10 ? 0 : @Value(snow_depth) < 0 ? 1 : 1 - (@Value(snow_depth) / 10.0)
      - id: 456f2bb8-f1bf-11f0-beff-6c02e0440ed6
        name: ExpressionEvaluator_5
        type: action 
        action: AttributeManager
        with:
          operations:
          - attribute: snow_correction_factor
            method: create 
            value: |
              let snow_depth = env.get("__value")["snow_depth"];   
              if snow_depth >= 10 {
                0.0
              } else if snow_depth < 0 {
                1.0
              } else {                
                1 - (snow_depth * 1.0) / 10.0
              }

      # Begin Fan out to 3 aggregators 
      - id: cdf6a3ac-f1d9-11f0-91bc-6c02e0440ed6
        name: Aggregator_5
        type: action 
        action: AttributeAggregator
        with:
          method: max 
          calculationAttribute:  year
          aggregateAttributes:
          - newAttribute: snow_correction_factor
            attributeValue: |
              env.get("__value").snow_correction_factor
       
      - id: 5ea66d6a-f1da-11f0-8477-6c02e0440ed6
        name: Aggregator_3
        type: action 
        action: AttributeAggregator
        with:
          method: max
          calculationAttribute:  date_key 
          aggregateAttributes:
          - newAttribute: snow_correction_factor
            attributeValue: |
              env.get("__value").snow_correction_factor

      - id: 6495f93e-f1da-11f0-a88b-6c02e0440ed6
        name: Aggregator_6
        type: action 
        action: AttributeAggregator
        with:
          method: max
          calculationAttribute:  date_key(YYYYMM) 
          aggregateAttributes:
          - newAttribute: snow_correction_factor
            attributeValue: |
              env.get("__value").snow_correction_factor              
      # End Fan out to 3 aggregators 


      - id: 38658a84-eb75-11f0-b42e-7c70db10a7e3
        name: DummyOutput
        type: action
        action: NoopSink

    edges:
      - id: beec4146-eb71-11f0-a144-7c70db10a7e3
        from: 454dfd76-eb70-11f0-8280-7c70db10a7e3
        to: 630f7e44-eb74-11f0-81ac-7c70db10a7e3
        fromPort: default
        toPort: default

      # From Tester_3 to AttributeManager_5
      - id: cb592162-eb74-11f0-8d92-7c70db10a7e3
        from: 630f7e44-eb74-11f0-81ac-7c70db10a7e3
        to: 78b75e32-eb70-11f0-a1de-7c70db10a7e3
        fromPort: default
        toPort: default

      # From AttributeManager_5 to ListExploder
      - id: af550e52-f116-11f0-9087-7c70db10a7e3
        from: 78b75e32-eb70-11f0-a1de-7c70db10a7e3
        to: 2b4b16a6-f116-11f0-809d-7c70db10a7e3
        fromPort: default 
        toPort: default 

      # From ListExploder to AttributeCreator_7
      - id: ac338fc4-f1b5-11f0-8d3a-6c02e0440ed6
        from: 2b4b16a6-f116-11f0-809d-7c70db10a7e3
        to: b86b4170-f1b4-11f0-bf60-6c02e0440ed6
        fromPort: default 
        toPort: default 

      # From AttributeCreator_7 to AttributeManager_3
      - id: 61342df8-eb75-11f0-880e-7c70db10a7e3
        from: b86b4170-f1b4-11f0-bf60-6c02e0440ed6
        to: 77b33a0c-f1be-11f0-866f-6c02e0440ed6
        fromPort: default
        toPort: default

      # Last edge connect with sink
      - id: a366c30c-f1bf-11f0-934b-6c02e0440ed6
        from: 77b33a0c-f1be-11f0-866f-6c02e0440ed6
        to: 456f2bb8-f1bf-11f0-beff-6c02e0440ed6
        fromPort: default
        toPort: default        

      # Last edge connect with sink
      - id: 04630626-f1bf-11f0-96cc-6c02e0440ed6
        from: 456f2bb8-f1bf-11f0-beff-6c02e0440ed6
        to: 38658a84-eb75-11f0-b42e-7c70db10a7e3
        fromPort: default
        toPort: default

      # Test 3 aggregators 
      - id: 88686efa-f1da-11f0-b3a9-6c02e0440ed6
        from: cdf6a3ac-f1d9-11f0-91bc-6c02e0440ed6
        to: 38658a84-eb75-11f0-b42e-7c70db10a7e3
        fromPort: default
        toPort: default  

      - id: 982b6a90-f1da-11f0-a079-6c02e0440ed6
        from: 5ea66d6a-f1da-11f0-8477-6c02e0440ed6
        to: 38658a84-eb75-11f0-b42e-7c70db10a7e3
        fromPort: default
        toPort: default    

      - id: 6495f93e-f1da-11f0-a88b-6c02e0440ed6
        from: 456f2bb8-f1bf-11f0-beff-6c02e0440ed6
        to: 38658a84-eb75-11f0-b42e-7c70db10a7e3
        fromPort: default
        toPort: default                         
