# yaml-language-server: $schema=https://raw.githubusercontent.com/reearth/reearth-flow/main/engine/schema/workflow.json
id: 3da19dc4-1ebd-4762-8250-2a4bc8043409
name: "PLATEAU4-A008-2-workflow"
entryGraphId: 3e3450c8-2344-4728-afa9-5fdb81eec33a
graphs:
  - id: 3e3450c8-2344-4728-afa9-5fdb81eec33a
    name: entry_point
    nodes:
      - id: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        name: FeatureCreator
        type: action
        action: FeatureCreator
        with:
          creator: |
            [
              #{
                testAttribute01: "2025-02-13T12:20:00Z",
                testAttribute02: "2025-02-01",
              },
              #{
                testAttribute01: "2025-02-14T08:10:00Z",
                testAttribute02: "2025-02-02",
              },
            ]

      - id: 61e89fd2-ea66-4fa1-b426-6f84484a9d38
        name: AttributeManager
        type: action
        action: AttributeManager
        with:
          operations:
          - attribute: extractYear
            method: create
            value: |
              datetime::extract_year(env.get("__value").testAttribute02)
          - attribute: extractMonth
            method: create
            value: |
              datetime::extract_month(env.get("__value").testAttribute02)
          - attribute: extractDay
            method: create
            value: |
              datetime::extract_day(env.get("__value").testAttribute02)
          - attribute: extractHour
            method: create
            value: |
              datetime::extract_hour(env.get("__value").testAttribute01)
          - attribute: extractMinute
            method: create
            value: |
              datetime::extract_minute(env.get("__value").testAttribute01)
          - attribute: extractSecond
            method: create
            value: |
              datetime::extract_second(env.get("__value").testAttribute01)
          - attribute: addYear
            method: create
            value: |
              datetime::add_year(env.get("__value").testAttribute02, 1)
          - attribute: addMonth
            method: create
            value: |
              datetime::add_month(env.get("__value").testAttribute02, 1)
          - attribute: addDay
            method: create
            value: |
              datetime::add_day(env.get("__value").testAttribute02, 1)
          - attribute: addHour
            method: create
            value: |
              datetime::add_hour(env.get("__value").testAttribute01, 1)
          - attribute: addMinute
            method: create
            value: |
              datetime::add_minute(env.get("__value").testAttribute01, 1)
          - attribute: addSecond
            method: create
            value: |
              datetime::add_second(env.get("__value").testAttribute01, 1)

      - id: f5e66920-24c0-4c70-ae16-6be1ed3b906c
        name: FileWriterCSV
        type: action
        action: FileWriter
        with:
          format: csv
          output: |
            file::join_path(env.get("currentPath"), "a008-2.csv")

    edges:
      - id: c064cf52-705f-443a-b2de-6795266c540d
        from: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        to: 61e89fd2-ea66-4fa1-b426-6f84484a9d38
        fromPort: default
        toPort: default
      - id: c81ea200-9aa1-4522-9f72-10e8b9184cb7
        from: 61e89fd2-ea66-4fa1-b426-6f84484a9d38
        to: f5e66920-24c0-4c70-ae16-6be1ed3b906c
        fromPort: default
        toPort: default
