# yaml-language-server: $schema=https://raw.githubusercontent.com/reearth/reearth-flow/main/engine/schema/workflow.json
id: a1b2c3d4-e5f6-7890-abcd-ef1234567890
name: "Solar Radiation Combined Workflow"
entryGraphId: ef57d360-df12-11f0-a558-7c70db10a7e3
with:
  cityGmlPath: null
  csvFile: |
    年月日,出,方位[°],南中,高度[°],入り,方位[°]00
    2023/1/1,7:06,118.3,11:57:59,30.7,16:50,241.7
    2023/1/2,7:06,118.2,11:58:28,30.8,16:51,241.8
    2023/1/3,7:06,118.1,11:58:55,30.9,16:52,241.9
graphs:
  - !include ../plateau-data-to-surface/workflow.yml
  - !include ../time-to-time-value/workflow.yml
  - id: ef57d360-df12-11f0-a558-7c70db10a7e3
    name: SolarPotentialWorkflow
    nodes:
      - id: 1a2b3c4d-5e6f-7890-1234-567890123456
        name: PlateauDataProcessor
        type: subGraph
        subGraphId: 8a6c4f2e-9b1d-4e7a-b3c5-6f8e2a4b9d7c

      - id: 2b3c4d5e-6f78-9012-3456-789012345678
        name: TimeDataProcessor
        type: subGraph
        subGraphId: 78ce67ea-d017-11f0-99c4-7c70db10a7e3

      - id: 2a5a577a-df14-11f0-84ed-7c70db10a7e3
        name: FeatureMerger
        type: action
        action: FeatureMerger
        with:
          requestorAttribute:
          - join_key
          supplierAttribute:
          - join_key

      - id: 3c4d5e6f-7890-1234-5678-901234567890
        name: SolarPotentialCalculator
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: solar_potential
              method: create
              value: |
                let surface_area = env.get("__value")["calculated_area"] ?? 0.0;
                let solar_radiation = env.get("__value")["日射量[kWh/m2].sum"] ?? 0.0;
                surface_area * solar_radiation

      - id: 4d5e6f78-9012-3456-7890-123456789012
        name: OutputRouter
        type: action
        action: NoopSink

    edges:
      # subgraph to feature merger 
      - id: e2f34567-8901-2345-6789-012345678901
        from: 1a2b3c4d-5e6f-7890-1234-567890123456
        to: 2a5a577a-df14-11f0-84ed-7c70db10a7e3
        fromPort: default
        toPort: supplier

      # subgraph to feature merger
      - id: f3456789-0123-4567-8901-234567890123
        from: 2b3c4d5e-6f78-9012-3456-789012345678
        to: 2a5a577a-df14-11f0-84ed-7c70db10a7e3
        fromPort: default
        toPort: requestor

      # feature merger to solar potential 
      - id: 45678901-2345-6789-0123-456789012345
        from: 2a5a577a-df14-11f0-84ed-7c70db10a7e3
        to: 3c4d5e6f-7890-1234-5678-901234567890
        fromPort: merged
        toPort: default

      # solar potential calculated
      - id: 56789012-3456-7890-1234-567890123456
        from: 3c4d5e6f-7890-1234-5678-901234567890
        to: 4d5e6f78-9012-3456-7890-123456789012
        fromPort: default
        toPort: default