# yaml-language-server: $schema=https://raw.githubusercontent.com/reearth/reearth-flow/main/engine/schema/workflow.json
id: f01ce0bb-e982-4dfa-94de-7a766156b4b3
name: "QualityCheck-01-common-workflow"
entryGraphId: 7f86c5d5-b375-4190-ab93-001e9a099d1e
with:
  cityGmlPath:
  codelistsPath:
  schemasPath:
  schemaJson: !include ../../../config/schema.txt
  addNsprefixToFeatureTypes: true
  extractDmGeometryAsXmlFragment: false
  outputPath:
graphs:
  - !include ../../../graphs/xml_validator.yml
  - !include ../../../graphs/domain_of_definition_validator.yml
  - id: 7f86c5d5-b375-4190-ab93-001e9a099d1e
    name: entry_point
    nodes:
      - id: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        name: FeatureCreator
        type: action
        action: FeatureCreator
        with:
          creator: |
            [
              #{
                cityGmlPath: env.get("cityGmlPath")
              },
            ]

      - id: 725d0323-6a27-4154-acb4-9e6bff200a84
        name: FilePathExtractor
        type: action
        action: FilePathExtractor
        with:
          sourceDataset: |
            env.get("__value")["path"]
          extractArchive: true

      - id: 8510992d-2546-4e89-a09b-f31ff435bbb7
        name: FeatureFilterByGml
        type: action
        action: FeatureFilter
        with:
          conditions:
            - expr: |
                env.get("__value").extension == "gml"
              outputPort: default

      - id: 5e786419-7657-4694-b947-5c851d9fb95c
        name: FeatureCounterIndex
        type: action
        action: FeatureCounter
        with:
          countStart: 1
          outputAttribute: index

      - id: 1acc6aea-dcfb-4b5e-b2d6-38cc3b6848ac
        name: FilePropertyExtractor
        type: action
        action: FilePropertyExtractor
        with:
          filePathAttribute: path

      - id: b16c4701-3b21-48f3-8b09-cf2fc6a51f1e
        name: PLATEAU3.UDXFolderExtractor
        type: action
        action: PLATEAU3.UDXFolderExtractor
        with:
          cityGmlPath: |
            env.get("__value").path

      - id: f2d222e7-fc54-4bf8-b066-515fe1cfe328
        name: PLATEAU3.XMLValidator
        type: subGraph
        subGraphId: 2c753ffc-cc90-4f4a-b5ee-f5d7853dbac6

      - id: 993965e1-2bef-45e5-8afa-33efa633064e
        name: AttributeManager01
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: L01Errors
              method: create
              value: |
                if env.get("__value").status == "NOT_WELL_FORMED" {
                  env.get("__value").xmlError.len
                } else {
                  0
                }
            - attribute: L02Errors
              method: create
              value: |
                if env.get("__value").status == "INVALID" {
                  env.get("__value").xmlError.len
                } else {
                  0
                }

      - id: d77027e9-535e-4a03-8ddd-dc5973e9b25a
        name: FeatureFilterByXmlChecker
        type: action
        action: FeatureFilter
        with:
          conditions:
            - expr: |
                env.get("__value").status == "VALID"
              outputPort: default

      - id: 2b51486a-7258-42a6-ac9d-41a4f9a48624
        name: PLATEAU3.DomainOfDefinitionValidator
        type: subGraph
        subGraphId: b7396083-17d0-47dd-be86-83caf6c5ac63

      - id: 67a54b1b-4e3c-4bd2-99a3-81a379187c09
        name: FeatureMerger01
        type: action
        action: FeatureMerger
        with:
          requestorAttributeValue: |
            env.get("__value").index.to_string()
          supplierAttributeValue: |
            env.get("__value").index.to_string()

      - id: 1c6330bf-218d-40c5-b0c9-fb20ab70e9da
        name: FeatureMerger02
        type: action
        action: FeatureMerger
        with:
          requestorAttributeValue: |
            env.get("__value").index.to_string()
          supplierAttributeValue: |
            env.get("__value").index.to_string()

      - id: e7c8f92b-11cd-474b-971f-fb23cc5a741a
        name: AttributeMapper
        type: action
        action: AttributeMapper
        with:
          mappers:
            - attribute: Index
              expr: |
                env.get("__value").index
            - attribute: Folder
              expr: |
                env.get("__value").udxDirs
            - attribute: Filename
              expr: |
                file::extract_filename(env.get("__value").cityGmlPath)
            - attribute: "サイズ[KB]"
              expr: |
                round(env.get("__value").fileSize / 1024)
            - attribute: "1GB以下"
              expr: |
                if env.get("__value").fileSize / 1024 / 1024 / 1024 <= 1 {
                  "OK"
                } else {
                  "Over"
                }
            - attribute: "XML検証結果"
              expr: |
                env.get("__value").status
            - attribute: "L01エラー"
              expr: |
                env.get("__value").L01Errors ?? 0
            - attribute: "L02エラー"
              expr: |
                env.get("__value").L02Errors ?? 0
            - attribute: "L03エラー"
              expr: |
                env.get("__value").invalidFeatureTypesNum ?? 0
            - attribute: "L03エラー詳細"
              expr: |
                env.get("__value").invalidFeatureTypesDetail
            - attribute: "L04エラー"
              expr: |
                env.get("__value").inCorrectCodeValue ?? 0
            - attribute: "不正なcodeSpace数"
              expr: |
                env.get("__value").inCorrectCodeSpace ?? 0
            - attribute: "L05CRS識別子"
              expr: |
                if env.get("__value").isCorrectSrsName {
                  "Ok"
                } else {
                  "Wrong"
                }
            - attribute: "不正なCRS識別子"
              expr: |
                if env.get("__value").isCorrectSrsName {
                  ""
                } else {
                  env.get("__value").srsName
                }
            - attribute: "L06エラー"
              expr: |
                env.get("__value").inCorrectExtents ?? 0
            - attribute: "T03エラー"
              expr: |
                env.get("__value").xlinkInvalidObjectType ?? 0
            - attribute: "xlink参照先なし"
              expr: |
                env.get("__value").xlinkHasNoReference ?? 0
            - attribute: "gml:id重複"
              expr: |
                env.get("__value").gmlIdNotUnique ?? 0
            - attribute: "gml:id書式不正"
              expr: |
                env.get("__value").gmlIdNotWellformed ?? 0
            - attribute: "L-frn-01エラー"
              expr: |
                env.get("__value").invalidLodXGeometry ?? 0
            - attribute: "補足"
              expr: |
                env.get("__value").miscellaneous ?? ""

      - id: 94e4f345-c22d-4dc0-b3e0-6e914172e2fa
        name: FileWriterTsv
        type: action
        action: CsvWriter
        with:
          format: tsv
          output: |
            file::join_path(env.get("outputPath"), "01_共通.tsv")

      - id: 3b6f77dc-fc94-4610-bec8-3b1cd2789f3d
        name: StatisticsCalculator
        type: action
        action: StatisticsCalculator
        with:
          calculations:
            - newAttribute: "L01エラー"
              expr: |
                env.get("__value")["L01エラー"] ?? 0

            - newAttribute: "L02エラー"
              expr: |
                env.get("__value")["L02エラー"] ?? 0

            - newAttribute: "L04エラー"
              expr: |
                env.get("__value")["L04エラー"] ?? 0

            - newAttribute: "不正なcodeSpace数"
              expr: |
                env.get("__value")["不正なcodeSpace数"] ?? 0

            - newAttribute: "L06エラー"
              expr: |
                env.get("__value")["L06エラー"] ?? 0

            - newAttribute: "T03エラー"
              expr: |
                env.get("__value")["T03エラー"] ?? 0

            - newAttribute: "xlink参照先なし"
              expr: |
                env.get("__value")["xlink参照先なし"] ?? 0

            - newAttribute: "gml:id重複"
              expr: |
                env.get("__value")["gml:id重複"] ?? 0

            - newAttribute: "gml:id書式不正"
              expr: |
                env.get("__value")["gml:id書式不正"] ?? 0

            - newAttribute: "L-frn-01エラー"
              expr: |
                env.get("__value")["L-frn-01エラー"] ?? 0

      - id: b1d1c5d0-12a1-46d6-ac35-803f3eb22d63
        name: FileWriterJson
        type: action
        action: JsonWriter
        with:
          converter: |
            if env.get("__features").is_empty() {
              []
            } else {
              let result = [];
              let feature = env.get("__features")[0];
              for key in feature.keys() {
                result.push(#{
                  name: key,
                  count: feature[key],
                });
              }
              result
            }
          output: |
            file::join_path(env.get("outputPath"), "summary_common.json")

    edges:
      - id: 7c5a60ec-66cb-4ee0-9793-88c1f57b495c
        from: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        to: 725d0323-6a27-4154-acb4-9e6bff200a84
        fromPort: default
        toPort: default
      - id: c064cf52-705f-443a-b2de-6795266c540d
        from: 725d0323-6a27-4154-acb4-9e6bff200a84
        to: 8510992d-2546-4e89-a09b-f31ff435bbb7
        fromPort: default
        toPort: default
      - id: f23b1f56-c5d8-4311-9239-6dd205b538ab
        from: 8510992d-2546-4e89-a09b-f31ff435bbb7
        to: 5e786419-7657-4694-b947-5c851d9fb95c
        fromPort: default
        toPort: default
      - id: 7436b0a3-a658-49f6-a576-5b45abb2bd25
        from: 5e786419-7657-4694-b947-5c851d9fb95c
        to: b16c4701-3b21-48f3-8b09-cf2fc6a51f1e
        fromPort: default
        toPort: default
      - id: 3e3497c2-7810-456f-8334-89649f561771
        from: b16c4701-3b21-48f3-8b09-cf2fc6a51f1e
        to: f2d222e7-fc54-4bf8-b066-515fe1cfe328
        fromPort: default
        toPort: default
      - id: 9f855529-bc8b-46e3-a679-0b2c13d06092
        from: f2d222e7-fc54-4bf8-b066-515fe1cfe328
        to: d77027e9-535e-4a03-8ddd-dc5973e9b25a
        fromPort: summary
        toPort: default
      - id: 833a0183-1795-491e-95d7-033d7512b070
        from: d77027e9-535e-4a03-8ddd-dc5973e9b25a
        to: 2b51486a-7258-42a6-ac9d-41a4f9a48624
        fromPort: default
        toPort: default
      - id: d44adfb3-082e-4e31-8e27-ac3a4f36303c
        from: f2d222e7-fc54-4bf8-b066-515fe1cfe328
        to: 993965e1-2bef-45e5-8afa-33efa633064e
        fromPort: summary
        toPort: default
      - id: 55f394c4-4f62-4feb-a86e-219c4c1fa52e
        from: 2b51486a-7258-42a6-ac9d-41a4f9a48624
        to: 67a54b1b-4e3c-4bd2-99a3-81a379187c09
        fromPort: summary
        toPort: requestor
      - id: 79d3353a-244e-4bb7-b44b-c1d3957d8e04
        from: 993965e1-2bef-45e5-8afa-33efa633064e
        to: 67a54b1b-4e3c-4bd2-99a3-81a379187c09
        fromPort: default
        toPort: supplier
      - id: 7e83522e-5dd2-46cc-881e-e08a99935050
        from: 67a54b1b-4e3c-4bd2-99a3-81a379187c09
        to: 1c6330bf-218d-40c5-b0c9-fb20ab70e9da
        fromPort: merged
        toPort: supplier
      - id: c1834039-8ea9-4b13-8921-84642e1ceda3
        from: 5e786419-7657-4694-b947-5c851d9fb95c
        to: 1acc6aea-dcfb-4b5e-b2d6-38cc3b6848ac
        fromPort: default
        toPort: default
      - id: 037c34a3-f09c-4079-b6ef-84a73c4366ef
        from: 1acc6aea-dcfb-4b5e-b2d6-38cc3b6848ac
        to: 1c6330bf-218d-40c5-b0c9-fb20ab70e9da
        fromPort: default
        toPort: requestor
      - id: 5279e383-1527-4c79-8384-5a0560afd54f
        from: 1c6330bf-218d-40c5-b0c9-fb20ab70e9da
        to: e7c8f92b-11cd-474b-971f-fb23cc5a741a
        fromPort: merged
        toPort: default
      - id: ccd43557-e876-4d10-8a22-3dd2b061b574
        from: e7c8f92b-11cd-474b-971f-fb23cc5a741a
        to: 94e4f345-c22d-4dc0-b3e0-6e914172e2fa
        fromPort: default
        toPort: default
      - id: c10aebe0-0f84-44f4-862e-97bd08290729
        from: e7c8f92b-11cd-474b-971f-fb23cc5a741a
        to: 3b6f77dc-fc94-4610-bec8-3b1cd2789f3d
        fromPort: default
        toPort: default
      - id: 2716f9db-ebde-4777-b9ee-8550578840af
        from: 3b6f77dc-fc94-4610-bec8-3b1cd2789f3d
        to: b1d1c5d0-12a1-46d6-ac35-803f3eb22d63
        fromPort: default
        toPort: default
