# yaml-language-server: $schema=https://raw.githubusercontent.com/reearth/reearth-flow/main/engine/schema/workflow.json
id: cd93ce74-eff8-479c-abec-f8a1bc24cbda
name: "PLATEAU4-DataConvert-05-fld-workflow"
entryGraphId: 6f9f1383-8a50-4a22-b815-5d06a9f9398a
with:
  cityGmlPath:
  cityCode:
  codelistsPath:
  schemasPath:
  codelists:
  schemas:
  targetPackages:
    - fld
    - tnm
    - htd
    - ifld
    - rfld
  workerArtifactPath:
graphs:
  - !include ../../../../graphs/plateau4/folder_and_file_path_reader.yml
  - id: 6f9f1383-8a50-4a22-b815-5d06a9f9398a
    name: entry_point
    nodes:
      - id: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        name: FeatureCreator
        type: action
        action: FeatureCreator
        with:
          creator: |
            [
              #{
                cityGmlPath: env.get("cityGmlPath"),
                cityCode: env.get("cityCode") ?? file::extract_filename(env.get("cityGmlPath"))[0..5],
                codelists: env.get("codelistsPath") ?? env.get("codelists"),
                schemas: env.get("schemasPath") ?? env.get("schemas"),
              },
            ]

      - id: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        name: FolderAndFilePathReader
        type: subGraph
        subGraphId: c6863b71-953b-4d15-af56-396fc93fc617

      - id: ded2e272-e05c-4918-86b3-aa9f763da6e6
        name: FeatureReaderByCityGml
        type: action
        action: FeatureCityGmlReader
        with:
          codelistsPath: env.get("__value").codelists
          flatten: true
          dataset: |
            env.get("__value")["path"]

      - id: e2441531-649a-4dcd-916f-ac59f7d56de3
        name: AttributeManagerPreFlattener
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: meshcode
              method: create
              value: |
                let file = file::extract_filename(env.get("__value")["path"]);
                file.split("_")[0]
            - attribute: gml_id
              method: create
              value: |
                env.get("__feature_id") ?? env.get("__value")["gmlId"]
            - attribute: feature_type
              method: create
              value: env.get("__value")["featureType"] ?? env.get("__value")["gmlName"]
            - attribute: codelists
              method: remove
            - attribute: schemas
              method: remove

      - id: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        name: AttributeFlattener
        type: action
        action: PLATEAU4.AttributeFlattener

      - id: 20cb127d-fc8a-4921-8ab6-0f88438eb9e0
        name: AttributeManager
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: featureId
              method: remove
            - attribute: featureParentId
              method: remove
            - attribute: geometryName
              method: remove
            - attribute: cityCode
              method: rename
              value: city_code
            - attribute: cityName
              method: rename
              value: city_name
            - attribute: lod
              method: remove
            - attribute: gmlId
              method: remove
            - attribute: gmlPropertyName
              method: remove
            - attribute: fileIndex
              method: remove
            - attribute: root
              method: remove
            - attribute: cityGmlPath
              method: remove
            - attribute: admin
              method: remove
            - attribute: area
              method: remove
            - attribute: package
              method: rename
              value: __package
            - attribute: extension
              method: remove
            - attribute: dirRoot
              method: remove
            - attribute: gmlRootId
              method: remove
            - attribute: maxLod
              method: remove
            - attribute: dirSchemas
              method: remove
            - attribute: dirCodelists
              method: remove
            - attribute: path
              method: remove
            - attribute: name
              method: rename
              value: __name
            - attribute: udxDirs
              method: rename
              value: __udxDirs
            - attribute: featureType
              method: remove
            - attribute: gmlName
              method: remove

      - id: 8b05f9d4-1cb2-4071-a1da-c968431bc0ec
        name: VerticalReprojector
        type: action
        action: VerticalReprojector
        with:
          reprojectorType: jgd2011ToWgs84

      - id: b4862d31-4bb2-49b1-8f0d-6d58dd4cb385
        name: Cesium3DTilesWriterNoTexture
        type: action
        action: Cesium3DTilesWriter
        with:
          minZoom: 15
          maxZoom: 18
          attachTexture: false
          skipUnexposedAttributes: true
          output: |
            let udx_dirs = env.get("__value")["__udxDirs"];
            udx_dirs.replace("/", "_");
            file::join_path(env.get("workerArtifactPath"), udx_dirs + "_no_texture")
          # example __udxDirs: "fld/pref/oyabegawa_gandogawa"
          # example output: "${workerArtifactPath}/16202_takaoka-shi_city_2024_citygml_1_op_fld_pref_oyabegawa_gandogawa_3dtiles_l2_no_texture.zip"
          compressOutput: |
            let artifact = env.get("workerArtifactPath");
            let citygml = file::extract_filename_without_ext(env.get("cityGmlPath"));
            let parts = citygml.split("_op_");
            citygml = parts[0];
            let udx_dirs = env.get("__value")["__udxDirs"];
            udx_dirs.replace("/", "_");
            let name = file::extract_filename_without_ext(env.get("__value")["__name"]);
            let lod = name.split("_").pop();
            file::join_path(artifact, citygml + "_op_" + udx_dirs + "_3dtiles_" + lod + "_no_texture.zip")

    edges:
      - id: 5ebf24ab-1d98-49d5-8f58-eb7c18d27244
        from: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        to: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        fromPort: default
        toPort: default
      - id: 7b81f501-3f07-4cec-bf9b-9cefcebdf47d
        from: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        to: ded2e272-e05c-4918-86b3-aa9f763da6e6
        fromPort: default
        toPort: default
      - id: cf845867-6ffc-4b83-9fd5-e376a22470e2
        from: ded2e272-e05c-4918-86b3-aa9f763da6e6
        to: e2441531-649a-4dcd-916f-ac59f7d56de3
        fromPort: default
        toPort: default
      - id: 7e8f9a0b-1c2d-3e4f-5a6b-7c8d9e0f1a2b
        from: e2441531-649a-4dcd-916f-ac59f7d56de3
        to: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        fromPort: default
        toPort: default
      - id: ad52c3e6-68ff-4844-a7b2-d302fc0aef14
        from: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        to: 20cb127d-fc8a-4921-8ab6-0f88438eb9e0
        fromPort: default
        toPort: default
      - id: e862f11a-88a6-4c1b-a743-ba80253039df
        from: 20cb127d-fc8a-4921-8ab6-0f88438eb9e0
        to: 8b05f9d4-1cb2-4071-a1da-c968431bc0ec
        fromPort: default
        toPort: default
      - id: 92e83e72-2507-4a3e-8889-815fb6eeb68d
        from: 8b05f9d4-1cb2-4071-a1da-c968431bc0ec
        to: b4862d31-4bb2-49b1-8f0d-6d58dd4cb385
        fromPort: default
        toPort: default

