# yaml-language-server: $schema=https://raw.githubusercontent.com/reearth/reearth-flow/main/engine/schema/workflow.json
id: cd93ce74-eff8-479c-abec-f8a1bc24cbda
name: "PLATEAU4-DataConvert-05-fld-workflow"
entryGraphId: 6f9f1383-8a50-4a22-b815-5d06a9f9398a
with:
  cityGmlPath:
  cityCode:
  codelistsPath:
  schemasPath:
  codelists:
  schemas:
  targetPackages:
    - fld
    - tnm
    - htd
    - ifld
    - rfld
  workerArtifactPath:
graphs:
  - !include ../../../../graphs/plateau4/folder_and_file_path_reader.yml
  - id: 6f9f1383-8a50-4a22-b815-5d06a9f9398a
    name: entry_point
    nodes:
      - id: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        name: FeatureCreator
        type: action
        action: FeatureCreator
        with:
          creator: |
            [
              #{
                cityGmlPath: env.get("cityGmlPath"),
                cityCode: env.get("cityCode") ?? file::extract_filename(env.get("cityGmlPath"))[0..5],
                codelists: env.get("codelistsPath") ?? env.get("codelists"),
                schemas: env.get("schemasPath") ?? env.get("schemas"),
              },
            ]

      - id: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        name: FolderAndFilePathReader
        type: subGraph
        subGraphId: c6863b71-953b-4d15-af56-396fc93fc617

      - id: ded2e272-e05c-4918-86b3-aa9f763da6e6
        name: FeatureReaderByCityGml
        type: action
        action: FeatureCityGmlReader
        with:
          codelistsPath: env.get("__value").codelists
          flatten: true
          dataset: |
            env.get("__value")["path"]

      - id: e2441531-649a-4dcd-916f-ac59f7d56de3
        name: AttributeManagerPreFlattener
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: feature_type
              method: create
              value: env.get("__value")["featureType"] ?? env.get("__value")["gmlName"]
            - attribute: codelists
              method: remove
            - attribute: schemas
              method: remove

      - id: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        name: AttributeFlattener
        type: action
        action: PLATEAU4.AttributeFlattener

      - id: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        name: AttributeManagerRename
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: cityName
              method: rename
              value: city_name
            - attribute: cityCode
              method: rename
              value: city_code

      # Schema branch - defines tileset.json properties
      - id: 20cb127d-fc8a-4921-8ab6-0f88438eb9e0
        name: AttributeMapperSchema
        type: action
        action: AttributeMapper
        with:
          mappers:
            - attribute: city_code
              valueAttribute: city_code
            - attribute: city_name
              valueAttribute: city_name
            - attribute: feature_type
              valueAttribute: feature_type
            - attribute: attributes
              valueAttribute: attributes
            - attribute: gml:name
              valueAttribute: gml:name
            - attribute: core:creationDate
              valueAttribute: core:creationDate
            - attribute: wtr:class
              valueAttribute: wtr:class
            - attribute: wtr:function
              valueAttribute: wtr:function
            - attribute: uro:description
              valueAttribute: uro:description
            - attribute: uro:rank
              valueAttribute: uro:rank
            - attribute: uro:rank_code
              valueAttribute: uro:rank_code
            - attribute: uro:rankOrg
              valueAttribute: uro:rankOrg
            - attribute: uro:rankOrg_code
              valueAttribute: uro:rankOrg_code
            - attribute: uro:adminType
              valueAttribute: uro:adminType
            - attribute: uro:scale
              valueAttribute: uro:scale
            - attribute: uro:geometrySrcDescLod1
              valueAttribute: uro:geometrySrcDescLod1

      - id: 8b05f9d4-1cb2-4071-a1da-c968431bc0ec
        name: VerticalReprojector
        type: action
        action: VerticalReprojector
        with:
          reprojectorType: jgd2011ToWgs84

      - id: 3f7a8b2c-4d9e-5a1f-6b3c-7d8e9f0a1b2c
        name: FloodingAreaSurfaceGenerator
        type: action
        action: PLATEAU4.FloodingAreaSurfaceGenerator

      - id: b4862d31-4bb2-49b1-8f0d-6d58dd4cb385
        name: Cesium3DTilesWriterNoTexture
        type: action
        action: Cesium3DTilesWriter
        with:
          minZoom: 15
          maxZoom: 18
          attachTexture: false
          dracoCompression: false
          output: |
            let udx_dirs = env.get("__value")["udxDirs"];
            udx_dirs.replace("/", "_");
            file::join_path(env.get("workerArtifactPath"), udx_dirs + "_no_texture")
          # example udxDirs: "fld/pref/oyabegawa_gandogawa"
          # example output: "${workerArtifactPath}/16202_takaoka-shi_city_2024_citygml_1_op_fld_pref_oyabegawa_gandogawa_3dtiles_l2_no_texture.zip"
          compressOutput: |
            let artifact = env.get("workerArtifactPath");
            let citygml = file::extract_filename_without_ext(env.get("cityGmlPath"));
            let parts = citygml.split("_op_");
            let pkg = env.get("__value")["package"];
            citygml = parts[0];
            let udx_dirs = env.get("__value")["udxDirs"];
            udx_dirs.replace("/", "_");
            let scale = "";
            if pkg == "fld" {
              let file_name = file::extract_filename_without_ext(env.get("__value")["name"]);
              scale = "_" + file_name.split("_").pop();
            }
            file::join_path(artifact, citygml + "_op_" + udx_dirs + "_3dtiles" + scale + "_no_texture.zip")

      # Dictionary.json output branch
      - id: 739c7093-63e5-43b8-a1b1-1eeae82f3de1
        name: CreateDictionaryNameDict
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: dict_name
              method: create
              value: |
                let udx_dirs = env.get("__value")["udxDirs"];
                let parts = udx_dirs.split("/");
                let last_segment = parts[parts.len() - 1];
                let pkg = env.get("__value")["package"];
                if pkg == "fld" {
                  let name = file::extract_filename_without_ext(env.get("__value")["name"]);
                  let scale = name.split("_").pop();
                  last_segment + "_" + scale
                } else {
                  last_segment
                }

      - id: c24dbf9e-1741-4c61-99bc-618582b1e03b
        name: AttributeDuplicateFilterDict
        type: action
        action: AttributeDuplicateFilter
        with:
          filterBy:
            - package
            - dict_name

      - id: defb033b-e2aa-4ad1-a9ff-58d9cf6dea47
        name: JsonWriterDict
        type: action
        action: JsonWriter
        with:
          output: |
            file::join_path(env.get("workerArtifactPath"), "dictionary.json")
          converter: |
            let packages = #{};
            for feature in env.get("__features") {
              let pkg = feature["package"];
              if pkg == () { continue; }
              if packages[pkg] == () {
                packages[pkg] = [];
              }
              let item = #{
                name: feature.dict_name,
                description: feature["uro:description"],
              };
              if "uro:adminType" in feature {
                item.admin = feature["uro:adminType"];
              }
              let scale = feature["uro:scale"] ?? "";
              if scale.len() < 2 {
              } else if scale[1] == "1" {
                item.scale = "計画規模";
              } else if scale[1] == "2" {
                item.scale = "想定最大規模";
              }
              packages[pkg].push(item);
            }
            packages

    edges:
      - id: 5ebf24ab-1d98-49d5-8f58-eb7c18d27244
        from: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        to: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        fromPort: default
        toPort: default
      - id: 7b81f501-3f07-4cec-bf9b-9cefcebdf47d
        from: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        to: ded2e272-e05c-4918-86b3-aa9f763da6e6
        fromPort: default
        toPort: default
      - id: cf845867-6ffc-4b83-9fd5-e376a22470e2
        from: ded2e272-e05c-4918-86b3-aa9f763da6e6
        to: e2441531-649a-4dcd-916f-ac59f7d56de3
        fromPort: default
        toPort: default
      - id: 7e8f9a0b-1c2d-3e4f-5a6b-7c8d9e0f1a2b
        from: e2441531-649a-4dcd-916f-ac59f7d56de3
        to: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        fromPort: default
        toPort: default
      # AttributeFlattener → AttributeManagerRename
      - id: e862f11a-88a6-4c1b-a743-ba80253039df
        from: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        to: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        fromPort: default
        toPort: default
      # AttributeManagerRename → VerticalReprojector
      - id: f2e3d4c5-b6a7-8901-cdef-234567890abc
        from: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        to: 8b05f9d4-1cb2-4071-a1da-c968431bc0ec
        fromPort: default
        toPort: default
      # Schema branch: AttributeFlattener → AttributeMapperSchema
      - id: ad52c3e6-68ff-4844-a7b2-d302fc0aef14
        from: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        to: 20cb127d-fc8a-4921-8ab6-0f88438eb9e0
        fromPort: schema
        toPort: default
      - id: 92e83e72-2507-4a3e-8889-815fb6eeb68d
        from: 8b05f9d4-1cb2-4071-a1da-c968431bc0ec
        to: 3f7a8b2c-4d9e-5a1f-6b3c-7d8e9f0a1b2c
        fromPort: default
        toPort: default
      - id: 4c5d6e7f-8a9b-0c1d-2e3f-4a5b6c7d8e9f
        from: 3f7a8b2c-4d9e-5a1f-6b3c-7d8e9f0a1b2c
        to: b4862d31-4bb2-49b1-8f0d-6d58dd4cb385
        fromPort: default
        toPort: default
      # Schema branch: AttributeMapperSchema → Cesium3DTilesWriter (schema port)
      - id: f1e2d3c4-b5a6-9788-0fed-cba987654321
        from: 20cb127d-fc8a-4921-8ab6-0f88438eb9e0
        to: b4862d31-4bb2-49b1-8f0d-6d58dd4cb385
        fromPort: default
        toPort: schema
      # Dictionary branch edges (from AttributeFlattener)
      - id: 48893ceb-2d37-4ca2-b5c0-184ea4128409
        from: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        to: 739c7093-63e5-43b8-a1b1-1eeae82f3de1
        fromPort: default
        toPort: default
      - id: 1e5c26d5-2082-4fed-9890-89fb517ef184
        from: 739c7093-63e5-43b8-a1b1-1eeae82f3de1
        to: c24dbf9e-1741-4c61-99bc-618582b1e03b
        fromPort: default
        toPort: default
      - id: db2b57d8-b2e2-4094-aa82-c76b555fdb60
        from: c24dbf9e-1741-4c61-99bc-618582b1e03b
        to: defb033b-e2aa-4ad1-a9ff-58d9cf6dea47
        fromPort: default
        toPort: default

