id: a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6e
name: "PLATEAU4-quality-check-11-wtr-workflow"
entryGraphId: b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7f
with:
  cityGmlPath:
  schemasPath:
  schemas:
  codelistsPath:
  codelists:
  workerArtifactPath:
  prcs:
  objectListsPath:
  objectLists:
graphs:
  # Include common graphs
  - !include ../../../../graphs/plateau4/xml_validator.yml
  - !include ../../../../graphs/plateau4/domain_of_definition_validator.yml
  - !include ../../../../graphs/plateau4/quality-check/01-01-common.yml
  - !include ../../../../graphs/plateau4/quality-check/01-02-common.yml
  # Entry point graph
  - id: b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7f
    name: entry_point
    nodes:
      - id: c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f
        name: FeatureCreator
        type: action
        action: FeatureCreator
        with:
          creator: |
            [
              #{
                cityGmlPath: env.get("cityGmlPath"),
                cityCode: env.get("cityCode") ?? file::extract_filename(env.get("cityGmlPath"))[0..5],
                baseCityCode: env.get("cityCode") ?? file::extract_filename(env.get("cityGmlPath"))[0..5],
                schemas: env.get("schemasPath") ?? env.get("schemas"),
                codelists: env.get("codelistsPath") ?? env.get("codelists"),
                objectListsPath: env.get("objectListsPath") ?? env.get("objectLists"),
              },
            ]

      - id: d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a
        name: DirectoryDecompressor
        type: action
        action: DirectoryDecompressor
        with:
          archiveAttributes:
            - codelists
            - schemas
          findDeepestSingleFolder: true

      # Common quality check subgraph call
      - id: d1e2f3a4-b5c6-7d8e-9f0a-1b2c3d4e5f6a
        name: CommonQualityCheck-01-01
        type: subGraph
        subGraphId: 5db64758-df36-486d-86bd-437b72fd9fc8

      - id: e2f3a4b5-c6d7-8e9f-0a1b-2c3d4e5f6a7b
        name: CommonQualityCheck-01-02
        type: subGraph
        subGraphId: b7a4c316-112e-4473-bd25-4c158db4e561

      # ZipFileWriter - Bundle all output files
      - id: d0e1f2a3-b4c5-6d7e-8f9a-0b1c2d3e4f5a
        name: ZipFileWriter
        type: action
        action: ZipFileWriter
        with:
          output: |
            let filename = file::extract_filename_without_ext(env.get("cityGmlPath")) + "_qc_result.zip";
            let dirname = env.get("workerArtifactPath");
            file::join_path(dirname, filename)

      # Statistics Calculator for total errors
      - id: a7b8c9d0-e1f2-3a4b-5c6d-7e8f9a0b1c2d
        name: StatisticsCalculatorTotalErrors
        type: action
        action: StatisticsCalculator
        with:
          calculations:
            - newAttribute: totalErrorCount
              expr: |
                env.get("__value")["totalErrorCount"] ?? 0

      # Filter for no errors
      - id: b8c9d0e1-f2a3-4b5c-6d7e-8f9a0b1c2d3e
        name: FeatureFilterNoErrors
        type: action
        action: FeatureFilter
        with:
          conditions:
            - expr: |
                env.get("__value")["totalErrorCount"] == 0
              outputPort: default

      # Write qc_result_ok file
      - id: c9d0e1f2-a3b4-5c6d-7e8f-9a0b1c2d3e4f
        name: JsonWriterQcResultOk
        type: action
        action: JsonWriter
        with:
          converter: '[]'
          output: |
            let filename = file::extract_filename_without_ext(env.get("cityGmlPath")) + "_qc_result_ok";
            let dirname = env.get("workerArtifactPath");
            file::join_path(dirname, filename)

    edges:
      # FeatureCreator → DirectoryDecompressor
      - id: e1f2a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6c
        from: c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f
        to: d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a
        fromPort: default
        toPort: default

      # DirectoryDecompressor → CommonQualityCheck-01-01
      - id: f2a3b4c5-d6e7-8f9a-0b1c-2d3e4f5a6b7d
        from: d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a
        to: d1e2f3a4-b5c6-7d8e-9f0a-1b2c3d4e5f6a
        fromPort: default
        toPort: default

      # DirectoryDecompressor → CommonQualityCheck-01-02
      - id: a3b4c5d6-e7f8-9a0b-1c2d-3e4f5a6b7c8e
        from: d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a
        to: e2f3a4b5-c6d7-8e9f-0a1b-2c3d4e5f6a7b
        fromPort: default
        toPort: default

      # Common subgraph outputs to ZipFileWriter (using fromPort: default)
      - id: d2e3f4a5-b6c7-8d9e-0f1a-2b3c4d5e6f7a
        from: d1e2f3a4-b5c6-7d8e-9f0a-1b2c3d4e5f6a
        to: d0e1f2a3-b4c5-6d7e-8f9a-0b1c2d3e4f5a
        fromPort: default
        toPort: default

      - id: e3f4a5b6-c7d8-9e0f-1a2b-3c4d5e6f7a8b
        from: e2f3a4b5-c6d7-8e9f-0a1b-2c3d4e5f6a7b
        to: d0e1f2a3-b4c5-6d7e-8f9a-0b1c2d3e4f5a
        fromPort: default
        toPort: default

      # For qc_result_ok: summaryOutput → StatisticsCalculator → Filter → JsonWriter
      - id: f3a4b5c6-d7e8-9f0a-1b2c-3d4e5f6a7b8c
        from: d1e2f3a4-b5c6-7d8e-9f0a-1b2c3d4e5f6a
        to: a7b8c9d0-e1f2-3a4b-5c6d-7e8f9a0b1c2d
        fromPort: summaryOutput
        toPort: default

      - id: a4b5c6d7-e8f9-0a1b-2c3d-4e5f6a7b8c9d
        from: e2f3a4b5-c6d7-8e9f-0a1b-2c3d4e5f6a7b
        to: a7b8c9d0-e1f2-3a4b-5c6d-7e8f9a0b1c2d
        fromPort: summaryOutput
        toPort: default

      - id: f8a9b0c1-d2e3-4f5a-6b7c-8d9e0f1a2b3d
        from: a7b8c9d0-e1f2-3a4b-5c6d-7e8f9a0b1c2d
        to: b8c9d0e1-f2a3-4b5c-6d7e-8f9a0b1c2d3e
        fromPort: default
        toPort: default

      - id: a9b0c1d2-e3f4-5a6b-7c8d-9e0f1a2b3c4e
        from: b8c9d0e1-f2a3-4b5c-6d7e-8f9a0b1c2d3e
        to: c9d0e1f2-a3b4-5c6d-7e8f-9a0b1c2d3e4f
        fromPort: default
        toPort: default
