import { FacingLog, FacingLogLevel } from "@flow/types";

export const logData: FacingLog[] = [
  {
    jobId: "1",
    level: FacingLogLevel.Info,
    message: "Job started",
    timestamp: "2021-09-01T00:00:00Z",
    nodeId: "node-1",
    nodeName: "Node 1",
  },
  {
    jobId: "1",
    level: FacingLogLevel.Info,
    message: "Job started",
    timestamp: "2021-09-01T00:00:00Z",
    nodeId: "node-1",
    nodeName: "Node 1",
  },
  {
    jobId: "1",
    level: FacingLogLevel.Info,
    message: "Job started",
    timestamp: "2021-09-01T00:00:00Z",
    nodeId: "node-1",
    nodeName: "Node 1",
  },
  {
    jobId: "1",
    level: FacingLogLevel.Info,
    message: "Job started",
    timestamp: "2021-09-01T00:00:00Z",
    nodeId: "node-1",
    nodeName: "Node 1",
  },
  {
    jobId: "1",
    level: FacingLogLevel.Info,
    message: "Job started",
    timestamp: "2021-09-01T00:00:00Z",
    nodeId: "node-1",
    nodeName: "Node 1",
  },
  {
    jobId: "1",
    level: FacingLogLevel.Info,
    message: "Job started",
    timestamp: "2021-09-01T00:00:00Z",
    nodeId: "node-1",
    nodeName: "Node 1",
  },
  {
    jobId: "1",
    level: FacingLogLevel.Info,
    message: "Job started",
    timestamp: "2021-09-01T00:00:00Z",
    nodeId: "node-1",
    nodeName: "Node 1",
  },
];
