#!/usr/bin/env bash
#
# Refresh the embedded PROJ grid set from the PROJ-data CDN.
#
# Downloads every grid listed in GRIDS below, verifies it against the SHA-256
# the CDN publishes in files.geojson, and regenerates MANIFEST.tsv and
# NOTICE.md. Run it from anywhere; it writes into its own directory.
#
# Adding a grid: append its CDN file name to GRIDS and re-run. Removing one:
# delete the line, re-run, and delete the stale .tif by hand.

set -euo pipefail

# Pinned PROJ-data release the licence table is read from. The CDN itself is a
# rolling mirror, so the grids are pinned by the SHA-256 in MANIFEST.tsv rather
# than by this tag. Bump both together.
PROJ_DATA_VERSION="1.24.0"

CDN="https://cdn.proj.org"
LICENSES_URL="https://raw.githubusercontent.com/OSGeo/PROJ-data/refs/tags/${PROJ_DATA_VERSION}/copyright_and_licenses.csv"

# The embedded set: current-generation geoid models, one per national vertical
# datum, plus the global EGM96 fallback. Every other grid stays external, see
# ../../../dev-docs/proj-grids.md.
GRIDS=(
  # Global
  us_nga_egm96_15.tif
  # Japan
  jp_gsi_gsigeo2011.tif
  jp_gsi_jpgeo2024.tif
  # Europe
  at_bev_GV_Hoehengrid_plus_Geoid_V2.tif
  be_ign_hBG18.tif
  ch_swisstopo_chgeo2004_ETRS89_LHN95.tif
  ch_swisstopo_chgeo2004_ETRS89_LN02.tif
  cz_cuzk_CR-2005.tif
  de_bkg_gcg2016.tif
  dk_sdfi_dvr90_2023.tif
  es_ign_egm08-rednap-canarias.tif
  es_ign_egm08-rednap.tif
  fi_nls_fin2023n2000.tif
  fr_ign_RAF20.tif
  hu_bme_geoid2014.tif
  is_lmi_Icegeoid_ISN2016.tif
  lv_lgia_lv14.tif
  nl_nsgi_nlgeo2018.tif
  no_kv_HREF2018B_NN2000_EUREF89.tif
  pl_gugik_geoid2021-PL-EVRF2007-NH.tif
  pt_dgt_GeodPT08.tif
  se_lantmateriet_SWEN17_RH2000.tif
  si_gurs_SLO-VRP2016-Koper.tif
  sk_gku_Slovakia_ETRS89h_to_EVRF2007.tif
  uk_os_OSGM15_Belfast.tif
  uk_os_OSGM15_GB.tif
  uk_os_OSGM15_Malin.tif
)

cd "$(dirname "$0")"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

echo "fetching catalogue..."
curl -sSfL --retry 3 -o "$work/files.geojson" "$CDN/files.geojson"
curl -sSfL --retry 3 -o "$work/licenses.csv" "$LICENSES_URL"

for name in "${GRIDS[@]}"; do
  if [ ! -f "$name" ]; then
    echo "downloading $name"
    curl -sSfL --retry 3 -o "$name" "$CDN/$name"
  fi
done

echo "verifying and writing MANIFEST.tsv / NOTICE.md..."
GRIDS="${GRIDS[*]}" PROJ_DATA_VERSION="$PROJ_DATA_VERSION" WORK="$work" python3 - <<'PY'
import csv, hashlib, json, os, sys

names = os.environ["GRIDS"].split()
work = os.environ["WORK"]
version = os.environ["PROJ_DATA_VERSION"]

catalogue = {
    f["properties"]["name"]: f["properties"]
    for f in json.load(open(f"{work}/files.geojson"))["features"]
}
licenses = {}
with open(f"{work}/licenses.csv", newline="") as fh:
    for row in csv.DictReader(fh):
        licenses[os.path.basename(row["filename"] or "")] = (
            (row["copyright"] or "").strip(),
            (row["license"] or "").strip(),
        )

rows, failed = [], []
for name in names:
    meta = catalogue.get(name)
    if meta is None:
        failed.append(f"{name}: not in the CDN catalogue")
        continue
    digest = hashlib.sha256(open(name, "rb").read()).hexdigest()
    if digest != meta["sha256sum"]:
        failed.append(f"{name}: sha256 mismatch (delete it and re-run)")
        continue
    holder, license = licenses.get(name, ("", ""))
    if not license:
        failed.append(f"{name}: no licence recorded in PROJ-data {version}")
        continue
    rows.append(
        {
            "name": name,
            "size": str(meta["file_size"]),
            "sha256": digest,
            "country": meta.get("source_country", ""),
            "source": holder or meta.get("source", ""),
            "source_url": meta.get("source_url", ""),
            "license": license,
        }
    )

if failed:
    sys.exit("\n".join(failed))

with open("MANIFEST.tsv", "w") as fh:
    fh.write(f"# PROJ-data {version}\tgenerated by update.sh\n")
    fh.write("name\tsize\tsha256\tcountry\tsource\tsource_url\tlicense\n")
    for r in sorted(rows, key=lambda r: r["name"]):
        fh.write("\t".join(r[k] for k in ("name", "size", "sha256", "country", "source", "source_url", "license")) + "\n")

total = sum(int(r["size"]) for r in rows)
with open("NOTICE.md", "w") as fh:
    fh.write("# Third-party geodetic grids\n\n")
    fh.write(
        f"This product embeds {len(rows)} geodetic grid files "
        f"({total / 1048576:.1f} MiB) taken from the PROJ-data {version} "
        "distribution (<https://github.com/OSGeo/PROJ-data>). Each is redistributed "
        "under the licence its publisher applied to it, reproduced below. "
        "Generated by `update.sh`; do not edit by hand.\n\n"
    )
    fh.write(
        "The Japanese grids are used with the permission of the Geospatial "
        "Information Authority of Japan recorded in the PROJ-data source "
        "distribution: 測量法に基づく国土地理院長承認(使用)R 2JHs 501.\n\n"
    )
    fh.write("| Grid | Publisher | Country | Licence |\n|---|---|---|---|\n")
    for r in sorted(rows, key=lambda r: (r["country"], r["name"])):
        pub = f"[{r['source']}]({r['source_url']})" if r["source_url"] else r["source"]
        fh.write(f"| `{r['name']}` | {pub} | {r['country']} | {r['license']} |\n")

print(f"{len(rows)} grids, {total / 1048576:.1f} MiB")
PY
