#!/usr/bin/env bash
#
# Refresh the vendored geodetic grids from the PROJ-data CDN.
#
# MANIFEST.tsv drives this: its first column names the grids to vendor, and its
# header pins the PROJ-data release the licence table is read from. Every grid
# named there is downloaded if absent and verified against the SHA-256 the CDN
# publishes, then the manifest is rewritten with the metadata read back.
#
# Adding a grid: append a line holding just its CDN file name and re-run.
# Removing one: delete its line, re-run, and delete the stale .tif.
# Either way, run `cargo make proj-grids-notice` afterwards to update NOTICE.md.
#
# The CDN is a rolling mirror, so a grid already on disk is left alone and
# verified against what the CDN publishes now. A mismatch means upstream
# republished it: delete the file and re-run to take the new bytes.

set -euo pipefail

cd "$(dirname "$0")"

MANIFEST=MANIFEST.tsv

PROJ_DATA_VERSION=$(sed -n '1s/^# PROJ-data \([^[:space:]]*\).*/\1/p' "$MANIFEST")
if [ -z "$PROJ_DATA_VERSION" ]; then
  echo "$MANIFEST: first line is not a '# PROJ-data <version>' header"
  exit 1
fi
mapfile -t GRIDS < <(tail -n +3 "$MANIFEST" | cut -f1 | sed '/^[[:space:]]*$/d')
if [ "${#GRIDS[@]}" -eq 0 ]; then
  echo "$MANIFEST lists no grids"
  exit 1
fi

CDN="https://cdn.proj.org"
LICENSES_URL="https://raw.githubusercontent.com/OSGeo/PROJ-data/refs/tags/${PROJ_DATA_VERSION}/copyright_and_licenses.csv"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

echo "fetching catalogue for PROJ-data ${PROJ_DATA_VERSION}..."
curl -sSfL --retry 3 -o "$work/files.geojson" "$CDN/files.geojson"
curl -sSfL --retry 3 -o "$work/licenses.csv" "$LICENSES_URL"

for name in "${GRIDS[@]}"; do
  if [ ! -f "$name" ]; then
    echo "downloading $name"
    curl -sSfL --retry 3 -o "$name" "$CDN/$name"
  fi
done

echo "verifying and writing $MANIFEST..."
GRIDS="${GRIDS[*]}" PROJ_DATA_VERSION="$PROJ_DATA_VERSION" WORK="$work" python3 - <<'PY'
import csv, hashlib, json, os, sys

names = os.environ["GRIDS"].split()
work = os.environ["WORK"]
version = os.environ["PROJ_DATA_VERSION"]

catalogue = {
    f["properties"]["name"]: f["properties"]
    for f in json.load(open(f"{work}/files.geojson"))["features"]
}
licenses = {}
with open(f"{work}/licenses.csv", newline="") as fh:
    for row in csv.DictReader(fh):
        licenses[os.path.basename(row["filename"] or "")] = (
            (row["copyright"] or "").strip(),
            (row["license"] or "").strip(),
        )

rows, failed = [], []
for name in names:
    meta = catalogue.get(name)
    if meta is None:
        failed.append(f"{name}: not in the CDN catalogue")
        continue
    digest = hashlib.sha256(open(name, "rb").read()).hexdigest()
    if digest != meta["sha256sum"]:
        failed.append(f"{name}: sha256 mismatch (delete it and re-run)")
        continue
    holder, license = licenses.get(name, ("", ""))
    if not license:
        failed.append(f"{name}: no licence recorded in PROJ-data {version}")
        continue
    rows.append(
        {
            "name": name,
            "size": str(meta["file_size"]),
            "sha256": digest,
            "country": meta.get("source_country", ""),
            "source": holder or meta.get("source", ""),
            "source_url": meta.get("source_url", ""),
            "license": license,
        }
    )

if failed:
    sys.exit("\n".join(failed))

with open("MANIFEST.tsv", "w") as fh:
    fh.write(f"# PROJ-data {version}\tgenerated by update.sh\n")
    fh.write("name\tsize\tsha256\tcountry\tsource\tsource_url\tlicense\n")
    for r in sorted(rows, key=lambda r: r["name"]):
        fh.write("\t".join(r[k] for k in ("name", "size", "sha256", "country", "source", "source_url", "license")) + "\n")

total = sum(int(r["size"]) for r in rows)
print(f"{len(rows)} grids, {total / 1048576:.1f} MiB")
PY
