[package]
description = "Re:Earth Flow runtime"
name = "reearth-flow-runtime"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
reearth-flow-action-log.workspace = true
reearth-flow-common.workspace = true
reearth-flow-eval-expr.workspace = true
reearth-flow-state.workspace = true
reearth-flow-storage.workspace = true
reearth-flow-types.workspace = true

async-stream = "0.3.5"
async-trait.workspace = true
chrono.workspace = true
crossbeam.workspace = true
futures.workspace = true
futures-util.workspace = true
nutype.workspace = true
once_cell.workspace = true
opentelemetry.workspace = true
parking_lot.workspace = true
petgraph.workspace = true
rayon.workspace = true
regex.workspace = true
rmp-serde = "1.3.0"
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[dev-dependencies]
bytes.workspace = true
pretty_assertions.workspace = true
