import { type AutocompleteSuggestion } from "./constants";

export const FLOWEXPR_KEYWORDS = [
  "if",
  "else",
  "while",
  "for",
  "in",
  "not",
  "and",
  "or",
  "true",
  "false",
  "null",
];

export const FLOWEXPR_BUILTIN_FUNCTIONS = [
  "str",
  "int",
  "float",
  "bool",
  "list",
  "map",
  "Url",
  "value",
  "env",
  "print",
];

export const FLOWEXPR_MATH_NAMESPACE = "math";

export const FLOWEXPR_MATH_FUNCTIONS = [
  "sin",
  "cos",
  "tan",
  "asin",
  "acos",
  "atan",
  "atan2",
  "sinh",
  "cosh",
  "tanh",
  "asinh",
  "acosh",
  "atanh",
  "exp",
  "exp_m1",
  "ln",
  "ln_1p",
  "log",
  "log10",
  "log2",
  "sqrt",
  "cbrt",
  "pow",
  "hypot",
  "floor",
  "ceil",
  "round",
  "abs",
  "min",
  "max",
  "to_radians",
  "to_degrees",
  "copysign",
];

export const FLOWEXPR_OPERATORS = [
  "==",
  "!=",
  "<=",
  ">=",
  "<",
  ">",
  "+",
  "-",
  "*",
  "**",
  "//",
  "/",
  "%",
  "=",
  "+=",
  "-=",
  "*=",
  "**=",
  "//=",
  "/=",
  "%=",
];

export const getFlowExprAutocompleteSuggestions = (
  t: (key: string) => string,
): AutocompleteSuggestion[] => [
  // Keywords
  {
    label: "if",
    insertText: "if {{cursor}} {\n  \n} else {\n  \n}",
    type: "keyword",
    description: t("if-else expression"),
  },
  {
    label: "else",
    insertText: "else { {{cursor}} }",
    type: "keyword",
    description: t("else branch"),
  },
  {
    label: "while",
    insertText: "while {{cursor}} {\n  \n}",
    type: "keyword",
    description: t("while loop"),
  },
  {
    label: "for",
    insertText: "for item in {{cursor}} {\n  \n}",
    type: "keyword",
    description: t("for-in loop"),
  },
  {
    label: "in",
    insertText: "in ",
    type: "keyword",
    description: t("membership test / loop iteration"),
  },
  {
    label: "not",
    insertText: "not ",
    type: "keyword",
    description: t("logical NOT"),
  },
  {
    label: "and",
    insertText: "and ",
    type: "keyword",
    description: t("logical AND"),
  },
  {
    label: "or",
    insertText: "or ",
    type: "keyword",
    description: t("logical OR"),
  },
  {
    label: "true",
    insertText: "true",
    type: "keyword",
    description: t("Boolean true"),
  },
  {
    label: "false",
    insertText: "false",
    type: "keyword",
    description: t("Boolean false"),
  },
  {
    label: "null",
    insertText: "null",
    type: "keyword",
    description: t("Null value"),
  },

  // Built-in functions
  {
    label: "value",
    insertText: 'value("{{cursor}}")',
    type: "function",
    description: t("Read a feature attribute by name"),
    detail: 'value("attr_name") → any',
  },
  {
    label: "env",
    insertText: 'env("{{cursor}}")',
    type: "function",
    description: t("Read an environment variable"),
    detail: 'env("VAR_NAME") → string',
  },
  {
    label: "Url",
    insertText: "Url({{cursor}})",
    type: "function",
    description: t("Construct a URL/path value"),
    detail: "Url(path) → Url",
  },
  {
    label: "str",
    insertText: "str({{cursor}})",
    type: "function",
    description: t("Convert to string"),
    detail: "str(value) → string",
  },
  {
    label: "int",
    insertText: "int({{cursor}})",
    type: "function",
    description: t("Convert to integer"),
    detail: "int(value) → integer",
  },
  {
    label: "float",
    insertText: "float({{cursor}})",
    type: "function",
    description: t("Convert to float"),
    detail: "float(value) → float",
  },
  {
    label: "bool",
    insertText: "bool({{cursor}})",
    type: "function",
    description: t("Convert to boolean"),
    detail: "bool(value) → bool",
  },
  {
    label: "list",
    insertText: "list({{cursor}})",
    type: "function",
    description: t("Convert to array"),
    detail: "list(value) → array",
  },
  {
    label: "map",
    insertText: "map({{cursor}})",
    type: "function",
    description: t("Convert to map"),
    detail: "map(value) → map",
  },
  {
    label: "print",
    insertText: "print({{cursor}})",
    type: "function",
    description: t("Debug print (returns first argument)"),
    detail: "print(...) → any",
  },

  // math:: namespace
  {
    label: "math::",
    insertText: "math::",
    type: "namespace",
    description: t("Math functions namespace"),
  },
  {
    label: "math::PI",
    insertText: "math::PI",
    type: "variable",
    description: t("π ≈ 3.14159"),
  },
  {
    label: "math::E",
    insertText: "math::E",
    type: "variable",
    description: t("e ≈ 2.71828"),
  },
  {
    label: "math::TAU",
    insertText: "math::TAU",
    type: "variable",
    description: t("2π ≈ 6.28318"),
  },
  {
    label: "math::sqrt",
    insertText: "math::sqrt({{cursor}})",
    type: "function",
    description: t("Square root"),
    detail: "math::sqrt(x: float) → float",
  },
  {
    label: "math::pow",
    insertText: "math::pow({{cursor}}, )",
    type: "function",
    description: t("Power"),
    detail: "math::pow(base: float, exp: float) → float",
  },
  {
    label: "math::abs",
    insertText: "math::abs({{cursor}})",
    type: "function",
    description: t("Absolute value"),
    detail: "math::abs(x: float) → float",
  },
  {
    label: "math::floor",
    insertText: "math::floor({{cursor}})",
    type: "function",
    description: t("Round down"),
    detail: "math::floor(x: float) → float",
  },
  {
    label: "math::ceil",
    insertText: "math::ceil({{cursor}})",
    type: "function",
    description: t("Round up"),
    detail: "math::ceil(x: float) → float",
  },
  {
    label: "math::round",
    insertText: "math::round({{cursor}})",
    type: "function",
    description: t("Round to nearest"),
    detail: "math::round(x: float) → float",
  },
  {
    label: "math::min",
    insertText: "math::min({{cursor}}, )",
    type: "function",
    description: t("Minimum of two values"),
    detail: "math::min(a: float, b: float) → float",
  },
  {
    label: "math::max",
    insertText: "math::max({{cursor}}, )",
    type: "function",
    description: t("Maximum of two values"),
    detail: "math::max(a: float, b: float) → float",
  },
  {
    label: "math::sin",
    insertText: "math::sin({{cursor}})",
    type: "function",
    description: t("Sine (radians)"),
    detail: "math::sin(x: float) → float",
  },
  {
    label: "math::cos",
    insertText: "math::cos({{cursor}})",
    type: "function",
    description: t("Cosine (radians)"),
    detail: "math::cos(x: float) → float",
  },
  {
    label: "math::tan",
    insertText: "math::tan({{cursor}})",
    type: "function",
    description: t("Tangent (radians)"),
    detail: "math::tan(x: float) → float",
  },
  {
    label: "math::atan2",
    insertText: "math::atan2({{cursor}}, )",
    type: "function",
    description: t("Two-argument arctangent"),
    detail: "math::atan2(y: float, x: float) → float",
  },
  {
    label: "math::ln",
    insertText: "math::ln({{cursor}})",
    type: "function",
    description: t("Natural logarithm"),
    detail: "math::ln(x: float) → float",
  },
  {
    label: "math::log",
    insertText: "math::log({{cursor}})",
    type: "function",
    description: t("Logarithm"),
    detail: "math::log(x: float) → float",
  },
  {
    label: "math::log10",
    insertText: "math::log10({{cursor}})",
    type: "function",
    description: t("Base-10 logarithm"),
    detail: "math::log10(x: float) → float",
  },
  {
    label: "math::to_radians",
    insertText: "math::to_radians({{cursor}})",
    type: "function",
    description: t("Degrees to radians"),
    detail: "math::to_radians(deg: float) → float",
  },
  {
    label: "math::to_degrees",
    insertText: "math::to_degrees({{cursor}})",
    type: "function",
    description: t("Radians to degrees"),
    detail: "math::to_degrees(rad: float) → float",
  },

  // Operators
  {
    label: "==",
    insertText: "== ",
    type: "operator",
    description: t("Equal"),
  },
  {
    label: "!=",
    insertText: "!= ",
    type: "operator",
    description: t("Not equal"),
  },
  {
    label: "<=",
    insertText: "<= ",
    type: "operator",
    description: t("Less than or equal"),
  },
  {
    label: ">=",
    insertText: ">= ",
    type: "operator",
    description: t("Greater than or equal"),
  },
];
