[package]
description = "Re:Earth Flow action library"
name = "reearth-flow-action"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
reearth-flow-action-log.workspace = true
reearth-flow-common.workspace = true
reearth-flow-eval-expr.workspace = true
reearth-flow-macros.workspace = true
reearth-flow-storage.workspace = true
reearth-flow-workflow.workspace = true

anyhow.workspace = true
async_zip = {version = "0.0.16", features = ["full"]}
bytes.workspace = true
csv = "1.3.0"
directories.workspace = true
futures.workspace = true
rayon.workspace = true
rhai.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
uuid.workspace = true
