//! Embeds the CityGML 2.0 schema bundle in `schemas/` into the crate.
//!
//! `schemas/MANIFEST.tsv` lists every file with its size and SHA-256. The build
//! fails if a listed file is missing or changed, or if a schema file is present
//! but not listed, then emits the `include_bytes!` table that
//! `src/schema/bundle.rs` includes. Follows `runtime/geometry/build.rs`.

use std::collections::BTreeSet;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

/// A row of `schemas/MANIFEST.tsv`.
struct Row {
    /// The path under `schemas/`, which is also the lookup key.
    path: String,
    size: u64,
    sha256: String,
}

fn main() {
    let root =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR"));
    let schemas = root.join("schemas");
    let manifest = schemas.join("MANIFEST.tsv");
    println!("cargo::rerun-if-changed={}", schemas.display());

    let text =
        fs::read_to_string(&manifest).unwrap_or_else(|e| panic!("{}: {e}", manifest.display()));
    let rows = parse(&text).unwrap_or_else(|e| panic!("{}: {e}", manifest.display()));

    let mut problems: Vec<String> = rows
        .iter()
        .filter_map(|row| verify(&schemas.join(&row.path), row).err())
        .collect();
    problems.extend(unlisted(&schemas, &rows));
    assert!(
        problems.is_empty(),
        "{} does not describe {}:\n  {}",
        manifest.display(),
        schemas.display(),
        problems.join("\n  ")
    );

    let mut table = String::from(
        "/// The embedded schema bundle. Generated by `build.rs` from\n\
         /// `schemas/MANIFEST.tsv`.\n\
         static EMBEDDED_SCHEMAS: &[EmbeddedSchema] = &[\n",
    );
    for row in &rows {
        let path = schemas.join(&row.path);
        let path = path
            .to_str()
            .unwrap_or_else(|| panic!("{} is not valid UTF-8", path.display()));
        println!("cargo::rerun-if-changed={path}");
        writeln!(
            table,
            "    EmbeddedSchema {{ key: {:?}, bytes: include_bytes!({path:?}) }},",
            row.path
        )
        .expect("writing to a String cannot fail");
    }
    table.push_str("];\n");

    let out =
        Path::new(&env::var("OUT_DIR").expect("cargo sets OUT_DIR")).join("embedded_schemas.rs");
    fs::write(&out, table).unwrap_or_else(|e| panic!("{}: {e}", out.display()));
}

/// Read the manifest rows, which follow the title and column headers.
fn parse(text: &str) -> Result<Vec<Row>, String> {
    let mut rows = Vec::new();
    for line in text.lines().skip(2).filter(|line| !line.trim().is_empty()) {
        let mut fields = line.split('\t');
        let path = fields.next().expect("splitting yields at least one field");
        let (size, sha256) = (
            fields.next().unwrap_or_default(),
            fields.next().unwrap_or_default(),
        );
        if size.is_empty() || sha256.is_empty() {
            return Err(format!("{path} has no size or SHA-256"));
        }
        rows.push(Row {
            path: path.to_owned(),
            size: size
                .parse()
                .map_err(|e| format!("{path} has an unreadable size: {e}"))?,
            sha256: sha256.to_owned(),
        });
    }
    if rows.is_empty() {
        return Err("lists no schemas".to_owned());
    }
    Ok(rows)
}

/// Check that `path` holds exactly the bytes `row` records.
fn verify(path: &Path, row: &Row) -> Result<(), String> {
    let bytes = fs::read(path).map_err(|e| format!("{}: {e}", row.path))?;
    if bytes.len() as u64 != row.size {
        return Err(format!(
            "{}: manifest records {} bytes, the file holds {}",
            row.path,
            row.size,
            bytes.len()
        ));
    }
    let digest = hex::encode(Sha256::digest(&bytes));
    if digest != row.sha256 {
        return Err(format!(
            "{}: manifest records SHA-256 {}, the file is {digest}",
            row.path, row.sha256
        ));
    }
    Ok(())
}

/// Schema files under `schemas` that no manifest row names.
fn unlisted(schemas: &Path, rows: &[Row]) -> Vec<String> {
    let listed: BTreeSet<&str> = rows.iter().map(|row| row.path.as_str()).collect();
    let mut found = Vec::new();
    walk(schemas, schemas, &mut found);
    let mut extra: Vec<String> = found
        .into_iter()
        .filter(|path| !listed.contains(path.as_str()))
        .map(|path| format!("{path}: present but not listed"))
        .collect();
    extra.sort();
    extra
}

fn walk(root: &Path, dir: &Path, out: &mut Vec<String>) {
    for entry in fs::read_dir(dir).unwrap_or_else(|e| panic!("{}: {e}", dir.display())) {
        let path = entry
            .unwrap_or_else(|e| panic!("{}: {e}", dir.display()))
            .path();
        if path.is_dir() {
            walk(root, &path, out);
        } else if path.extension().is_some_and(|ext| ext == "xsd") {
            let relative = path.strip_prefix(root).expect("walked from root");
            out.push(relative.to_string_lossy().replace('\\', "/"));
        }
    }
}
