# yaml-language-server: $schema=https://raw.githubusercontent.com/reearth/reearth-flow/main/engine/schema/workflow.json
id: 83307700-04b9-490c-b6a1-11b93e7f7a8a
name: "DataConvert-01-bldg-workflow"
entryGraphId: 34bf873b-3364-46b0-8153-efeb9568bb3c
with:
  cityGmlPath:
  cityCode:
  codelistsPath:
  schemasPath:
  schemaJson: !include ../../../config/schema.txt
  targetPackages:
    - bldg
  addNsprefixToFeatureTypes: true
  extractDmGeometryAsXmlFragment: false
  outputPath:
graphs:
  - !include ../../../graphs/attribute_reader.yml
  - !include ../../../graphs/folder_and_file_path_reader.yml
  - id: 34bf873b-3364-46b0-8153-efeb9568bb3c
    name: entry_point
    nodes:
      - id: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        name: FeatureCreator
        type: action
        action: FeatureCreator
        with:
          creator: |
            [
              #{
                cityGmlPath: env.get("cityGmlPath")
              },
            ]

      - id: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        name: AttributeReader
        type: subGraph
        subGraphId: 64931277-3a82-4a1c-88bc-9b54fe172518

      - id: fc649773-af86-49bd-9629-149f9ac4166b
        name: AttributeMapperFilePath
        type: action
        action: AttributeMapper
        with:
          mappers:
            - attribute: code
              valueAttribute: meshCode
            - attribute: type
              valueAttribute: package
            - attribute: maxLod
              valueAttribute: maxLod
            - attribute: length
              expr: |
                env.get("__value")["package"].len()
            - attribute: file
              expr: |
                file::extract_filename(env.get("__value").cityGmlPath)

      - id: 6e2a7c56-1ce3-48ee-b969-b1a1a0f057ca
        name: FileWriterTsvFilePath
        type: action
        action: CsvWriter
        with:
          format: tsv
          output: |
            file::join_path(env.get("outputPath"), "maxLod.tsv")

      - id: ded2e272-e05c-4918-86b3-aa9f763da6e6
        name: FeatureReaderByCityGml
        type: action
        action: FeatureReader
        with:
          format: citygml
          dataset: |
            env.get("__value").cityGmlPath

      - id: 1bd42875-4b8c-4439-82dc-9554d9946b07
        name: AttributeFlattener
        type: action
        action: PLATEAU3.AttributeFlattener

      - id: 928e21d9-fc30-4876-ba03-41338cfa47ed
        name: VerticalReprojector
        type: action
        action: VerticalReprojector
        with:
          reprojectorType: jgd2011ToWgs84

      - id: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        name: AttributeManagerCreateValid
        type: action
        action: AttributeManager
        with:
          operations:
          - attribute: gmlId
            method: rename
            value: id
          - attribute: cityGmlPath
            method: remove
          - attribute: package
            method: remove
          - attribute: gmlName
            method: rename
            value: featureType
          - attribute: cityName
            method: remove
          - attribute: geometryName
            method: remove
          - attribute: featureParentId
            method: remove
          - attribute: root
            method: remove
          - attribute: type
            method: remove
          - attribute: udxDirs
            method: remove
          - attribute: cityCode
            method: remove
          - attribute: meshCode
            method: remove
          - attribute: gmlRootId
            method: remove
          - attribute: featureId
            method: remove

      - id: 41d69f1f-2a4d-4bc1-a5d0-175698273571
        name: cesium3DTilesWriter
        type: action
        action: Cesium3DTilesWriter
        with:
          minZoom: 15
          maxZoom: 18
          attachTexture: true
          output: |
             file::join_path(env.get("outputPath"), "bldg_lod")

    edges:
      - id: 5ebf24ab-1d98-49d5-8f58-eb7c18d27244
        from: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        to: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        fromPort: default
        toPort: default
      - id: 7b81f501-3f07-4cec-bf9b-9cefcebdf47d
        from: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        to: fc649773-af86-49bd-9629-149f9ac4166b
        fromPort: filePath
        toPort: default
      - id: 284b02d9-8051-4614-a03c-583274c700f8
        from: fc649773-af86-49bd-9629-149f9ac4166b
        to: 6e2a7c56-1ce3-48ee-b969-b1a1a0f057ca
        fromPort: default
        toPort: default
      - id: a4751655-5956-4e27-a976-e35f8914ad31
        from: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        to: ded2e272-e05c-4918-86b3-aa9f763da6e6
        fromPort: filePath
        toPort: default
      - id: fb48e9e0-fa1b-4f27-8a89-84b6d2e1c6d7
        from: ded2e272-e05c-4918-86b3-aa9f763da6e6
        to: 1bd42875-4b8c-4439-82dc-9554d9946b07
        fromPort: default
        toPort: default
      - id: d4c1c8a9-00a6-49c1-9735-db62a736932b
        from: 1bd42875-4b8c-4439-82dc-9554d9946b07
        to: 928e21d9-fc30-4876-ba03-41338cfa47ed
        fromPort: default
        toPort: default
      - id: 8ca2968d-b44f-42dd-befa-86134bd9b030
        from: 928e21d9-fc30-4876-ba03-41338cfa47ed
        to: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        fromPort: default
        toPort: default
      - id: 1c7273e8-f529-4233-a9ef-34ee68c6d586
        from: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        to: 41d69f1f-2a4d-4bc1-a5d0-175698273571
        fromPort: default
        toPort: default
