# yaml-language-server: $schema=https://raw.githubusercontent.com/reearth/reearth-flow/main/engine/schema/workflow.json
id: 697b3412-d017-11f0-9e7b-7c70db10a7e3
name: "Solar Radiation time to TIMEVALUE workflow"
entryGraphId: 78ce67ea-d017-11f0-99c4-7c70db10a7e3
with:
  csvFile: !include ./input-time-to-time-value.csv
graphs:
  - id: 78ce67ea-d017-11f0-99c4-7c70db10a7e3
    name: entry_point
    nodes:
      - id: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        name: CsvReader
        type: action
        action: CsvReader
        with:
          format: csv
          inline: |
            env.get("csvFile")

      - id: d2b4977d-e218-4628-96f2-d26407aeea14
        name: AttributeMapper
        type: action
        action: AttributeMapper
        with:
          mappers:
            - attribute: 年月日
              valueAttribute: 年月日
            - attribute: 方位_出
              valueAttribute: 方位[°]
            - attribute: 方位_入
              valueAttribute: 方位[°]00
            - attribute: 高度[°]
              valueAttribute: 高度[°]
            # Preserve original time values
            - attribute: 出
              valueAttribute: 出
            - attribute: 入り
              valueAttribute: 入り
            - attribute: 南中
              valueAttribute: 南中

      - id: deeca816-d026-11f0-bcf9-7c70db10a7e3
        name: solar-radiation-accumulator
        type: action
        action: AttributeManager
        with:
          operations:
          # Calculate solar radiation using the time values
          - attribute: 日射量[kWh/m2]
            method: create
            expr: |
              # Parse the time strings to calculate solar radiation
              let input_str = env.get("入り");
              let output_str = env.get("出");

              # Since input_str and output_str are in format like "16:50", "7:06",
              # we need to parse them into time values in seconds
              # Split the time strings by colon
              let input_parts = string::split(input_str, ":");
              let output_parts = string::split(output_str, ":");

              # Extract hour and minute parts (assuming H:MM or HH:MM format)
              let input_hour = string::to_int(input_parts[0]);
              let input_min = string::to_int(input_parts[1]);
              let output_hour = string::to_int(output_parts[0]);
              let output_min = string::to_int(output_parts[1]);

              # Calculate total seconds from midnight
              let input_seconds = input_hour * 3600 + input_min * 60;
              let output_seconds = output_hour * 3600 + output_min * 60;

              # Calculate the day fraction
              let input_day_fraction = input_seconds / 86400.0;
              let output_day_fraction = output_seconds / 86400.0;

              # Get the elevation angle
              let hight = env.get("高度[°]");

              # Calculate solar radiation
              (input_day_fraction - output_day_fraction) * 24.0 * math::sin(math::to_radians(hight)) * (2.0/math::PI)

      - id: f5e66920-24c0-4c70-ae16-6be1ed3b906c
        name: CsvWriter
        type: action
        action: CsvWriter
        with:
          format: csv
          output: ./target/output-time-to-time-value.csv

    edges:
      - id: c064cf52-705f-443a-b2de-6795266c540d
        from: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        to: d2b4977d-e218-4628-96f2-d26407aeea14
        fromPort: default
        toPort: default

      - id: ff632408-d0b2-11f0-8ed6-7c70db10a7e3
        from: d2b4977d-e218-4628-96f2-d26407aeea14
        to: deeca816-d026-11f0-bcf9-7c70db10a7e3
        fromPort: default
        toPort: default

      - id: c81ea200-9aa1-4522-9f72-10e8b9184cb7
        from: deeca816-d026-11f0-bcf9-7c70db10a7e3
        to: f5e66920-24c0-4c70-ae16-6be1ed3b906c
        fromPort: default
        toPort: default
