# yaml-language-server: $schema=https://raw.githubusercontent.com/reearth/reearth-flow/main/engine/schema/workflow.json
id: 697b3412-d017-11f0-9e7b-7c70db10a7e3
name: "Solar Radiation time to TIMEVALUE workflow"
entryGraphId: 78ce67ea-d017-11f0-99c4-7c70db10a7e3
with:
  csvFile: !include ./input-time-to-time-value.csv
graphs:
  - id: 78ce67ea-d017-11f0-99c4-7c70db10a7e3
    name: entry_point
    nodes:
      - id: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        name: CsvReader
        type: action
        action: CsvReader
        with:
          format: csv
          inline: |
            env.get("csvFile")

      - id: d2b4977d-e218-4628-96f2-d26407aeea14
        name: AttributeMapper
        type: action
        action: AttributeMapper
        with:
          mappers:
            - attribute: 年月日
              valueAttribute: 年月日
            - attribute: 方位_出
              valueAttribute: 方位[°]
            - attribute: 方位_入
              valueAttribute: 方位[°]00
            - attribute: 高度[°]
              valueAttribute: 高度[°]
            # Preserve original time values
            - attribute: 出
              valueAttribute: 出
            - attribute: 入り
              valueAttribute: 入り
            - attribute: 南中
              valueAttribute: 南中
            # Add the extracted time parts directly in the AttributeMapper
            - attribute: 出_H
              expr: |
                let time_parts = env.get("__value")["出"].split(":");
                if time_parts.len() > 0 { time_parts[0] } else { "" }
            - attribute: 出_M
              expr: |
                let time_parts = env.get("__value")["出"].split(":");
                if time_parts.len() > 1 { time_parts[1] } else { "" }
            - attribute: 入り_H
              expr: |
                let time_parts = env.get("__value")["入り"].split(":");
                if time_parts.len() > 0 { time_parts[0] } else { "" }
            - attribute: 入り_M
              expr: |
                let time_parts = env.get("__value")["入り"].split(":");
                if time_parts.len() > 1 { time_parts[1] } else { "" }

      - id: 57d8a9b1-8e7b-4c23-9e6d-9f70db10a7e4
        name: ConvertToSeconds
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: 出
              method: convert 
              value: |
                let hour_str = env.get("__value")["出_H"];
                let minute_str = env.get("__value")["出_M"];
                minute_str
         

      - id: f5e66920-24c0-4c70-ae16-6be1ed3b906c
        name: CsvWriter
        type: action
        action: CsvWriter
        with:
          format: csv
          output: ./target/output-time-to-time-value.csv

    edges:
      - id: c064cf52-705f-443a-b2de-6795266c540d
        from: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        to: d2b4977d-e218-4628-96f2-d26407aeea14
        fromPort: default
        toPort: default

      - id: c81ea200-9aa1-4522-9f72-10e8b9184cb7
        from: d2b4977d-e218-4628-96f2-d26407aeea14
        to: 57d8a9b1-8e7b-4c23-9e6d-9f70db10a7e4
        fromPort: default
        toPort: default

      - id: e9c6b2a3-4d5e-6f7a-8b9c-0d1e2f3a4b5c
        from: 57d8a9b1-8e7b-4c23-9e6d-9f70db10a7e4
        to: f5e66920-24c0-4c70-ae16-6be1ed3b906c
        fromPort: default
        toPort: default
