// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -source=repo.go -destination=mockrepo/mockrepo.go -package=mockrepo -mock_names=Repo=MockWorkspaceRepo
//

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	id "github.com/reearth/reearth-flow/api/pkg/id"
	workspace "github.com/reearth/reearth-flow/api/pkg/workspace"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkspaceRepo is a mock of Repo interface.
type MockWorkspaceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceRepoMockRecorder
	isgomock struct{}
}

// MockWorkspaceRepoMockRecorder is the mock recorder for MockWorkspaceRepo.
type MockWorkspaceRepoMockRecorder struct {
	mock *MockWorkspaceRepo
}

// NewMockWorkspaceRepo creates a new mock instance.
func NewMockWorkspaceRepo(ctrl *gomock.Controller) *MockWorkspaceRepo {
	mock := &MockWorkspaceRepo{ctrl: ctrl}
	mock.recorder = &MockWorkspaceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceRepo) EXPECT() *MockWorkspaceRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWorkspaceRepo) Create(ctx context.Context, name string) (*workspace.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name)
	ret0, _ := ret[0].(*workspace.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWorkspaceRepoMockRecorder) Create(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWorkspaceRepo)(nil).Create), ctx, name)
}

// Delete mocks base method.
func (m *MockWorkspaceRepo) Delete(ctx context.Context, wid id.WorkspaceID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, wid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWorkspaceRepoMockRecorder) Delete(ctx, wid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWorkspaceRepo)(nil).Delete), ctx, wid)
}

// FindByIDs mocks base method.
func (m *MockWorkspaceRepo) FindByIDs(ctx context.Context, ids id.WorkspaceIDList) (workspace.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", ctx, ids)
	ret0, _ := ret[0].(workspace.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockWorkspaceRepoMockRecorder) FindByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockWorkspaceRepo)(nil).FindByIDs), ctx, ids)
}

// FindByUser mocks base method.
func (m *MockWorkspaceRepo) FindByUser(ctx context.Context, uid id.UserID) (workspace.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUser", ctx, uid)
	ret0, _ := ret[0].(workspace.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUser indicates an expected call of FindByUser.
func (mr *MockWorkspaceRepoMockRecorder) FindByUser(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUser", reflect.TypeOf((*MockWorkspaceRepo)(nil).FindByUser), ctx, uid)
}

// Update mocks base method.
func (m *MockWorkspaceRepo) Update(ctx context.Context, wid id.WorkspaceID, name string) (*workspace.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, wid, name)
	ret0, _ := ret[0].(*workspace.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockWorkspaceRepoMockRecorder) Update(ctx, wid, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWorkspaceRepo)(nil).Update), ctx, wid, name)
}
