# General application settings
[general]
app_name = "WebSocket Editor Backend"
environment = "development" # can be "development", "staging", or "production"

# Redis configuration
[redis]
host = "127.0.0.1"
port = 6379
database = 0

# Google Cloud Storage configuration
[gcs]
project_id = "project_id"
bucket_name = "bucket_name"
credentials_file = "/path/to/your/credentials.json"

# Logging configuration
[logging]
level = "debug" # can be "debug", "info", "warn", or "error"
