[package]
description = "Re:Earth Flow cli library"
name = "reearth-flow-cli"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "reearth-flow"
path = "src/main.rs"

[dependencies]
reearth-flow-action-log.workspace = true
reearth-flow-common.workspace = true
reearth-flow-state.workspace = true
reearth-flow-storage.workspace = true
reearth-flow-telemetry.workspace = true
reearth-flow-workflow-runner.workspace = true

bytes.workspace = true
clap = {version = "4.5.4", features = ["env", "string"]}
colored = "2.1.0"
directories.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
thiserror.workspace = true
time.workspace = true
tokio-stream.workspace = true
tokio.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
