import { Job } from "@flow/types";
import { formatDate } from "@flow/utils";

const date = formatDate(new Date());
export const jobs: Job[] = [
  {
    id: "1",
    deploymentId: "1",
    workspaceId: "1",
    status: "completed",
    startedAt: date,
    completedAt: date,
    logs: true,
    deployment: {
      id: "1",
      projectId: "1",
      projectName: "Project 1",
      workspaceId: "1",
      workflowUrl: "http://example.com",
      description: "Description 1",
      version: "1.0",
      createdAt: date,
      updatedAt: date,
    },
  },
  {
    id: "2",
    deploymentId: "2",
    workspaceId: "2",
    status: "failed",
    startedAt: date,
    completedAt: date,
    logs: true,
    deployment: {
      id: "2",
      projectId: "2",
      projectName: "Project 2",
      workspaceId: "2",
      workflowUrl: "http://example.com",
      description: "Description 2",
      version: "2.0",
      createdAt: date,
      updatedAt: date,
    },
  },
  {
    id: "3",
    deploymentId: "3",
    workspaceId: "3",
    status: "running",
    startedAt: date,
    completedAt: date,
    logs: true,
    deployment: {
      id: "3",
      projectId: "3",
      projectName: "Project 3",
      workspaceId: "3",
      workflowUrl: "http://example.com",
      description: "Description 3",
      version: "3.0",
      createdAt: date,
      updatedAt: date,
    },
  },
  {
    id: "4",
    deploymentId: "4",
    workspaceId: "4",
    status: "pending",
    startedAt: date,
    completedAt: date,
    logs: true,
    deployment: {
      id: "4",
      projectId: "4",
      projectName: "Project 4",
      workspaceId: "4",
      workflowUrl: "http://example.com",
      description: "Description 4",
      version: "4.0",
      createdAt: date,
      updatedAt: date,
    },
  },
  {
    id: "5",
    deploymentId: "5",
    workspaceId: "5",
    status: "completed",
    startedAt: date,
    completedAt: date,
    logs: true,
    deployment: {
      id: "5",
      projectId: "5",
      projectName: "Project 5",
      workspaceId: "5",
      workflowUrl: "http://example.com",
      description: "Description 5",
      version: "5.0",
      createdAt: date,
      updatedAt: date,
    },
  },
];
