import { Job } from "@flow/types";
import { formatDate } from "@flow/utils";

const date = formatDate(new Date());
export const jobs: Job[] = [
  {
    id: "1",
    deploymentId: "1",
    workspaceId: "1",
    status: "completed",
    startedAt: date,
    completedAt: date,
    logs: true,
    trigger: "api",
    deployment: {
      id: "1",
      projectId: "1",
      projectName: "Project 1",
      workspaceId: "1",
      workflowUrl: "http://example.com",
      description: "Description 1",
      version: "1.0",
      createdAt: date,
      updatedAt: date,
    },
  },
  {
    id: "2",
    deploymentId: "2",
    workspaceId: "2",
    status: "failed",
    startedAt: date,
    completedAt: date,
    logs: true,
    trigger: "manual",
    deployment: {
      id: "2",
      projectId: "2",
      projectName: "Project 2",
      workspaceId: "2",
      workflowUrl: "http://example.com",
      description: "Description 2",
      version: "2.0",
      createdAt: date,
      updatedAt: date,
    },
  },
  {
    id: "3",
    deploymentId: "3",
    workspaceId: "3",
    status: "running",
    startedAt: date,
    completedAt: date,
    logs: true,
    trigger: "api",
    deployment: {
      id: "3",
      projectId: "3",
      projectName: "Project 3",
      workspaceId: "3",
      workflowUrl: "http://example.com",
      description: "Description 3",
      version: "3.0",
      createdAt: date,
      updatedAt: date,
    },
  },
  {
    id: "4",
    deploymentId: "4",
    workspaceId: "4",
    status: "queued",
    startedAt: date,
    completedAt: date,
    logs: true,
    trigger: "manual",
    deployment: {
      id: "4",
      projectId: "4",
      projectName: "Project 4",
      workspaceId: "4",
      workflowUrl: "http://example.com",
      description: "Description 4",
      version: "4.0",
      createdAt: date,
      updatedAt: date,
    },
  },
  {
    id: "5",
    deploymentId: "5",
    workspaceId: "5",
    status: "completed",
    startedAt: date,
    completedAt: date,
    logs: true,
    trigger: "api",
    deployment: {
      id: "5",
      projectId: "5",
      projectName: "Project 5",
      workspaceId: "5",
      workflowUrl: "http://example.com",
      description: "Description 5",
      version: "5.0",
      createdAt: date,
      updatedAt: date,
    },
  },
  {
    id: "6",
    deploymentId: "6",
    workspaceId: "6",
    status: "failed",
    startedAt: date,
    completedAt: date,
    logs: true,
    trigger: "manual",
    deployment: {
      id: "6",
      projectId: "6",
      projectName: "Project 6",
      workspaceId: "6",
      workflowUrl: "http://example.com",
      description: "Description 6",
      version: "6.0",
      createdAt: date,
      updatedAt: date,
    },
  },
  {
    id: "7",
    deploymentId: "7",
    workspaceId: "7",
    status: "running",
    startedAt: date,
    completedAt: date,
    logs: true,
    trigger: "api",
    deployment: {
      id: "7",
      projectId: "7",
      projectName: "Project 7",
      workspaceId: "7",
      workflowUrl: "http://example.com",
      description: "Description 7",
      version: "7.0",
      createdAt: date,
      updatedAt: date,
    },
  },
  {
    id: "8",
    deploymentId: "8",
    workspaceId: "8",
    status: "queued",
    startedAt: date,
    completedAt: date,
    logs: true,
    trigger: "manual",
    deployment: {
      id: "8",
      projectId: "8",
      projectName: "Project 8",
      workspaceId: "8",
      workflowUrl: "http://example.com",
      description: "Description 8",
      version: "8.0",
      createdAt: date,
      updatedAt: date,
    },
  },
  {
    id: "9",
    deploymentId: "9",
    workspaceId: "9",
    status: "completed",
    startedAt: date,
    completedAt: date,
    logs: true,
    trigger: "api",
    deployment: {
      id: "9",
      projectId: "9",
      projectName: "Project 9",
      workspaceId: "9",
      workflowUrl: "http://example.com",
      description: "Description 9",
      version: "9.0",
      createdAt: date,
      updatedAt: date,
    },
  },
  {
    id: "10",
    deploymentId: "10",
    workspaceId: "10",
    status: "failed",
    startedAt: date,
    completedAt: date,
    logs: true,
    trigger: "manual",
    deployment: {
      id: "10",
      projectId: "10",
      projectName: "Project 10",
      workspaceId: "10",
      workflowUrl: "http://example.com",
      description: "Description 10",
      version: "10.0",
      createdAt: date,
      updatedAt: date,
    },
  },
  {
    id: "11",
    deploymentId: "11",
    workspaceId: "11",
    status: "running",
    startedAt: date,
    completedAt: date,
    logs: true,
    trigger: "api",
    deployment: {
      id: "11",
      projectId: "11",
      projectName: "Project 11",
      workspaceId: "11",
      workflowUrl: "http://example.com",
      description: "Description 11",
      version: "11.0",
      createdAt: date,
      updatedAt: date,
    },
  },
  {
    id: "12",
    deploymentId: "12",
    workspaceId: "12",
    status: "queued",
    startedAt: date,
    completedAt: date,
    logs: true,
    trigger: "manual",
    deployment: {
      id: "12",
      projectId: "12",
      projectName: "Project 12",
      workspaceId: "12",
      workflowUrl: "http://example.com",
      description: "Description 12",
      version: "12.0",
      createdAt: date,
      updatedAt: date,
    },
  },
  {
    id: "13",
    deploymentId: "13",
    workspaceId: "13",
    status: "completed",
    startedAt: date,
    completedAt: date,
    logs: true,
    trigger: "api",
    deployment: {
      id: "13",
      projectId: "13",
      projectName: "Project 13",
      workspaceId: "13",
      workflowUrl: "http://example.com",
      description: "Description 13",
      version: "13.0",
      createdAt: date,
      updatedAt: date,
    },
  },
];
