const mockLogs = [
  {
    workflowId: "workflow-123",
    jobId: "job-456",
    nodeId: "node-789",
    timestamp: new Date().toISOString(),
    logLevel: "ERROR",
    message: "An error occurred while processing the task.",
  },
  {
    workflowId: "workflow-123",
    jobId: "job-456",
    nodeId: "node-790",
    timestamp: new Date(Date.now() - 1000 * 60).toISOString(),
    logLevel: "WARN",
    message: "The system is approaching resource limits.",
  },
  {
    workflowId: "workflow-124",
    jobId: "job-457",
    nodeId: "node-791",
    timestamp: new Date(Date.now() - 1000 * 120).toISOString(),
    logLevel: "INFO",
    message: "Task started successfully.",
  },
  {
    workflowId: "workflow-125",
    jobId: "job-458",
    nodeId: null,
    timestamp: new Date(Date.now() - 1000 * 180).toISOString(),
    logLevel: "DEBUG",
    message: "Debugging the task execution flow.",
  },
  {
    workflowId: "workflow-126",
    jobId: "job-459",
    nodeId: "node-792",
    timestamp: new Date(Date.now() - 1000 * 240).toISOString(),
    logLevel: "TRACE",
    message: "Trace log for deep diagnostics.",
  },
  {
    workflowId: "workflow-123",
    jobId: "job-456",
    nodeId: "node-789",
    timestamp: new Date().toISOString(),
    logLevel: "ERROR",
    message: "An error occurred while processing the task.",
  },
  {
    workflowId: "workflow-123",
    jobId: "job-456",
    nodeId: "node-790",
    timestamp: new Date(Date.now() - 1000 * 60).toISOString(),
    logLevel: "WARN",
    message: "The system is approaching resource limits.",
  },
  {
    workflowId: "workflow-124",
    jobId: "job-457",
    nodeId: "node-791",
    timestamp: new Date(Date.now() - 1000 * 120).toISOString(),
    logLevel: "INFO",
    message: "Task started successfully.",
  },
  {
    workflowId: "workflow-125",
    jobId: "job-458",
    nodeId: null,
    timestamp: new Date(Date.now() - 1000 * 180).toISOString(),
    logLevel: "DEBUG",
    message: "Debugging the task execution flow.",
  },
  {
    workflowId: "workflow-126",
    jobId: "job-459",
    nodeId: "node-792",
    timestamp: new Date(Date.now() - 1000 * 240).toISOString(),
    logLevel: "TRACE",
    message: "Trace log for deep diagnostics.",
  },
  {
    workflowId: "workflow-123",
    jobId: "job-456",
    nodeId: "node-789",
    timestamp: new Date().toISOString(),
    logLevel: "ERROR",
    message: "An error occurred while processing the task.",
  },
  {
    workflowId: "workflow-123",
    jobId: "job-456",
    nodeId: "node-790",
    timestamp: new Date(Date.now() - 1000 * 60).toISOString(),
    logLevel: "WARN",
    message: "The system is approaching resource limits.",
  },
  {
    workflowId: "workflow-124",
    jobId: "job-457",
    nodeId: "node-791",
    timestamp: new Date(Date.now() - 1000 * 120).toISOString(),
    logLevel: "INFO",
    message: "Task started successfully.",
  },
  {
    workflowId: "workflow-125",
    jobId: "job-458",
    nodeId: null,
    timestamp: new Date(Date.now() - 1000 * 180).toISOString(),
    logLevel: "DEBUG",
    message: "Debugging the task execution flow.",
  },
  {
    workflowId: "workflow-126",
    jobId: "job-459",
    nodeId: "node-792",
    timestamp: new Date(Date.now() - 1000 * 240).toISOString(),
    logLevel: "TRACE",
    message: "Trace log for deep diagnostics.",
  },
  {
    workflowId: "workflow-123",
    jobId: "job-456",
    nodeId: "node-789",
    timestamp: new Date().toISOString(),
    logLevel: "ERROR",
    message: "An error occurred while processing the task.",
  },
  {
    workflowId: "workflow-123",
    jobId: "job-456",
    nodeId: "node-790",
    timestamp: new Date(Date.now() - 1000 * 60).toISOString(),
    logLevel: "WARN",
    message: "The system is approaching resource limits.",
  },
  {
    workflowId: "workflow-124",
    jobId: "job-457",
    nodeId: "node-791",
    timestamp: new Date(Date.now() - 1000 * 120).toISOString(),
    logLevel: "INFO",
    message: "Task started successfully.",
  },
  {
    workflowId: "workflow-125",
    jobId: "job-458",
    nodeId: null,
    timestamp: new Date(Date.now() - 1000 * 180).toISOString(),
    logLevel: "DEBUG",
    message: "Debugging the task execution flow.",
  },
  {
    workflowId: "workflow-126",
    jobId: "job-459",
    nodeId: "node-792",
    timestamp: new Date(Date.now() - 1000 * 240).toISOString(),
    logLevel: "TRACE",
    message: "Trace log for deep diagnostics.",
  },
  {
    workflowId: "workflow-123",
    jobId: "job-456",
    nodeId: "node-789",
    timestamp: new Date().toISOString(),
    logLevel: "ERROR",
    message: "An error occurred while processing the task.",
  },
  {
    workflowId: "workflow-123",
    jobId: "job-456",
    nodeId: "node-790",
    timestamp: new Date(Date.now() - 1000 * 60).toISOString(),
    logLevel: "WARN",
    message: "The system is approaching resource limits.",
  },
  {
    workflowId: "workflow-124",
    jobId: "job-457",
    nodeId: "node-791",
    timestamp: new Date(Date.now() - 1000 * 120).toISOString(),
    logLevel: "INFO",
    message: "Task started successfully.",
  },
  {
    workflowId: "workflow-125",
    jobId: "job-458",
    nodeId: null,
    timestamp: new Date(Date.now() - 1000 * 180).toISOString(),
    logLevel: "DEBUG",
    message: "Debugging the task execution flow.",
  },
  {
    workflowId: "workflow-126",
    jobId: "job-459",
    nodeId: "node-792",
    timestamp: new Date(Date.now() - 1000 * 240).toISOString(),
    logLevel: "TRACE",
    message: "Trace log for deep diagnostics.",
  },
  {
    workflowId: "workflow-123",
    jobId: "job-456",
    nodeId: "node-789",
    timestamp: new Date().toISOString(),
    logLevel: "ERROR",
    message: "An error occurred while processing the task.",
  },
  {
    workflowId: "workflow-123",
    jobId: "job-456",
    nodeId: "node-790",
    timestamp: new Date(Date.now() - 1000 * 60).toISOString(),
    logLevel: "WARN",
    message: "The system is approaching resource limits.",
  },
  {
    workflowId: "workflow-124",
    jobId: "job-457",
    nodeId: "node-791",
    timestamp: new Date(Date.now() - 1000 * 120).toISOString(),
    logLevel: "INFO",
    message: "Task started successfully.",
  },
  {
    workflowId: "workflow-125",
    jobId: "job-458",
    nodeId: null,
    timestamp: new Date(Date.now() - 1000 * 180).toISOString(),
    logLevel: "DEBUG",
    message: "Debugging the task execution flow.",
  },
  {
    workflowId: "workflow-126",
    jobId: "job-459",
    nodeId: "node-792",
    timestamp: new Date(Date.now() - 1000 * 240).toISOString(),
    logLevel: "TRACE",
    message: "Trace log for deep diagnostics.",
  },
];

export default mockLogs;
