# yaml-language-server: $schema=https://raw.githubusercontent.com/reearth/reearth-flow/main/engine/schema/workflow.json
id: 3e39d990-0a80-47df-9be9-3bf7c0068b5a
name: "PLATEAU4-DataConvert-04-luse-lsld-workflow"
entryGraphId: 0e500d5a-7882-4835-9285-9763ba8b5b65
with:
  cityGmlPath:
  codelistsPath:
  schemasPath:
  codelists:
  schemas:
  cityCode:
  targetPackages:
    - luse
    - lsld
  workerArtifactPath:
graphs:
  - !include ../../../../graphs/plateau4/folder_and_file_path_reader.yml
  - id: 0e500d5a-7882-4835-9285-9763ba8b5b65
    name: entry_point
    nodes:
      - id: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        name: FeatureCreator
        type: action
        action: FeatureCreator
        with:
          creator: |
            [
              #{
                cityGmlPath: env.get("cityGmlPath"),
                cityCode: env.get("cityCode") ?? file::extract_filename(env.get("cityGmlPath"))[0..5],
                codelists: env.get("codelistsPath") ?? env.get("codelists"),
                schemas: env.get("schemasPath") ?? env.get("schemas"),
              },
            ]

      - id: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        name: FolderAndFilePathReader
        type: subGraph
        subGraphId: c6863b71-953b-4d15-af56-396fc93fc617

      - id: ded2e272-e05c-4918-86b3-aa9f763da6e6
        name: FeatureReaderByCityGml
        type: action
        action: FeatureCityGmlReader
        with:
          codelistsPath: env.get("__value").codelists
          dataset: |
            env.get("__value")["path"]

      - id: 3820b7e2-a1ca-436b-acb0-72b907c8b246
        name: AttributeFlattener
        type: action
        action: PLATEAU4.AttributeFlattener

      - id: a7c3e1d2-5f8b-4a6c-9e0d-1b2c3d4e5f60
        name: TwoDimensionForcer
        type: action
        action: TwoDimensionForcer

      - id: 8510992d-2546-4e89-a09b-f31ff435bbb7
        name: FeatureFilterByPackage
        type: action
        action: FeatureFilter
        with:
          conditions:
            - expr: |
                env.get("__value")["package"] == "luse"
              outputPort: luse
            - expr: |
                env.get("__value")["package"] == "lsld"
              outputPort: lsld

      # LUSE processing branch
      - id: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        name: AttributeMapperLuse
        type: action
        action: AttributeMapper
        with:
          mappers:
            - attribute: meshcode
              expr: |
                file::extract_filename_without_ext(env.get("__value")["path"]).split("_")[0]
            - attribute: city_code
              valueAttribute: cityCode
            - attribute: city_name
              valueAttribute: cityName
            - attribute: feature_type
              valueAttribute: featureType
            - attribute: gml_id
              valueAttribute: gmlId
            - attribute: luse_class
              expr: |
                env.get("__value")["luse:class"]
            - attribute: luse_usage
              expr: |
                env.get("__value")["luse:usage"]
            - attribute: core_creationDate
              expr: |
                env.get("__value")["core:creationDate"]
            - attribute: uro_urbanPlanType
              expr: |
                env.get("__value")["uro:LandUseDetailAttribute_uro:urbanPlanType"]
            - attribute: uro_prefecture
              expr: |
                env.get("__value")["uro:LandUseDetailAttribute_uro:prefecture"]
            - attribute: uro_city
              expr: |
                env.get("__value")["uro:LandUseDetailAttribute_uro:city"]
            - attribute: uro_surveyYear
              expr: |
                env.get("__value")["uro:LandUseDetailAttribute_uro:surveyYear"]
            - attribute: uro_areaInSquareMeter
              expr: |
                env.get("__value")["uro:LandUseDetailAttribute_uro:areaInSquareMeter"]
            - attribute: uro_orgLandUse
              expr: |
                env.get("__value")["uro:LandUseDetailAttribute_uro:orgLandUse"]
            - attribute: uro_geometrySrcDescLod1
              expr: |
                env.get("__value")["uro:DataQualityAttribute_uro:geometrySrcDescLod1"]
            - attribute: attributes
              valueAttribute: attributes

      - id: b4862d31-4bb2-49b1-8f0d-6d58dd4cb385
        name: MVTWriterLuse
        type: action
        action: MVTWriter
        with:
          layerName: |
            "luse"
          minZoom: 8
          maxZoom: 16
          extent: 65536
          output: |
            file::join_path(env.get("workerArtifactPath"), "luse")
          compressOutput: |
            let artifact = env.get("workerArtifactPath");
            let city_gml = file::extract_filename_without_ext(env.get("cityGmlPath"));
            if city_gml.ends_with("_luse") {
              city_gml = city_gml.sub_string(0, city_gml.len() - 5);
            }
            file::join_path(artifact, city_gml + "_luse_mvt.zip")

      # LSLD processing branch
      - id: 7a1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d
        name: AttributeMapperLsld
        type: action
        action: AttributeMapper
        with:
          mappers:
            - attribute: meshcode
              expr: |
                file::extract_filename_without_ext(env.get("__value")["path"]).split("_")[0]
            - attribute: city_code
              valueAttribute: cityCode
            - attribute: city_name
              valueAttribute: cityName
            - attribute: feature_type
              valueAttribute: featureType
            - attribute: gml_id
              valueAttribute: gmlId
            - attribute: core_creationDate
              expr: |
                env.get("__value")["core:creationDate"]
            - attribute: urf_validFrom
              expr: |
                env.get("__value")["urf:validFrom"]
            - attribute: urf_prefecture
              expr: |
                env.get("__value")["urf:prefecture"]
            - attribute: urf_location
              expr: |
                env.get("__value")["urf:location"]
            - attribute: urf_disasterType
              expr: |
                env.get("__value")["urf:disasterType"]
            - attribute: urf_areaType
              expr: |
                env.get("__value")["urf:areaType"]
            - attribute: urf_zoneNumber
              expr: |
                env.get("__value")["urf:zoneNumber"]
            - attribute: urf_zoneName
              expr: |
                env.get("__value")["urf:zoneName"]
            - attribute: urf_status
              expr: |
                env.get("__value")["urf:status"]
            - attribute: uro_geometrySrcDescLod1
              expr: |
                env.get("__value")["uro:DataQualityAttribute_uro:geometrySrcDescLod1"]
            - attribute: attributes
              valueAttribute: attributes
            - attribute: sort_order
              expr: |
                let area_type = env.get("__value")["urf:areaType_code"];
                if area_type == () { area_type = env.get("__value")["urf:areaType"]; }
                if area_type == "1" || area_type == 1 { 1 }
                else if area_type == "2" || area_type == 2 { 2 }
                else if area_type == "3" || area_type == 3 { 3 }
                else if area_type == "4" || area_type == 4 { 4 }
                else { 999 }

      - id: 9c3d4e5f-6a7b-8c9d-0e1f-2a3b4c5d6e7f
        name: FeatureSorterLsld
        type: action
        action: FeatureSorter
        with:
          attributes:
            - sort_order
          order: ascending

      - id: 4b5c6d7e-8f9a-0b1c-2d3e-4f5a6b7c8d9e
        name: AttributeManagerLsldRemoveSortOrder
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: sort_order
              method: remove

      - id: 0d4e5f6a-7b8c-9d0e-1f2a-3b4c5d6e7f8a
        name: MVTWriterLsld
        type: action
        action: MVTWriter
        with:
          layerName: |
            "lsld"
          minZoom: 8
          maxZoom: 16
          extent: 65536
          output: |
            file::join_path(env.get("workerArtifactPath"), "lsld")
          compressOutput: |
            let artifact = env.get("workerArtifactPath");
            let city_gml = file::extract_filename_without_ext(env.get("cityGmlPath"));
            if city_gml.ends_with("_lsld") {
              city_gml = city_gml.sub_string(0, city_gml.len() - 5);
            }
            file::join_path(artifact, city_gml + "_lsld_mvt.zip")

    edges:
      - id: 5ebf24ab-1d98-49d5-8f58-eb7c18d27244
        from: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        to: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        fromPort: default
        toPort: default
      - id: 7b81f501-3f07-4cec-bf9b-9cefcebdf47d
        from: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        to: ded2e272-e05c-4918-86b3-aa9f763da6e6
        fromPort: default
        toPort: default
      - id: ad52c3e6-68ff-4844-a7b2-d302fc0aef14
        from: ded2e272-e05c-4918-86b3-aa9f763da6e6
        to: 3820b7e2-a1ca-436b-acb0-72b907c8b246
        fromPort: default
        toPort: default
      - id: c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f
        from: 3820b7e2-a1ca-436b-acb0-72b907c8b246
        to: a7c3e1d2-5f8b-4a6c-9e0d-1b2c3d4e5f60
        fromPort: default
        toPort: default
      - id: 1e29f24a-620b-472c-805f-8295bf5920c2
        from: a7c3e1d2-5f8b-4a6c-9e0d-1b2c3d4e5f60
        to: 8510992d-2546-4e89-a09b-f31ff435bbb7
        fromPort: default
        toPort: default
      - id: 28abe7a9-8bdc-414d-b15e-90cb2a451a70
        from: 8510992d-2546-4e89-a09b-f31ff435bbb7
        to: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        fromPort: luse
        toPort: default
      - id: e862f11a-88a6-4c1b-a743-ba80253039df
        from: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        to: b4862d31-4bb2-49b1-8f0d-6d58dd4cb385
        fromPort: default
        toPort: default

      # LSLD branch edges
      - id: 1e2f3a4b-5c6d-7e8f-9a0b-1c2d3e4f5a6b
        from: 8510992d-2546-4e89-a09b-f31ff435bbb7
        to: 7a1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d
        fromPort: lsld
        toPort: default
      - id: 2f3a4b5c-6d7e-8f9a-0b1c-2d3e4f5a6b7c
        from: 7a1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d
        to: 9c3d4e5f-6a7b-8c9d-0e1f-2a3b4c5d6e7f
        fromPort: default
        toPort: default
      - id: 3a4b5c6d-7e8f-9a0b-1c2d-3e4f5a6b7c8d
        from: 9c3d4e5f-6a7b-8c9d-0e1f-2a3b4c5d6e7f
        to: 4b5c6d7e-8f9a-0b1c-2d3e-4f5a6b7c8d9e
        fromPort: default
        toPort: default
      - id: 5c6d7e8f-9a0b-1c2d-3e4f-5a6b7c8d9e0f
        from: 4b5c6d7e-8f9a-0b1c-2d3e-4f5a6b7c8d9e
        to: 0d4e5f6a-7b8c-9d0e-1f2a-3b4c5d6e7f8a
        fromPort: default
        toPort: default

