# yaml-language-server: $schema=https://raw.githubusercontent.com/reearth/reearth-flow/main/engine/schema/workflow.json
id: 3e39d990-0a80-47df-9be9-3bf7c0068b5a
name: "PLATEAU4-DataConvert-04-luse-lsld-workflow"
entryGraphId: 0e500d5a-7882-4835-9285-9763ba8b5b65
with:
  cityGmlPath:
  codelists:
  schemas:
  cityCode:
  targetPackages:
    - luse
    - lsld
  outputPath:
graphs:
  - !include ../../../../graphs/plateau4/folder_and_file_path_reader.yml
  - id: 0e500d5a-7882-4835-9285-9763ba8b5b65
    name: entry_point
    nodes:
      - id: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        name: FeatureCreator
        type: action
        action: FeatureCreator
        with:
          creator: |
            [
              #{
                cityGmlPath: env.get("cityGmlPath"),
                cityCode: env.get("cityCode") ?? file::extract_filename(env.get("cityGmlPath"))[0..5],
                codelists: env.get("codelists"),
                schemas: env.get("schemas"),
              },
            ]

      - id: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        name: FolderAndFilePathReader
        type: subGraph
        subGraphId: c6863b71-953b-4d15-af56-396fc93fc617

      - id: ded2e272-e05c-4918-86b3-aa9f763da6e6
        name: FeatureReaderByCityGml
        type: action
        action: FeatureReader
        with:
          format: citygml
          dataset: |
            env.get("__value")["path"]

      - id: dc498449-5478-4bff-abaa-59f2d160925f
        name: PLATEAU4.MaxLodExtractor
        type: action
        action: PLATEAU4.MaxLodExtractor
        with:
          cityGmlPathAttribute: path
          maxLodAttribute: maxLod

      - id: 1fb4ce1c-538a-436d-8dfa-79185e032de3
        name: AttributeAggregatorByMaxLod
        type: action
        action: AttributeAggregator
        with:
          aggregateAttributes:
          - newAttribute: file
            attributeValue: |
              file::extract_filename(env.get("__value")["path"])
          - newAttribute: type
            attributeValue: |
              env.get("__feature_type")
          - newAttribute: maxLod
            attributeValue: |
              env.get("__value").maxLod
          calculation: |
            1
          calculationAttribute: count
          method: count

      - id: 52ff7b3c-5fbb-4ad2-86d9-5df50429e3b4
        name: AttributeMapperByMaxLod
        type: action
        action: AttributeMapper
        with:
          mappers:
          - attribute: code
            expr: |
              env.get("__value").file[0..6]
          - attribute: type
            expr: |
              env.get("__value")["type"].split(":")[0]
          - attribute: maxLod
            expr: |
              env.get("__value").maxLod
          - attribute: file
            expr: |
              env.get("__value").file

      - id: 65074ffc-9113-4fbf-8957-9ba1de4c56ab
        name: FileWriterTsvFilePath
        type: action
        action: FileWriter
        with:
          format: csv
          output: |
            file::join_path(env.get("outputPath"), "maxLod.csv")

      - id: 8510992d-2546-4e89-a09b-f31ff435bbb7
        name: FeatureFilterByPackage
        type: action
        action: FeatureFilter
        with:
          conditions:
            - expr: |
                env.get("__value")["package"] == "luse"
              outputPort: luse
            - expr: |
                env.get("__value")["package"] == "lsld"
              outputPort: lsld

      - id: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        name: AttributeMapperLuse
        type: action
        action: AttributeMapper
        with:
          mappers:
            - attribute: meshcode
              valueAttribute: meshCode
            - attribute: city_code
              valueAttribute: cityCode
            - attribute: city_name
              valueAttribute: cityName
            - attribute: feature_type
              valueAttribute: gmlName
            - attribute: gml_id
              valueAttribute: gmlId
            - attribute: luse_class
              parentAttribute: cityGmlAttributes
              childAttribute: luse:class

      - id: b4862d31-4bb2-49b1-8f0d-6d58dd4cb385
        name: MVTWriter
        type: action
        action: MVTWriter
        with:
          layerName: |
            "luse"
          minZoom: 8
          maxZoom: 16
          output: |
            file::join_path(env.get("outputPath"), "luse")
          compressOutput: |
            file::join_path(env.get("outputPath"), "" + file::extract_filename_without_ext(env.get("cityGmlPath")) + "_luse_mvt.zip")

    edges:
      - id: 5ebf24ab-1d98-49d5-8f58-eb7c18d27244
        from: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        to: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        fromPort: default
        toPort: default
      - id: 7b81f501-3f07-4cec-bf9b-9cefcebdf47d
        from: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        to: ded2e272-e05c-4918-86b3-aa9f763da6e6
        fromPort: default
        toPort: default
      - id: cf845867-6ffc-4b83-9fd5-e376a22470e2
        from: ded2e272-e05c-4918-86b3-aa9f763da6e6
        to: dc498449-5478-4bff-abaa-59f2d160925f
        fromPort: default
        toPort: default
      - id: 046c94ea-9937-4439-b5f8-c8a616f6599d
        from: dc498449-5478-4bff-abaa-59f2d160925f
        to: 1fb4ce1c-538a-436d-8dfa-79185e032de3
        fromPort: default
        toPort: default
      - id: 59c14dab-0e56-4f90-85e6-0c8cfa6d1d14
        from: 1fb4ce1c-538a-436d-8dfa-79185e032de3
        to: 52ff7b3c-5fbb-4ad2-86d9-5df50429e3b4
        fromPort: default
        toPort: default
      - id: 993360df-5cfd-4525-9626-bfe13fa62117
        from: 52ff7b3c-5fbb-4ad2-86d9-5df50429e3b4
        to: 65074ffc-9113-4fbf-8957-9ba1de4c56ab
        fromPort: default
        toPort: default
      - id: ad52c3e6-68ff-4844-a7b2-d302fc0aef14
        from: ded2e272-e05c-4918-86b3-aa9f763da6e6
        to: 8510992d-2546-4e89-a09b-f31ff435bbb7
        fromPort: default
        toPort: default
      - id: 1e29f24a-620b-472c-805f-8295bf5920c2
        from: 8510992d-2546-4e89-a09b-f31ff435bbb7
        to: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        fromPort: luse
        toPort: default
      - id: e862f11a-88a6-4c1b-a743-ba80253039df
        from: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        to: b4862d31-4bb2-49b1-8f0d-6d58dd4cb385
        fromPort: default
        toPort: default
