# yaml-language-server: $schema=https://raw.githubusercontent.com/reearth/reearth-flow/main/engine/schema/workflow.json
id: c5f20714-1b35-408a-a203-aada363b4179
name: "DataConvert-08-ubld-workflow"
entryGraphId: 49aefc85-168d-4190-b7e2-dc0d58ee44e3
with:
  cityGmlPath:
  cityCode:
  codelistsPath:
  schemasPath:
  schemaJson: !include ../../../config/schema.txt
  targetPackages:
    - ubld
  addNsprefixToFeatureTypes: true
  extractDmGeometryAsXmlFragment: false
  outputPath:
graphs:
  - !include ../../../graphs/folder_and_file_path_reader.yml
  - id: 49aefc85-168d-4190-b7e2-dc0d58ee44e3
    name: entry_point
    nodes:
      - id: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        name: FeatureCreator
        type: action
        action: FeatureCreator
        with:
          creator: |
            [
              #{
                cityGmlPath: env.get("cityGmlPath")
              },
            ]

      - id: d5fa7732-ef20-45ec-a331-e6d57571354b
        name: FolderAndfilePathReader
        type: subGraph
        subGraphId: c6863b71-953b-4d15-af56-396fc93fc617

      - id: 254d6287-7649-4647-9ab5-0c1c423f356a
        name: FeatureReaderByCityGml
        type: action
        action: FeatureReader
        with:
          format: citygml
          dataset: |
            env.get("__value").cityGmlPath

      - id: 0feb3175-9723-4c06-9d55-0b57490660d5
        name: FeatureTypeFilterByUndergroundBuilding
        type: action
        action: FeatureTypeFilter
        with:
          targetTypes:
            - "uro:UndergroundBuilding"

      - id: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        name: AttributeMapperUbld
        type: action
        action: AttributeMapper
        with:
          mappers:
            - attribute: meshcode
              valueAttribute: meshCode
            - attribute: city_code
              valueAttribute: cityCode
            - attribute: city_name
              valueAttribute: cityName
            - attribute: feature_type
              valueAttribute: gmlName
            - attribute: gml_id
              valueAttribute: gmlId

      - id: 92b4dc62-675d-4365-a012-20ad1980bb98
        name: Offsetter
        type: action
        action: Offsetter
        with:
          offsetZ: 4.0

      - id: 928e21d9-fc30-4876-ba03-41338cfa47ed
        name: VerticalReprojectorUbld
        type: action
        action: VerticalReprojector
        with:
          reprojectorType: jgd2011ToWgs84

      - id: b4862d31-4bb2-49b1-8f0d-6d58dd4cb385
        name: Cesium3DTilesWriterByUbld
        type: action
        action: Cesium3DTilesWriter
        with:
          minZoom: 15
          maxZoom: 18
          attachTexture: true
          output: |
             file::join_path(env.get("outputPath"), "ubld")

    edges:
      - id: 84a25947-9abb-4983-925a-910272b42bc0
        from: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        to: d5fa7732-ef20-45ec-a331-e6d57571354b
        fromPort: default
        toPort: default
      - id: a4751655-5956-4e27-a976-e35f8914ad31
        from: d5fa7732-ef20-45ec-a331-e6d57571354b
        to: 254d6287-7649-4647-9ab5-0c1c423f356a
        fromPort: default
        toPort: default
      - id: 86ec56d6-cefb-48ca-a72d-0c57a33d198a
        from: 254d6287-7649-4647-9ab5-0c1c423f356a
        to: 0feb3175-9723-4c06-9d55-0b57490660d5
        fromPort: default
        toPort: default
      - id: afc70bd9-8467-4997-ad1a-bab3a0593278
        from: 0feb3175-9723-4c06-9d55-0b57490660d5
        to: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        fromPort: default
        toPort: default
      - id: 6b857fe4-c6c1-4ed3-ac6e-f7eef19c9248
        from: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        to: 92b4dc62-675d-4365-a012-20ad1980bb98
        fromPort: default
        toPort: default
      - id: 703fbdd0-516f-4201-b2ad-5575ab684fbc
        from: 92b4dc62-675d-4365-a012-20ad1980bb98
        to: 928e21d9-fc30-4876-ba03-41338cfa47ed
        fromPort: default
        toPort: default
      - id: e862f11a-88a6-4c1b-a743-ba80253039df
        from: 928e21d9-fc30-4876-ba03-41338cfa47ed
        to: b4862d31-4bb2-49b1-8f0d-6d58dd4cb385
        fromPort: default
        toPort: default
