#!/usr/bin/env python3
"""Emit the per-class CityGML 2.0 content model as Rust.

CityGML declares each class's properties as an `xs:sequence`, so a document that
carries the right elements in the wrong order is still invalid. The writer needs
that order to emit correctly, and the order is a fact of the schema rather than
something to hand-maintain, so it is generated from the schemas vendored beside
this script.

Run via `cargo make update-citygml-content-model`.
"""

import glob
import os
import re
import sys
import xml.etree.ElementTree as ET

XS = "{http://www.w3.org/2001/XMLSchema}"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(
    HERE, "..", "..", "runtime", "action-sink", "src", "file", "citygml", "content_model.rs"
)

# The writer's `CityObjectType` variants, paired with the complexType each maps to.
CLASSES = [
    ("Building", "BuildingType"),
    ("BuildingPart", "BuildingPartType"),
    ("Road", "RoadType"),
    ("Railway", "RailwayType"),
    ("Track", "TrackType"),
    ("Square", "SquareType"),
    ("Bridge", "BridgeType"),
    ("BridgePart", "BridgePartType"),
    ("Tunnel", "TunnelType"),
    ("TunnelPart", "TunnelPartType"),
    ("WaterBody", "WaterBodyType"),
    ("LandUse", "LandUseType"),
    ("SolitaryVegetationObject", "SolitaryVegetationObjectType"),
    ("PlantCover", "PlantCoverType"),
    ("CityFurniture", "CityFurnitureType"),
    ("ReliefFeature", "ReliefFeatureType"),
    ("GenericCityObject", "GenericCityObjectType"),
]


def harvest():
    """Every named complexType, as (base type, its own element names in order)."""
    types = {}
    pattern = os.path.join(HERE, "schemas", "schemas.opengis.net", "citygml", "**", "*.xsd")
    for path in glob.glob(pattern, recursive=True):
        try:
            root = ET.parse(path).getroot()
        except ET.ParseError:
            continue
        for ct in root.iter(XS + "complexType"):
            name = ct.get("name")
            if not name:
                continue
            base = next((e.get("base") for e in ct.iter(XS + "extension")), None)
            names = [e.get("name") for e in ct.iter(XS + "element") if e.get("name")]
            types[name] = (base, names)
    return types


def chain(types, tname, seen=()):
    """Properties in document order: inherited ones precede the type's own."""
    tname = tname.split(":")[-1]
    if tname not in types or tname in seen:
        return []
    base, names = types[tname]
    inherited = chain(types, base, seen + (tname,)) if base and not base.startswith("gml:") else []
    return inherited + names


def main():
    types = harvest()
    if not types:
        sys.exit("no schemas found: expected them beside this script under schemas/")

    rows = []
    for variant, tname in CLASSES:
        props = chain(types, tname)
        if not props:
            sys.exit(f"could not resolve {tname}; are the vendored schemas complete?")
        rows.append((variant, props))

    body = [
        "// @generated by tools/citygml-schema/generate_content_model.py",
        "// Run `cargo make update-citygml-content-model` after changing that script",
        "// or the vendored schemas. Do not edit by hand.",
        "",
        "use super::model::CityObjectType;",
        "",
        "/// Every property CityGML 2.0 declares for `city_type`, in the order its",
        "/// `xs:sequence` requires. Emitting out of this order is invalid even when",
        "/// every element is individually legal.",
        "pub(crate) fn content_model(city_type: CityObjectType) -> &'static [&'static str] {",
        "    match city_type {",
    ]
    for variant, props in rows:
        body.append(f"        CityObjectType::{variant} => &[")
        line = "           "
        for prop in props:
            piece = f' "{prop}",'
            if len(line) + len(piece) > 96:
                body.append(line)
                line = "           "
            line += piece
        body.append(line)
        body.append("        ],")
    body += ["    }", "}", ""]

    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write("\n".join(body))

    total = sum(len(p) for _, p in rows)
    print(f"wrote {os.path.relpath(OUT, os.path.join(HERE, '..', '..'))}: "
          f"{total} properties across {len(rows)} classes")


if __name__ == "__main__":
    main()
