[package]
description = "Re:Earth Flow action log library"
name = "reearth-flow-action-log"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
reearth-flow-common.workspace = true

anyhow.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
slog-async = "2.8.0"
slog-term = "2.9.1"
slog.workspace = true
sloggers = {version = "2.2.0", default-features = false}
thiserror.workspace = true
tokio-stream.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
