//! Generates the table of geodetic grids compiled into the crate.
//!
//! `grids/MANIFEST.tsv` names the set and records the size and SHA-256 of each
//! file. This checks `grids/` against those rows and emits the `include_bytes!`
//! entries that embed them.

use std::collections::BTreeSet;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use sha2::{Digest, Sha256};

/// A row of `grids/MANIFEST.tsv`: a grid file and the bytes it must hold.
struct Row {
    /// The PROJ-data file name, which is also what `proj.db` refers to it by.
    name: String,
    /// The file's length in bytes.
    size: u64,
    /// The file's SHA-256, as lowercase hex.
    sha256: String,
}

fn main() {
    let root = env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR");
    let grids = Path::new(&root).join("grids");
    let manifest = grids.join("MANIFEST.tsv");
    println!("cargo::rerun-if-changed={}", grids.display());

    let text =
        fs::read_to_string(&manifest).unwrap_or_else(|e| panic!("{}: {e}", manifest.display()));
    let rows = parse(&text).unwrap_or_else(|e| panic!("{}: {e}", manifest.display()));

    let mut problems: Vec<String> = rows
        .iter()
        .filter_map(|row| verify(&grids.join(&row.name), row).err())
        .collect();
    problems.extend(unlisted(&grids, &rows));
    assert!(
        problems.is_empty(),
        "{} does not describe {}:\n  {}",
        manifest.display(),
        grids.display(),
        problems.join("\n  ")
    );

    let mut table = String::from(
        "/// The embedded set: current-generation geoid models, one per national\n\
         /// vertical datum, plus the global EGM96 fallback. Generated by `build.rs`\n\
         /// from `grids/MANIFEST.tsv`.\n\
         static EMBEDDED_GRIDS: &[EmbeddedGrid] = &[\n",
    );
    for row in &rows {
        let path = grids.join(&row.name);
        let path = path
            .to_str()
            .unwrap_or_else(|| panic!("{} is not valid UTF-8", path.display()));
        println!("cargo::rerun-if-changed={path}");
        writeln!(
            table,
            "    EmbeddedGrid {{ name: {:?}, bytes: include_bytes!({path:?}) }},",
            row.name
        )
        .expect("writing to a String cannot fail");
    }
    table.push_str("];\n");

    let out =
        Path::new(&env::var("OUT_DIR").expect("cargo sets OUT_DIR")).join("embedded_grids.rs");
    fs::write(&out, table).unwrap_or_else(|e| panic!("{}: {e}", out.display()));
}

/// Read the manifest rows, which follow the version and column headers. Each
/// must carry at least a name, a size and a SHA-256.
fn parse(text: &str) -> Result<Vec<Row>, String> {
    let mut rows = Vec::new();
    for line in text.lines().skip(2).filter(|line| !line.trim().is_empty()) {
        let mut fields = line.split('\t');
        let name = fields.next().expect("splitting yields at least one field");
        let (size, sha256) = (
            fields.next().unwrap_or_default(),
            fields.next().unwrap_or_default(),
        );
        if size.is_empty() || sha256.is_empty() {
            return Err(format!(
                "{name} has no size or SHA-256; run grids/update.sh to fetch it"
            ));
        }
        rows.push(Row {
            name: name.to_owned(),
            size: size
                .parse()
                .map_err(|e| format!("{name} has an unreadable size: {e}"))?,
            sha256: sha256.to_owned(),
        });
    }
    if rows.is_empty() {
        return Err("lists no grids".to_owned());
    }
    Ok(rows)
}

/// Check that `path` holds exactly the bytes `row` records.
fn verify(path: &Path, row: &Row) -> Result<(), String> {
    let bytes = fs::read(path).map_err(|e| format!("{}: {e}", row.name))?;
    if bytes.len() as u64 != row.size {
        return Err(format!(
            "{}: manifest records {} bytes, the file holds {}",
            row.name,
            row.size,
            bytes.len()
        ));
    }
    let digest = hex::encode(Sha256::digest(&bytes));
    if digest != row.sha256 {
        return Err(format!(
            "{}: manifest records SHA-256 {}, the file is {digest}",
            row.name, row.sha256
        ));
    }
    Ok(())
}

/// The grid files in `grids` that no manifest row names.
fn unlisted(grids: &Path, rows: &[Row]) -> Vec<String> {
    let listed: BTreeSet<&str> = rows.iter().map(|row| row.name.as_str()).collect();
    let entries = fs::read_dir(grids).unwrap_or_else(|e| panic!("{}: {e}", grids.display()));
    let mut extra: Vec<String> = entries
        .map(|entry| {
            entry
                .unwrap_or_else(|e| panic!("{}: {e}", grids.display()))
                .file_name()
                .to_string_lossy()
                .into_owned()
        })
        .filter(|name| name.ends_with(".tif") && !listed.contains(name.as_str()))
        .map(|name| format!("{name}: present but not listed"))
        .collect();
    extra.sort();
    extra
}
