//! Generates the table of geodetic grids compiled into the crate.
//!
//! `grids/MANIFEST.tsv`, written by `grids/update.sh`, is the embedded set. This
//! reads the grid names from it and emits the `include_bytes!` entries that
//! embed them, so the set is authored in one place only.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

fn main() {
    let root = env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR");
    let grids = Path::new(&root).join("grids");
    let manifest = grids.join("MANIFEST.tsv");
    println!("cargo::rerun-if-changed={}", manifest.display());

    let text =
        fs::read_to_string(&manifest).unwrap_or_else(|e| panic!("{}: {e}", manifest.display()));

    let mut table = String::from(
        "/// The embedded set: current-generation geoid models, one per national\n\
         /// vertical datum, plus the global EGM96 fallback. Generated by `build.rs`\n\
         /// from `grids/MANIFEST.tsv`, which `grids/update.sh` writes.\n\
         static EMBEDDED_GRIDS: &[EmbeddedGrid] = &[\n",
    );
    for line in text.lines().skip(2).filter(|line| !line.trim().is_empty()) {
        let name = line.split('\t').next().expect("manifest row has a name");
        let path = grids.join(name);
        let path = path
            .to_str()
            .unwrap_or_else(|| panic!("{} is not valid UTF-8", path.display()));
        assert!(
            Path::new(path).is_file(),
            "{} lists {name}, which is not in {}",
            manifest.display(),
            grids.display()
        );
        writeln!(
            table,
            "    EmbeddedGrid {{ name: {name:?}, bytes: include_bytes!({path:?}) }},"
        )
        .expect("writing to a String cannot fail");
    }
    table.push_str("];\n");

    let out =
        Path::new(&env::var("OUT_DIR").expect("cargo sets OUT_DIR")).join("embedded_grids.rs");
    fs::write(&out, table).unwrap_or_else(|e| panic!("{}: {e}", out.display()));
}
