version: "2"
sql:
  - engine: "postgresql"
    schema: "db/migrations"
    queries: "query"
    gen:
      go:
        package: "gen"
        out: "gen"
        sql_package: "pgx/v5"
        emit_json_tags: false
        emit_interface: true
        emit_exact_table_names: false
        emit_pointers_for_null_types: true
        overrides:
          - db_type: "timestamptz"
            go_type: "time.Time"
          - db_type: "timestamptz"
            nullable: true
            go_type:
              import: "time"
              type: "Time"
              pointer: true
          - db_type: "text"
            nullable: true
            go_type:
              type: "string"
              pointer: true
