version: "2"
sql:
  - engine: "postgresql"
    schema: "db/migrations"
    queries: "query"
    gen:
      go:
        package: "gen"
        out: "gen"
        sql_package: "pgx/v5"
        emit_json_tags: false
        emit_interface: false
        emit_exact_table_names: false
