# yaml-language-server: $schema=https://raw.githubusercontent.com/reearth/reearth-flow/main/engine/schema/workflow.json
id: d6a556db-dfac-4ca1-9275-c490ef2d1ad8
name: "PLATEAU4-DataConvert-02-tran-rwy-trk-squr-wwy"
entryGraphId: 34bf873b-3364-46b0-8153-efeb9568bb3c
with:
  cityGmlPath:
  cityCode:
  codelistsPath:
  schemasPath:
  targetPackages:
    - tran
    - rwy
    - trk
    - squr
    - wwy
  outputPath:
graphs:
  - !include ../../../../graphs/plateau4/folder_and_file_path_reader.yml
  - id: 34bf873b-3364-46b0-8153-efeb9568bb3c
    name: entry_point
    nodes:
      - id: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        name: FeatureCreator
        type: action
        action: FeatureCreator
        with:
          creator: |
            [
              #{
                cityGmlPath: env.get("cityGmlPath"),
                cityCode: env.get("cityCode") ?? file::extract_filename(env.get("cityGmlPath"))[0..5],
              },
            ]

      - id: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        name: FolderAndFilePathReader
        type: subGraph
        subGraphId: c6863b71-953b-4d15-af56-396fc93fc617

      - id: ded2e272-e05c-4918-86b3-aa9f763da6e6
        name: FeatureReaderByCityGml
        type: action
        action: FeatureCityGmlReader
        with:
          flatten: true
          format: citygml
          dataset: |
            env.get("__value")["path"]

      - id: c32a279d-97be-4584-b282-4d65627b1132
        name: FeatureLodFilter
        type: action
        action: FeatureLodFilter
        with:
          filterKey: path

      - id: 8f3a2b1c-4d5e-6f7a-8b9c-0d1e2f3a4b5c
        name: FeatureTypeFilterTrafficArea
        type: action
        action: FeatureTypeFilter
        with:
          targetTypes:
            - "tran:TrafficArea"
            - "tran:AuxiliaryTrafficArea"

      - id: 1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d
        name: FeatureTypeFilterTrafficAreaLod3
        type: action
        action: FeatureTypeFilter
        with:
          targetTypes:
            - "tran:TrafficArea"
            - "tran:AuxiliaryTrafficArea"

      - id: 2ccf7b99-4123-446e-8ff7-049be1c604c7
        name: AttributeMapperByLod0-2
        type: action
        action: AttributeMapper
        with:
          mappers:
            - attribute: meshcode
              expr: |
                let file = file::extract_filename(env.get("__value")["path"]);
                file[0..8]
            - attribute: city_code
              valueAttribute: cityCode
            - attribute: city_name
              valueAttribute: cityName
            - attribute: feature_type
              valueAttribute: gmlName
            - attribute: gml_id
              expr: |
                env.get("__feature_id")
            - attribute: lod
              expr: |
                env.get("__lod")
            - attribute: _folder_package
              valueAttribute: package

      - id: 1f8b3c4e-5a2d-4e1f-9b7c-3d5e6f8a9b0c
        name: FeatureSorter
        type: action
        action: FeatureSorter
        with:
          attributes:
            # sorting is required by MVT writer and dissolver
            # must sort by output path, not feature type
            - _folder_package
            - lod
          order: ascending

      # corresponding to FME's 2DForcer_lod0-2
      - id: 8a9b7c6d-5e4f-3a2b-1c0d-9e8f7a6b5c4d
        name: TwoDimensionForcer
        type: action
        action: TwoDimensionForcer

      # Filter geometry types: polygons go to Dissolver, linestrings bypass
      - id: 6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c
        name: GeometryFilter
        type: action
        action: GeometryFilter
        with:
          filterType: geometryType

      - id: 9f8e7d6c-5b4a-3c2d-1e0f-8a9b7c6d5e4f
        name: Dissolver
        type: action
        action: Dissolver
        with:
          groupBy:
            - gml_id
            - _folder_package
            - lod
          attributeAccumulationMode: useOne

      - id: b4c8d9e0-f1a2-3b4c-5d6e-7f8a9b0c1d2e
        name: FeatureSorterPreMVT
        type: action
        action: FeatureSorter
        with:
          attributes:
            - _folder_package
            - lod
            - feature_type
          order: ascending

      - id: 7a17c4f9-dd4d-44b0-936c-50c394272016
        name: MVTWriter
        type: action
        action: MVTWriter
        with:
          layerName: |
            env.get("__value").feature_type.split(":")[1]
          minZoom: 8
          maxZoom: 16
          output: |
            file::join_path(env.get("outputPath"), env.get("__value")._folder_package + "_lod" + env.get("__value").lod)

    edges:
      - id: 5ebf24ab-1d98-49d5-8f58-eb7c18d27244
        from: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        to: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        fromPort: default
        toPort: default
      - id: 64196428-ea1b-4177-9d66-28331fad14f8
        from: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        to: ded2e272-e05c-4918-86b3-aa9f763da6e6
        fromPort: default
        toPort: default
      - id: ad52c3e6-68ff-4844-a7b2-d302fc0aef14
        from: ded2e272-e05c-4918-86b3-aa9f763da6e6
        to: c32a279d-97be-4584-b282-4d65627b1132
        fromPort: default
        toPort: default
      - id: 90f518e2-3ca0-404f-821c-5dffe4e57597
        from: c32a279d-97be-4584-b282-4d65627b1132
        to: 2ccf7b99-4123-446e-8ff7-049be1c604c7
        fromPort: up_to_lod0
        toPort: default
      - id: 83c68df9-a61b-4cad-8f64-ea20186e9db1
        from: c32a279d-97be-4584-b282-4d65627b1132
        to: 2ccf7b99-4123-446e-8ff7-049be1c604c7
        fromPort: up_to_lod1
        toPort: default
      - id: 7303c673-ccf3-4075-9eec-97176ced4b86
        from: c32a279d-97be-4584-b282-4d65627b1132
        to: 8f3a2b1c-4d5e-6f7a-8b9c-0d1e2f3a4b5c
        fromPort: up_to_lod2
        toPort: default
      - id: 9a8b7c6d-5e4f-3a2b-1c0d-9e8f7a6b5c4d
        from: 8f3a2b1c-4d5e-6f7a-8b9c-0d1e2f3a4b5c
        to: 2ccf7b99-4123-446e-8ff7-049be1c604c7
        fromPort: default
        toPort: default
      - id: 2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e
        from: c32a279d-97be-4584-b282-4d65627b1132
        to: 1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d
        fromPort: up_to_lod3
        toPort: default
      - id: 841f1bed-a4d3-4425-a754-4f0dd7461ead
        from: 2ccf7b99-4123-446e-8ff7-049be1c604c7
        to: 1f8b3c4e-5a2d-4e1f-9b7c-3d5e6f8a9b0c
        fromPort: default
        toPort: default
      - id: 3c7d9e2f-4a5b-6c8d-9e0f-1a2b3c4d5e6f
        from: 1f8b3c4e-5a2d-4e1f-9b7c-3d5e6f8a9b0c
        to: 8a9b7c6d-5e4f-3a2b-1c0d-9e8f7a6b5c4d
        fromPort: default
        toPort: default
      # TwoDimensionForcer -> GeometryFilter
      - id: 5b6c7d8e-9f0a-1b2c-3d4e-5f6a7b8c9d0e
        from: 8a9b7c6d-5e4f-3a2b-1c0d-9e8f7a6b5c4d
        to: 6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c
        fromPort: default
        toPort: default
      # GeometryFilter (polygon) -> Dissolver
      - id: 8d9e0f1a-2b3c-4d5e-6f7a-8b9c0d1e2f3a
        from: 6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c
        to: 9f8e7d6c-5b4a-3c2d-1e0f-8a9b7c6d5e4f
        fromPort: surface
        toPort: default
      # Dissolver -> FeatureSorterPreMVT
      - id: 4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a
        from: 9f8e7d6c-5b4a-3c2d-1e0f-8a9b7c6d5e4f
        to: b4c8d9e0-f1a2-3b4c-5d6e-7f8a9b0c1d2e
        fromPort: area
        toPort: default
      # GeometryFilter (linestrings) -> FeatureSorterPreMVT
      - id: 9e0f1a2b-3c4d-5e6f-7a8b-9c0d1e2f3a4b
        from: 6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c
        to: b4c8d9e0-f1a2-3b4c-5d6e-7f8a9b0c1d2e
        fromPort: curve
        toPort: default
      # FeatureSorterPreMVT -> MVTWriter
      - id: c1d2e3f4-5a6b-7c8d-9e0f-1a2b3c4d5e6f
        from: b4c8d9e0-f1a2-3b4c-5d6e-7f8a9b0c1d2e
        to: 7a17c4f9-dd4d-44b0-936c-50c394272016
        fromPort: default
        toPort: default