# yaml-language-server: $schema=https://raw.githubusercontent.com/reearth/reearth-flow/main/engine/schema/workflow.json
id: d6a556db-dfac-4ca1-9275-c490ef2d1ad8
name: "PLATEAU4-DataConvert-02-tran-rwy-trk-squr-wwy"
entryGraphId: 34bf873b-3364-46b0-8153-efeb9568bb3c
with:
  cityGmlPath:
  cityCode:
  codelists:
  schemas:
  targetPackages:
    - tran
    - rwy
    - trk
    - squr
    - wwy
  outputPath:
graphs:
  - !include ../../../../graphs/plateau4/folder_and_file_path_reader.yml
  - id: 34bf873b-3364-46b0-8153-efeb9568bb3c
    name: entry_point
    nodes:
      - id: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        name: FeatureCreator
        type: action
        action: FeatureCreator
        with:
          creator: |
            [
              #{
                cityGmlPath: env.get("cityGmlPath"),
                cityCode: env.get("cityCode") ?? file::extract_filename(env.get("cityGmlPath"))[0..5],
                baseCityCode: env.get("cityCode") ?? file::extract_filename(env.get("cityGmlPath"))[0..5],
                codelists: env.get("codelists"),
                schemas: env.get("schemas"),
              },
            ]

      - id: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        name: FolderAndFilePathReader
        type: subGraph
        subGraphId: c6863b71-953b-4d15-af56-396fc93fc617

      - id: ded2e272-e05c-4918-86b3-aa9f763da6e6
        name: FeatureReaderByCityGml
        type: action
        action: FeatureCityGmlReader
        with:
          format: citygml
          dataset: |
            env.get("__value")["path"]

      - id: 4ffbb8a3-371e-4938-aa73-c142f11bb04b
        name: FeatureSorter
        type: action
        action: FeatureSorter
        with:
          attributes:
            - path
          order: ascending

      - id: dc498449-5478-4bff-abaa-59f2d160925f
        name: PLATEAU4.MaxLodExtractor
        type: action
        action: PLATEAU4.MaxLodExtractor
        with:
          cityGmlPathAttribute: path
          maxLodAttribute: maxLod

      - id: 1fb4ce1c-538a-436d-8dfa-79185e032de3
        name: AttributeAggregatorByMaxLod
        type: action
        action: AttributeAggregator
        with:
          aggregateAttributes:
          - newAttribute: file
            attributeValue: |
              file::extract_filename(env.get("__value")["path"])
          - newAttribute: type
            attributeValue: |
              env.get("__feature_type")
          - newAttribute: maxLod
            attributeValue: |
              env.get("__value").maxLod
          calculation: |
            1
          calculationAttribute: count
          method: count

      - id: 52ff7b3c-5fbb-4ad2-86d9-5df50429e3b4
        name: AttributeMapperByMaxLod
        type: action
        action: AttributeMapper
        with:
          mappers:
          - attribute: code
            expr: |
              env.get("__value").file.split("_")[0]
          - attribute: type
            expr: |
              env.get("__value")["type"].split(":")[0]
          - attribute: maxLod
            expr: |
              env.get("__value").maxLod
          - attribute: file
            expr: |
              env.get("__value").file

      - id: 65074ffc-9113-4fbf-8957-9ba1de4c56ab
        name: FileWriterTsvFilePath
        type: action
        action: FileWriter
        with:
          format: tsv
          output: |
            file::join_path(env.get("outputPath"), "maxLod.tsv")

      - id: c32a279d-97be-4584-b282-4d65627b1132
        name: FeatureLodFilter
        type: action
        action: FeatureLodFilter
        with:
          filterKey: path

      - id: 2ccf7b99-4123-446e-8ff7-049be1c604c7
        name: FeatureDuplicateFilter
        type: action
        action: FeatureDuplicateFilter

      - id: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        name: AttributeMapperByLod0-2
        type: action
        action: AttributeMapper
        with:
          mappers:
            - attribute: meshcode
              expr: |
                let file = file::extract_filename(env.get("__value")["path"]);
                file[0..8]
            - attribute: city_code
              valueAttribute: cityCode
            - attribute: city_name
              valueAttribute: cityName
            - attribute: feature_type
              valueAttribute: gmlName
            - attribute: gml_id
              valueAttribute: gmlId
            - attribute: lod
              valueAttribute: maxLod

      - id: 7a17c4f9-dd4d-44b0-936c-50c394272016
        name: MVTWriter
        type: action
        action: MVTWriter
        with:
          layerName: |
            env.get("__value").feature_type.split(":")[1]
          minZoom: 8
          maxZoom: 16
          output: |
            file::join_path(env.get("outputPath"), env.get("__value").feature_type.split(":")[0] + "_lod" + env.get("__value").lod)

    edges:
      - id: 5ebf24ab-1d98-49d5-8f58-eb7c18d27244
        from: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        to: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        fromPort: default
        toPort: default
      - id: 64196428-ea1b-4177-9d66-28331fad14f8
        from: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        to: ded2e272-e05c-4918-86b3-aa9f763da6e6
        fromPort: default
        toPort: default
      - id: cf845867-6ffc-4b83-9fd5-e376a22470e2
        from: ded2e272-e05c-4918-86b3-aa9f763da6e6
        to: 4ffbb8a3-371e-4938-aa73-c142f11bb04b
        fromPort: default
        toPort: default
      - id: f7c94aaf-e43c-4779-893c-e5b23c0cf643
        from: 4ffbb8a3-371e-4938-aa73-c142f11bb04b
        to: dc498449-5478-4bff-abaa-59f2d160925f
        fromPort: default
        toPort: default
      - id: 046c94ea-9937-4439-b5f8-c8a616f6599d
        from: dc498449-5478-4bff-abaa-59f2d160925f
        to: 1fb4ce1c-538a-436d-8dfa-79185e032de3
        fromPort: default
        toPort: default
      - id: 59c14dab-0e56-4f90-85e6-0c8cfa6d1d14
        from: 1fb4ce1c-538a-436d-8dfa-79185e032de3
        to: 52ff7b3c-5fbb-4ad2-86d9-5df50429e3b4
        fromPort: default
        toPort: default
      - id: 993360df-5cfd-4525-9626-bfe13fa62117
        from: 52ff7b3c-5fbb-4ad2-86d9-5df50429e3b4
        to: 65074ffc-9113-4fbf-8957-9ba1de4c56ab
        fromPort: default
        toPort: default
      - id: 60ee038e-db4c-4c70-8c0a-a9cbfba726d0
        from: 4ffbb8a3-371e-4938-aa73-c142f11bb04b
        to: c32a279d-97be-4584-b282-4d65627b1132
        fromPort: default
        toPort: default
      - id: 90f518e2-3ca0-404f-821c-5dffe4e57597
        from: c32a279d-97be-4584-b282-4d65627b1132
        to: 2ccf7b99-4123-446e-8ff7-049be1c604c7
        fromPort: up_to_lod0
        toPort: default
      - id: 83c68df9-a61b-4cad-8f64-ea20186e9db1
        from: c32a279d-97be-4584-b282-4d65627b1132
        to: 2ccf7b99-4123-446e-8ff7-049be1c604c7
        fromPort: up_to_lod1
        toPort: default
      - id: dde1d751-fe3e-4283-8742-ec4a61a41574
        from: c32a279d-97be-4584-b282-4d65627b1132
        to: 2ccf7b99-4123-446e-8ff7-049be1c604c7
        fromPort: up_to_lod0
        toPort: default
      - id: 7303c673-ccf3-4075-9eec-97176ced4b86
        from: c32a279d-97be-4584-b282-4d65627b1132
        to: 2ccf7b99-4123-446e-8ff7-049be1c604c7
        fromPort: up_to_lod2
        toPort: default
      - id: 841f1bed-a4d3-4425-a754-4f0dd7461ead
        from: 2ccf7b99-4123-446e-8ff7-049be1c604c7
        to: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        fromPort: default
        toPort: default
      - id: bef08313-519f-48b5-b74c-6744bbc6bee2
        from: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        to: 7a17c4f9-dd4d-44b0-936c-50c394272016
        fromPort: default
        toPort: default
