# yaml-language-server: $schema=https://raw.githubusercontent.com/reearth/reearth-flow/main/engine/schema/workflow.json
id: cd93ce74-eff8-479c-abec-f8a1bc24cbda
name: "PLATEAU4-DataConvert-06-urf-area-workflow"
entryGraphId: 6f9f1383-8a50-4a22-b815-5d06a9f9398a
with:
  cityGmlPath:
  cityCode:
  codelistsPath:
  schemasPath:
  targetPackages:
    - urf
    - area
  workerArtifactPath:
graphs:
  - !include ../../../../graphs/plateau4/folder_and_file_path_reader.yml
  - id: 6f9f1383-8a50-4a22-b815-5d06a9f9398a
    name: entry_point
    nodes:
      - id: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        name: FeatureCreator
        type: action
        action: FeatureCreator
        with:
          creator: |
            [
              #{
                cityGmlPath: env.get("cityGmlPath"),
                cityCode: env.get("cityCode") ?? file::extract_filename(env.get("cityGmlPath"))[0..5],
              },
            ]

      - id: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        name: FolderAndFilePathReader
        type: subGraph
        subGraphId: c6863b71-953b-4d15-af56-396fc93fc617

      - id: ded2e272-e05c-4918-86b3-aa9f763da6e6
        name: FeatureReaderByCityGml
        type: action
        action: FeatureCityGmlReader
        with:
          format: citygml
          flatten: true
          dataset: |
            env.get("__value")["path"]

      - id: 1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6e
        name: AttributeManagerPreFlattener
        type: action
        action: AttributeManager
        with:
          operations:
            - attribute: meshcode
              method: create
              value: |
                let file = file::extract_filename(env.get("__value")["path"]);
                file.split("_")[0]
            - attribute: gml_id
              method: create
              value: |
                env.get("__feature_id") ?? env.get("__value")["gmlId"]
            - attribute: feature_type
              method: create
              value: env.get("__value")["featureType"] ?? env.get("__value")["gmlName"]

      - id: 5daabfc0-2bda-4f8d-b206-d7a388469f7a
        name: AttributeFlattener
        type: action
        action: PLATEAU4.AttributeFlattener

      - id: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        name: AttributeManager
        type: action
        action: AttributeManager
        with:
          operations:
          - attribute: featureId
            method: remove
          - attribute: featureParentId
            method: remove
          - attribute: geometryName
            method: remove
          - attribute: cityCode
            method: rename
            value: city_code
          - attribute: cityName
            method: rename
            value: city_name
          - attribute: lod
            method: rename
            value: _lod
          - attribute: gmlId
            method: remove
          - attribute: gmlPropertyName
            method: remove
          - attribute: fileIndex
            method: remove
          - attribute: root
            method: remove
          - attribute: cityGmlPath
            method: remove
          - attribute: admin
            method: remove
          - attribute: area
            method: remove
          - attribute: package
            method: remove
          - attribute: extension
            method: remove
          - attribute: dirRoot
            method: remove
          - attribute: gmlRootId
            method: remove
          - attribute: maxLod
            method: remove
          - attribute: dirSchemas
            method: remove
          - attribute: dirCodelists
            method: remove
          - attribute: path
            method: remove
          - attribute: name
            method: remove
          - attribute: udxDirs
            method: rename
            value: _udxDirs
          - attribute: featureType
            method: remove
          - attribute: gmlName
            method: remove

      - id: a3b4c5d6-e7f8-9a0b-1c2d-3e4f5a6b7c8d
        name: StripFeatureTypePrefix
        type: action
        action: AttributeManager
        with:
          operations:
          - attribute: feature_type_without_prefix
            method: create
            value: |
              env.get("__value").feature_type.split(":")[1]

      - id: b5c6d7e8-f9a0-1b2c-3d4e-5f6a7b8c9d0e
        name: AttributeDuplicateFilter
        type: action
        action: AttributeDuplicateFilter
        with:
          filterBy:
            - feature_type

      - id: d1e2f3a4-b5c6-d7e8-f9a0-b1c2d3e4f5a6
        name: AttributeConversionTable
        type: action
        action: AttributeConversionTable
        with:
          format: csv
          inline: !include urf_japanese_converter.csv.txt
          rules:
          - featureFroms:
            - feature_type_without_prefix
            featureTo: feature_type_ja
            conversionTableKeys:
            - name
            conversionTableTo: description

      - id: c7d8e9f0-a1b2-c3d4-e5f6-a7b8c9d0e1f2
        name: JsonWriter
        type: action
        action: JsonWriter
        with:
          output: |
            file::join_path(env.get("workerArtifactPath"), "dictionary.json")
          converter: |
            #{
              urf: env.get("__features").map(|f| #{
                name: f.feature_type_without_prefix,
                description: f.feature_type_ja
              })
            }

      - id: 1f8b3c4e-5a2d-4e1f-9b7c-3d5e6f8a9b0c
        name: FeatureSorter
        type: action
        action: FeatureSorter
        with:
          attributes:
            - feature_type
          order: ascending

      - id: b4862d31-4bb2-49b1-8f0d-6d58dd4cb385
        name: MvtWriter
        type: action
        action: MVTWriter
        with:
          layerName: |
            env.get("__value").feature_type.split(":")[1]
          minZoom: 8
          maxZoom: 16
          skipUnderscorePrefix: true
          colonToUnderscore: true
          output: |
            let feature_type = env.get("__value").feature_type;
            feature_type.replace(":", "_");
            file::join_path(env.get("workerArtifactPath"), feature_type)

    edges:
      - id: 5ebf24ab-1d98-49d5-8f58-eb7c18d27244
        from: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        to: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        fromPort: default
        toPort: default
      - id: 7b81f501-3f07-4cec-bf9b-9cefcebdf47d
        from: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        to: ded2e272-e05c-4918-86b3-aa9f763da6e6
        fromPort: default
        toPort: default
      - id: cf845867-6ffc-4b83-9fd5-e376a22470e2
        from: ded2e272-e05c-4918-86b3-aa9f763da6e6
        to: 1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6e
        fromPort: default
        toPort: default
      - id: 7e8f9a0b-1c2d-3e4f-5a6b-7c8d9e0f1a2b
        from: 1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6e
        to: 5daabfc0-2bda-4f8d-b206-d7a388469f7a
        fromPort: default
        toPort: default
      - id: ad52c3e6-68ff-4844-a7b2-d302fc0aef14
        from: 5daabfc0-2bda-4f8d-b206-d7a388469f7a
        to: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        fromPort: default
        toPort: default
      - id: d8e9f0a1-b2c3-d4e5-f6a7-b8c9d0e1f2a3
        from: 5daabfc0-2bda-4f8d-b206-d7a388469f7a
        to: a3b4c5d6-e7f8-9a0b-1c2d-3e4f5a6b7c8d
        fromPort: default
        toPort: default
      - id: e9f0a1b2-c3d4-e5f6-a7b8-c9d0e1f2a3b4
        from: a3b4c5d6-e7f8-9a0b-1c2d-3e4f5a6b7c8d
        to: b5c6d7e8-f9a0-1b2c-3d4e-5f6a7b8c9d0e
        fromPort: default
        toPort: default
      - id: f0a1b2c3-d4e5-f6a7-b8c9-d0e1f2a3b4c5
        from: b5c6d7e8-f9a0-1b2c-3d4e-5f6a7b8c9d0e
        to: d1e2f3a4-b5c6-d7e8-f9a0-b1c2d3e4f5a6
        fromPort: default
        toPort: default
      - id: a1b2c3d4-e5f6-a7b8-c9d0-e1f2a3b4c5d6
        from: d1e2f3a4-b5c6-d7e8-f9a0-b1c2d3e4f5a6
        to: c7d8e9f0-a1b2-c3d4-e5f6-a7b8c9d0e1f2
        fromPort: default
        toPort: default
      - id: 3c7d9e2f-4a5b-6c8d-9e0f-1a2b3c4d5e6f
        from: 6e5ed9fc-006e-4dbe-8699-4663dba795cb
        to: 1f8b3c4e-5a2d-4e1f-9b7c-3d5e6f8a9b0c
        fromPort: default
        toPort: default
      - id: e862f11a-88a6-4c1b-a743-ba80253039df
        from: 1f8b3c4e-5a2d-4e1f-9b7c-3d5e6f8a9b0c
        to: b4862d31-4bb2-49b1-8f0d-6d58dd4cb385
        fromPort: default
        toPort: default
