// Code generated by Kitex v0.14.1. DO NOT EDIT.
package reearthcms

import (
	server "github.com/cloudwego/kitex/server"
	v1 "github.com/reearth/reearth-flow/api/kitex_gen/reearth/cms/v1"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler v1.ReEarthCMS, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler v1.ReEarthCMS, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
