#!/usr/bin/env python3
"""Mirror the PROJ-data grid catalogue into a directory.

Builds the grid set the deployed engine reads through `FLOW_PROJ_GRID_DIR`. The
directory is then synced to the bucket the workers mount read-only:

    python3 mirror.py ./proj-grids 1.24.0
    gcloud storage rsync --recursive --delete-unmatched-destination-objects \\
        ./proj-grids gs://<bucket>/proj-grids

Downloads every file the PROJ-data CDN publishes, verifies each against the
SHA-256 the catalogue records, and writes MANIFEST.tsv and NOTICE.md alongside
them. A data file whose licence cannot be established is left out rather than
carried unattributed; the report at the end names anything skipped. The
publishers' own README files are mirrored too, since they state the conditions
the licence table cannot capture.

Usage: mirror.py <destination directory> <PROJ-data version tag>
"""

import concurrent.futures
import csv
import hashlib
import io
import json
import os
import sys
import time
import urllib.error
import urllib.request

CDN = "https://cdn.proj.org"
LICENCES = "https://raw.githubusercontent.com/OSGeo/PROJ-data/refs/tags/{}/copyright_and_licenses.csv"
# The catalogue is a rolling mirror that can run ahead of the last release, so a
# file added after the pinned tag has no licence row there. `master` is consulted
# for those rather than dropping them.
LICENCES_LATEST = (
    "https://raw.githubusercontent.com/OSGeo/PROJ-data/master/copyright_and_licenses.csv"
)
WORKERS = 8
ATTEMPTS = 4


def fetch(url):
    """The bytes at `url`, retrying a few times on transient failures."""
    for attempt in range(1, ATTEMPTS + 1):
        try:
            with urllib.request.urlopen(url, timeout=120) as response:
                return response.read()
        except (urllib.error.URLError, TimeoutError) as e:
            if attempt == ATTEMPTS:
                raise RuntimeError(f"{url}: {e}") from e
            time.sleep(2 * attempt)


def read_licences(version):
    """Map file name to (copyright holder, licence), preferring the pinned tag."""
    table = {}
    for url in (LICENCES_LATEST, LICENCES.format(version)):
        for row in csv.DictReader(io.StringIO(fetch(url).decode("utf-8"))):
            name = os.path.basename(row["filename"] or "")
            holder = (row["copyright"] or "").strip()
            licence = (row["license"] or "").strip()
            if name and licence:
                table[name] = (holder, licence)
    return table


def download(dest, entry):
    """Fetch one catalogue entry into `dest`, verifying its digest."""
    path = os.path.join(dest, entry["name"])
    if os.path.exists(path) and os.path.getsize(path) == entry["file_size"]:
        with open(path, "rb") as fh:
            if hashlib.sha256(fh.read()).hexdigest() == entry["sha256sum"]:
                return None
    body = fetch(f"{CDN}/{entry['name']}")
    digest = hashlib.sha256(body).hexdigest()
    if digest != entry["sha256sum"]:
        return f"{entry['name']}: sha256 {digest} != catalogue {entry['sha256sum']}"
    tmp = f"{path}.part"
    with open(tmp, "wb") as fh:
        fh.write(body)
    os.replace(tmp, path)
    return None


def write_manifest(dest, entries, version):
    with open(os.path.join(dest, "MANIFEST.tsv"), "w") as fh:
        fh.write(f"# PROJ-data {version}\tgenerated by mirror.py\n")
        fh.write("name\tsize\tsha256\tcountry\tsource\tlicense\n")
        for e in entries:
            fh.write(
                "\t".join(
                    (
                        e["name"],
                        str(e["file_size"]),
                        e["sha256sum"],
                        e.get("source_country") or "",
                        e["holder"] or e.get("source") or "",
                        e["licence"],
                    )
                )
                + "\n"
            )


def write_notice(dest, entries, version, skipped):
    total = sum(e["file_size"] for e in entries)
    licences = sorted({e["licence"] for e in entries})
    with open(os.path.join(dest, "NOTICE.md"), "w") as fh:
        fh.write("# Third-party geodetic grids\n\n")
        fh.write(
            f"This image carries {len(entries)} files ({total / 1048576:.0f} MiB) "
            f"mirrored from the PROJ-data {version} distribution "
            "(<https://github.com/OSGeo/PROJ-data>). Each is redistributed under "
            "the licence its publisher applied to it, listed below. The `*_README.txt` "
            "files beside them are the publishers' own statements of source and "
            "conditions, reproduced verbatim. Generated by `mirror.py`; do not edit "
            "by hand.\n\n"
        )
        fh.write(
            "The Japanese grids are used with the permission of the Geospatial "
            "Information Authority of Japan recorded in the PROJ-data source "
            "distribution: 測量法に基づく国土地理院長承認(使用)R 2JHs 501.\n\n"
        )
        fh.write("## Licences represented\n\n")
        for licence in licences:
            count = sum(1 for e in entries if e["licence"] == licence)
            fh.write(f"- {licence} ({count} files)\n")
        if skipped:
            fh.write(
                "\n## Not included\n\nNo licence could be established for these, so "
                "they were left out:\n\n"
            )
            for name in skipped:
                fh.write(f"- `{name}`\n")
        fh.write("\n## Files\n\n| File | Publisher | Licence |\n|---|---|---|\n")
        for e in sorted(entries, key=lambda e: e["name"]):
            fh.write(f"| `{e['name']}` | {e['holder'] or e.get('source') or ''} | {e['licence']} |\n")


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    dest, version = sys.argv[1], sys.argv[2]
    os.makedirs(dest, exist_ok=True)

    catalogue = json.loads(fetch(f"{CDN}/files.geojson"))["features"]
    licences = read_licences(version)

    wanted, skipped = [], []
    for feature in catalogue:
        entry = dict(feature["properties"])
        if entry.get("version_removed"):
            continue
        holder, licence = licences.get(entry["name"], ("", ""))
        if entry["name"].endswith("README.txt"):
            # The publishers' own licence statements: always carried, and not
            # themselves a redistributed dataset.
            holder, licence = holder or "PROJ-data", licence or "documentation"
        if not licence:
            skipped.append(entry["name"])
            continue
        entry["holder"], entry["licence"] = holder, licence
        wanted.append(entry)

    failures = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=WORKERS) as pool:
        for error in pool.map(lambda e: download(dest, e), wanted):
            if error:
                failures.append(error)
    if failures:
        sys.exit("\n".join(failures))

    write_manifest(dest, wanted, version)
    write_notice(dest, wanted, version, skipped)
    total = sum(e["file_size"] for e in wanted)
    print(f"mirrored {len(wanted)} files, {total / 1048576:.0f} MiB, PROJ-data {version}")
    if skipped:
        print(f"skipped {len(skipped)} file(s) with no licence recorded: {', '.join(skipped)}")


if __name__ == "__main__":
    main()
