# https://taplo.tamasfe.dev/configuration/formatter-options.html

[formatting]
trailing_newline = true
reorder_keys = true
align_comments = false
allowed_blank_lines = 1
array_auto_collapse = false
array_auto_expand = false
include = ["*.toml"]
indent_string = "    " # 4 spaces
reorder_arrays = true
