# https://taplo.tamasfe.dev/configuration/formatter-options.html
include = [
  "Cargo.toml",
  "crates/*/Cargo.toml",
  "examples/Cargo.toml",
  "tests/Cargo.toml",
  "tools/plateau-gis-quality-checker/src-tauri/Cargo.toml",
]

[formatting]
align_comments = false
allowed_blank_lines = 1
array_auto_collapse = false
array_auto_expand = false
reorder_arrays = true
reorder_keys = true
trailing_newline = true
