[workspace]
members = [
  "crates/*",
  "examples",
  "tests",
]
resolver = "2"

[workspace.package]
authors = ["Re:Earth Flow Contributors"]
edition = "2021"
exclude = ["benches/", "test-data/", "testdata/"]
homepage = "https://github.com/reearth/reearth-flow"
license = "MIT OR Apache-2.0"
repository = "https://github.com/reearth/reearth-flow"
rust-version = "1.77" # Remember to update clippy.toml as well
version = "0.1.0"

[profile.dev]
opt-level = 0

# Like release, but with full debug symbols and with stack unwinds. Useful for e.g. `perf`.
[profile.debug-fast]
debug = true
incremental = false
inherits = "release"
panic = "unwind"
strip = "none"

# Optimized release profile
[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"
strip = true

[workspace.dependencies]
reearth-flow-action = {path = "crates/action"}
reearth-flow-action-log = {path = "crates/action-log"}
reearth-flow-action-universal = {path = "crates/action-universal"}
reearth-flow-common = {path = "crates/common"}
reearth-flow-eval-expr = {path = "crates/eval-expr"}
reearth-flow-macros = {path = "crates/macros"}
reearth-flow-state = {path = "crates/state"}
reearth-flow-storage = {path = "crates/storage"}
reearth-flow-telemetry = {path = "crates/telemetry"}
reearth-flow-workflow = {path = "crates/workflow"}
reearth-flow-workflow-cli = {path = "crates/cli"}
reearth-flow-workflow-runner = {path = "crates/workflow-runner"}
reearth-flow-xml = {path = "crates/xml"}

async-recursion = "1.1.0"
async-trait = "0.1.80"
async_zip = {version = "0.0.17", features = ["full"]}
bytes = {version = "1.6.0", features = ["serde"]}
color-eyre = "0.6.3"
colorsys = "0.6.7"
csv = "1.3.0"
derive_more = "0.99.17"
directories = "5.0.1"
futures = "0.3.30"
itertools = "0.12.1"
jsonpath_lib = "0.3.0"
nutype = {version = "0.4.2", features = ["serde"]}
object_store = "0.9.1"
once_cell = "1.19.0"
opendal = {version = "0.45.1", features = ["layers-metrics"]}
opentelemetry = {version = "0.22.0", default-features = false, features = ["trace", "metrics"]}
opentelemetry-otlp = {version = "0.15.0", default-features = false, features = ["grpc-tonic", "trace", "metrics"]}
opentelemetry-semantic-conventions = "0.14.0"
opentelemetry-stdout = {version = "0.3.0", default-features = false, features = ["trace", "metrics"]}
opentelemetry_sdk = {version = "0.22.1", default-features = false, features = ["trace", "rt-tokio", "metrics"]}
parking_lot = "0.12.1"
petgraph = "0.6.4"
pretty_assertions = "1.4.0"
rand = "0.8.5"
rayon = "1.10.0"
regex = "1.10.4"
rhai = {version = "1.18.0", features = ["internals", "sync", "serde"]}
rstest = "0.19.0"
rust_xlsxwriter = "0.64.1"
serde = {version = "1.0.197", features = ["derive"]}
serde_derive = "1.0.197"
serde_json = {version = "1.0.115", features = ["arbitrary_precision"]}
serde_with = "3.7.0"
serde_yaml = "0.9.34"
sha2 = "0.10.8"
slog = {version = "2.7.0", features = ["release_max_level_trace", "max_level_trace"]}
strum = "0.26.2"
strum_macros = "0.26.2"
tempfile = "3.10.1"
thiserror = "1.0.58"
time = {version = "0.3.34", features = ["formatting"]}
tokio = {version = "1.37.0", features = ["full", "time"]}
tokio-stream = {version = "0.1.15", features = ["sync"]}
tokio-util = {version = "0.7.10", features = ["full"]}
toml = "0.8.12"
tracing = "0.1.40"
tracing-opentelemetry = {version = "0.23.0", default-features = false, features = ["tracing-log", "metrics"]}
tracing-subscriber = {version = "0.3.18", features = [
  "env-filter",
  "std",
  "time",
]}
typetag = "0.2.16"
uuid = {version = "1.8.0", features = [
  "v4",
  "fast-rng",
  "macro-diagnostics",
  "serde",
]}
