services:
  jaeger:
    image: "jaegertracing/all-in-one:1.58"
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  otel-collector:
    image: otel/opentelemetry-collector:0.104.0
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./containers/compose/otel-collector/config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "11888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "14317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger
