FROM rust:1.81 as builder

WORKDIR /usr/src/app
COPY . .

RUN cargo build --release 

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/app/target/release/grpc /usr/local/bin/grpc

WORKDIR /usr/local/bin
COPY .env .
EXPOSE 50051

CMD ["grpc"] 