version: "3"

services:
  redis:
    # Redis service configuration
    build:
      context: .
      dockerfile: Redis.Dockerfile
    container_name: websocket_redis_container
    ports:
      - "6379:6379" # Expose Redis port
    volumes:
      - redis_data:/data # Persist Redis data
    restart: always # Ensure Redis always restarts

  websocket:
    # WebSocket service configuration
    build:
      context: .
      dockerfile: Websocket.Dockerfile
    container_name: websocket_app_container
    ports:
      - "8000:8000" # Expose WebSocket port
    depends_on:
      - redis # Ensure Redis starts before WebSocket service
    environment:
      - REDIS_URL=redis://redis:6379 # Point to the Redis service
    restart: always # Ensure WebSocket service always restarts

volumes:
  # Define persistent volume for Redis data
  redis_data:
