version: "3"

services:
  redis:
    # Redis service configuration
    build:
      context: .
      dockerfile: Redis.Dockerfile
    container_name: websocket_redis_container
    ports:
      - "6379:6379" # Expose Redis port
    volumes:
      - redis_data:/data # Persist Redis data
    restart: always # Ensure Redis always restarts

volumes:
  # Define persistent volume for Redis data
  redis_data:
