[config]
skip_core_tasks = true
default_to_workspace = false

[env]
PROJ_NAME = "websocket-server"

[tasks.format]
script = '''
#!/usr/bin/env bash -eux
cargo fmt --all
'''

[tasks.check]
script = '''
#!/usr/bin/env bash -eux
cargo check --workspace --all-targets --all-features
'''

[tasks.clippy]
script = '''
#!/usr/bin/env bash -eux
cargo clippy --workspace --all-targets --all-features -- -D warnings
'''

[tasks.test]
script = '''
#!/usr/bin/env bash -eux
cargo test --workspace --all-targets --all-features
'''

[tasks.doc]
script = '''
#!/usr/bin/env bash -eux
cargo clean --doc
cargo doc --no-deps --all-features
'''

[tasks.coverage]
script = '''
#!/usr/bin/env bash -eux
rm -rf target/debug/deps/${PROJ_NAME}-*

export CARGO_INCREMENTAL=0
export RUSTFLAGS="-Zinstrument-coverage"
export LLVM_PROFILE_FILE="${PROJ_NAME}-%p-%m.profraw"

cargo build --workspace --verbose
cargo test --workspace --verbose

grcov . -s . --binary-path ./target/debug/ -t lcov --branch --ignore-not-existing -o lcov.info
'''

[tasks.check-easy-panic]
script = '''
#!/usr/bin/env bash -eux
git ls-files | grep -E '.rs$' | (! xargs grep 'unimplemented!')
git ls-files | grep -E '.rs$' | (! xargs grep 'todo!')
'''

[tasks.format-taplo]
script = '''
#!/usr/bin/env bash -eux
taplo fmt
'''

[tasks.build]
script = '''
#!/usr/bin/env bash -eux
cargo build --release
'''

[tasks.run]
script = '''
#!/usr/bin/env bash -eux
cargo run
'''

[tasks.ci]
dependencies = [
    "format",
    "check",
    "clippy",
    "test",
    "format-taplo",
]
