# yaml-language-server: $schema=https://raw.githubusercontent.com/reearth/reearth-flow/main/engine/schema/workflow.json
id: 83307700-04b9-490c-b6a1-11b93e7f7a8a
name: "PLATEAU4-quality-check-01-common-workflow"
entryGraphId: 34bf873b-3364-46b0-8153-efeb9568bb3c
with:
  cityGmlPath:
  codelists:
  schemas:
  objectLists:
  outputPath:
graphs:
  - !include ../../../../graphs/plateau4/xml_validator.yml
  - !include ../../../../graphs/plateau4/domain_of_definition_validator.yml
  - !include ../../../../graphs/plateau4/quality-check/01-01-common.yml
  - !include ../../../../graphs/plateau4/quality-check/01-02-common.yml
  - id: 34bf873b-3364-46b0-8153-efeb9568bb3c
    name: entry_point
    nodes:
      - id: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        name: FeatureCreator
        type: action
        action: FeatureCreator
        with:
          creator: |
            [
              #{
                cityGmlPath: env.get("cityGmlPath"),
                cityCode: env.get("cityCode") ?? file::extract_filename(env.get("cityGmlPath"))[0..5],
                baseCityCode: env.get("cityCode") ?? file::extract_filename(env.get("cityGmlPath"))[0..5],
                objectListPath: env.get("objectLists"),
                codelists: env.get("codelists"),
                schemas: env.get("schemas"),
              },
            ]

      - id: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        name: PLATEAU4.CommonQualityCheck-01-01-common
        type: subGraph
        subGraphId: 5db64758-df36-486d-86bd-437b72fd9fc8

      - id: 9309842a-a3a7-4d1b-9216-ef523a6b4789
        name: PLATEAU4.CommonQualityCheck-01-02-common
        type: subGraph
        subGraphId: b7a4c316-112e-4473-bd25-4c158db4e561

      - id: 65074ffc-9113-4fbf-8957-9ba1de4c56ab
        name: ZipFileWriter
        type: action
        action: ZipFileWriter
        with:
          output: |
            let filename = file::extract_filename_without_ext(env.get("cityGmlPath")) + "_qc_result.zip";
            let dirname = env.get("workerArtifactPath") ?? env.get("outputPath");
            file::join_path(dirname, filename)

      - id: 9e0f1a2b-3c4d-5e6f-7a8b-9c0d1e2f3a4b
        name: StatisticsCalculatorTotalErrors
        type: action
        action: StatisticsCalculator
        with:
          calculations:
            - newAttribute: totalErrorCount
              expr: |
                env.get("__value")["totalErrorCount"] ?? 0

      - id: a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d
        name: FeatureFilterNoErrors
        type: action
        action: FeatureFilter
        with:
          conditions:
            - expr: |
                env.get("__value")["totalErrorCount"] == 0
              outputPort: default

      - id: b2c3d4e5-6f7a-8b9c-0d1e-2f3a4b5c6d7e
        name: FileWriterQcResultOk
        type: action
        action: JsonWriter
        with:
          converter: '[]'
          output: |
            let filename = file::extract_filename_without_ext(env.get("cityGmlPath")) + "_qc_result_ok";
            let dirname = env.get("workerArtifactPath") ?? env.get("outputPath");
            file::join_path(dirname, filename)

    edges:
      - id: 5ebf24ab-1d98-49d5-8f58-eb7c18d27244
        from: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        to: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        fromPort: default
        toPort: default
      - id: f47c77ad-c465-48cf-bdf5-36e385ffbd41
        from: 90f40a3e-61d3-48e2-a328-e7226c2ad1ae
        to: 9309842a-a3a7-4d1b-9216-ef523a6b4789
        fromPort: default
        toPort: default
      - id: 7b81f501-3f07-4cec-bf9b-9cefcebdf47d
        from: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        to: 65074ffc-9113-4fbf-8957-9ba1de4c56ab
        fromPort: default
        toPort: default
      - id: f69a4e59-b7b8-4fab-97cd-112b4d1e4a53
        from: 9309842a-a3a7-4d1b-9216-ef523a6b4789
        to: 65074ffc-9113-4fbf-8957-9ba1de4c56ab
        fromPort: default
        toPort: default
      - id: c3d4e5f6-7a8b-9c0d-1e2f-3a4b5c6d7e8f
        from: d376f32b-7ce8-4721-8b9e-bfa39d71b860
        to: 9e0f1a2b-3c4d-5e6f-7a8b-9c0d1e2f3a4b
        fromPort: summaryOutput
        toPort: default
      - id: d4e5f6a7-8b9c-0d1e-2f3a-4b5c6d7e8f9a
        from: 9309842a-a3a7-4d1b-9216-ef523a6b4789
        to: 9e0f1a2b-3c4d-5e6f-7a8b-9c0d1e2f3a4b
        fromPort: summaryOutput
        toPort: default
      - id: e5f6a7b8-9c0d-1e2f-3a4b-5c6d7e8f9a0b
        from: 9e0f1a2b-3c4d-5e6f-7a8b-9c0d1e2f3a4b
        to: a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d
        fromPort: default
        toPort: default
      - id: f6a7b8c9-0d1e-2f3a-4b5c-6d7e8f9a0b1c
        from: a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d
        to: b2c3d4e5-6f7a-8b9c-0d1e-2f3a4b5c6d7e
        fromPort: default
        toPort: default
