name: Build and Deploy API

on:
  workflow_call:
    inputs:
      sha_short:
        required: true
        type: string
      new_tag:
        required: true
        type: string
      new_tag_short:
        required: true
        type: string
      name:
        required: true
        type: string
      sha:
        required: true
        type: string

jobs:
  build-api:
    name: Build API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'server/api/go.mod'
          check-latest: true

      - name: Build API
        run: |
          cd server/api
          go build -v -o reearth-flow-api .

      - name: Create distribution directory
        run: |
          mkdir -p server/api/dist
          mv server/api/reearth-flow-api server/api/dist/

      - name: Rename Artifacts
        if: ${{ inputs.name != 'blank' }}
        run: |
          cd server/api/dist
          mv reearth-flow-api reearth-flow-api_${{ inputs.name }}

      - name: List Artifacts
        run: ls -l server/api/dist

      - name: Upload API Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-artifacts
          path: server/api/dist/*

  build-docker-image:
    name: Build and Push Docker Image
    needs: build-api
    runs-on: ubuntu-latest
    if: ${{ inputs.name != 'blank' || inputs.new_tag != 'blank' }}
    env:
      IMAGE_NAME: reearth/reearth-flow-api
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download API Artifacts
        uses: actions/download-artifact@v4
        with:
          name: api-artifacts
          path: server/api/dist

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Build Options
        id: options
        run: |
          TAG="${{ inputs.new_tag_short != 'blank' && inputs.new_tag_short || '' }}"
          NAME="${{ inputs.name }}"
          SHA="${{ inputs.sha_short }}"

          if [[ -n "$TAG" ]]; then
            PLATFORMS="linux/amd64,linux/arm64"
            VERSION="$TAG"
            TAGS="$IMAGE_NAME:$TAG"

            if [[ ! "$TAG" =~ '-' ]]; then
              TAGS+=",${IMAGE_NAME}:${TAG%.*}"
              TAGS+=",${IMAGE_NAME}:${TAG%%.*}"
              TAGS+=",${IMAGE_NAME}:latest"
            fi
          else
            PLATFORMS="linux/amd64"
            VERSION="$SHA"
            TAGS="$IMAGE_NAME:$NAME"
          fi

          echo "platforms=$PLATFORMS" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: server/api/Dockerfile
          platforms: ${{ steps.options.outputs.platforms }}
          push: true
          build-args: VERSION=${{ steps.options.outputs.version }}
          tags: ${{ steps.options.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          sbom: true

  deploy-to-cloud-run:
    name: Deploy to Cloud Run (Nightly)
    needs: build-docker-image
    runs-on: ubuntu-latest
    if: ${{ inputs.name == 'nightly' }}
    permissions:
      contents: read
      id-token: write
    env:
      IMAGE: reearth/reearth-flow-api:nightly
      CLOUD_RUN_SERVICE: reearth-flow-api
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.GC_SA_EMAIL }}
          workload_identity_provider: ${{ secrets.GC_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Push Docker Image to GCP Artifact Registry
        run: |
          docker pull ${{ env.IMAGE }}
          docker tag ${{ env.IMAGE }} ${{ secrets.API_IMAGE_GC }}
          docker push ${{ secrets.API_IMAGE_GC }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.CLOUD_RUN_SERVICE }} \
            --image ${{ secrets.API_IMAGE_GC }} \
            --region ${{ secrets.GC_REGION }} \
            --platform managed \
            --quiet
