name: ci-log-subscriber
on:
  workflow_call:
env:
  GO_VERSION: "1.22"

jobs:
  ci-log-subscriber-lint:
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'v')
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1
          args: --timeout=10m
          working-directory: log_subscriber

  ci-log-subscriber-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: log_subscriber/go.sum
      - name: test
        run: go test ./... -v -race -coverprofile=coverage.txt -covermode=atomic -timeout 10m
        working-directory: log_subscriber
      - name: Send coverage report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: log_subscriber
