name: ci-websocket

on:
  workflow_call:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: short

defaults:
  run:
    working-directory: server/websocket

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Install Protocol Buffers Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      - name: Install Thrift Compiler
        run: |
          sudo apt-get install -y thrift-compiler
      - name: Cache cargo registry
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: server/websocket
          shared-key: "websocket-ci"
      - name: Install required tools
        uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli,cargo-make
      - name: Check
        run: cargo make check
      - name: Rustfmt
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo make clippy
      # - name: Taplo
      #   run: taplo fmt --check
      - name: Run tests
        run: cargo make test
