name: ci-websocket

on:
  workflow_call:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: short

defaults:
  run:
    working-directory: server/websocket

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: dtolnay/rust-toolchain@2ea1b3bdd0261867664fd125505456a7b9c3385c # 1.93.1
        with:
          components: clippy, rustfmt
      - name: Install Protocol Buffers Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      - name: Install Thrift Compiler
        run: |
          sudo apt-get install -y thrift-compiler
      - name: Cache cargo registry
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          workspaces: server/websocket
          shared-key: "websocket-ci"
      - name: Install required tools
        uses: taiki-e/install-action@5f57d6cb7cd20b14a8a27f522884c4bc8a187458 # v2.75.19
        with:
          tool: taplo-cli,cargo-make
      - name: Check
        run: cargo make check
      - name: Rustfmt
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo make clippy
      # - name: Taplo
      #   run: taplo fmt --check
      - name: Run tests
        run: cargo make test
