name: Crates deny

on:
  push:
    branches:
      - main
    paths:
      - worker/Cargo.lock
      - worker/deny.toml
      - ".github/workflows/crates-deny.yml"
  pull_request:
    paths:
      - worker/Cargo.lock
      - worker/deny.toml
      - ".github/workflows/crates-deny.yml"

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./worker

jobs:
  cargo-deny:
    name: cargo deny check
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check all
          # Clear out arguments to not pass `--all-features` to `cargo deny`.
          # many crates have an `openssl` feature which enables banned dependencies
          arguments: ""
          manifest-path: worker/Cargo.toml
