name: deploy-ui-nightly
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy'
        required: true
env:
  GCP_REGION: us-central1
  CLOUD_RUN_SERVICE: reearth-flow-ui
jobs:
  deploy_ui:
    name: Deploy UI to Cloud Run with CDN
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $CLOUD_RUN_SERVICE \
            --image reearth/reearth-flow-ui:${{ github.event.inputs.image_tag }} \
            --region $GCP_REGION \
            --platform managed \
            --allow-unauthenticated